  "Cavite City": "甲米地市",
  "Sao Raimundo No": "圣雷蒙多诺纳图",
  "Nakhon Si Thamm": "洛坤府",
  "Noosa Airport": "努萨机场",
  "Sigonella Airpo": "西戈内拉机场",
  "Notodden Airpor": "诺托登机场",
  "Point Mugu": "穆古角",
  "Bintuni-Papua I": "宾图尼-巴布亚岛",
  "Williamtown": "威廉敦",
  "Normanton Airpo": "诺曼顿机场",
  "Ponta do Sol": "蓬塔杜索尔",
  "Wajima": "轮岛",
  "Del Norte Inter": "北地国际机场",
  "Niuatoputapu": "纽阿托普塔普",
  "Virginia Beach": "弗吉尼亚比奇",
  "Ranai-Natuna Be": "拉奈-纳土纳贝萨尔",
  "Pilanesberg": "匹兰斯堡",
  "Numbulwar Airpo": "农布尔瓦机场",
  "En Nahud": "纳胡德",
  "Nuremberg": "纽伦堡",
  "Nuiqsut": "努伊克苏特",
  "Nukutavake": "努库塔瓦克",
  "Nulato": "努拉托",
  "Mountain View": "山景城",
  "Nullabor Motel": "纳拉伯汽车旅馆",
  "Norsup": "诺苏普",
  "Nakuru": "纳库鲁",
  "Oak Harbor": "橡树港",
  "Novy Urengoy": "新乌连戈伊",
  "Neiva": "内瓦",
  "Nevada": "内华达",
  "Narvik": "纳尔维克",
  "Beckwourth": "贝克沃思",
  "Novo Aripuana": "新阿里普阿南",
  "Navegantes": "纳韦甘蒂斯",
  "Moheli Bandar E": "莫埃利班达尔埃萨拉姆",
  "Norwich": "诺里奇",
  "Nyagan": "尼亚甘",
  "Nyeri": "涅里",
  "Quantico": "匡蒂科",
  "Sunyani": "苏尼亚尼",
  "Nanyuki": "纳纽基",
  "Nadym": "纳德姆",
  "Nyngan Airport": "宁根机场",
  "Nyurba": "纽尔巴",
  "Pyinmana": "彬马那",
  "Nyaung U": "良乌",
  "Monywar": "蒙育瓦",
  "Nzagi": "恩扎吉",
  "Maria Reiche Ne": "玛丽亚·赖歇·诺伊曼",
  "Nzerekore": "恩泽雷科雷",
  "Shindand Airpor": "申丹德机场",
  "Bagram": "巴格拉姆",
  "Cacoal": "卡科尔",
  "Oamaru Airport": "奥马鲁机场",
  "Olanchito": "奥兰奇托",
  "Marina": "玛丽娜",
  "Sharana": "沙拉纳",
  "Camp Bastion": "堡垒营",
  "Obock": "奥博克",
  "Okeechobee": "奥基乔比",
  "Oberpfaffenhofe": "上普法芬霍芬",
  "Obidos": "奥比多斯",
  "Zoersel": "佐尔塞尔",
  "North Connel": "北康奈尔",
  "Kobuk": "科布克",
  "Coca": "科卡",
  "Ocean City": "海洋城",
  "Ocala": "奥卡拉",
  "Nacogdoches": "纳科多奇斯",
  "Boolgeeda Airpo": "布尔吉达机场",
  "Oceanside": "奥欣赛德",
  "Ocana": "奥卡尼亚",
  "Ouadda": "瓦达",
  "Oakdale": "奥克代尔",
  "Oodnadatta Airp": "乌德纳达塔机场",
  "Odiham": "奥迪厄姆",
  "Ouanda Djalle": "旺达贾勒",
  "Cordillo Downs": "科迪洛唐斯",
  "Long Seridan": "长塞里丹",
  "Bodaybo": "博代博",
  "Ord River": "奥德河",
  "Oudomsay": "乌多姆塞",
  "Orel": "奥廖尔",
  "Paloemeu": "帕洛默",
  "Osceola": "奥西奥拉",
  "San Antonio Oes": "西圣安东尼奥",
  "Olafsfjordur": "奥拉夫斯菲厄泽",
  "Ofu Village": "奥富村",
  "Ogallala": "奥加拉拉",
  "Orangeburg": "奥兰治堡",
  "Ogeranang Airpo": "奥格拉南机场",
  "Ogle": "奥格尔",
  "Yonaguni Airpor": "与那国机场",
  "Bongor": "邦戈尔",
  "Ogdensburg": "奥格登斯堡",
  "Ordu": "奥尔杜",
  "Ouargla": "瓦尔格拉",
  "Beslan": "别斯兰",
  "RNZAF Base Ohak": "新西兰皇家空军奥哈基亚基地",
  "Okha": "奥哈",
  "Wyk auf Fohr": "福尔岛维克",
  "Sohar": "苏哈尔",
  "Ourilandia Do N": "北欧里兰迪亚",
  "Izu Oshima": "伊豆大岛",
  "Okushiri Airpor": "奥尻机场",
  "Sidi Ahmed": "西迪艾哈迈德",
  "Okierabu Airpor": "冲永良部机场",
  "Okaukuejo": "奥考奎霍",
  "Cottesmore": "科茨莫尔",
  "Okinoshima": "冲之岛",
  "Kokomo": "科科莫",
  "Oksibil-Papua I": "奥克西比尔-巴布亚岛",
  "Okmulgee": "奥克马尔吉",
  "Okondja": "奥孔贾",
  "Fussa": "福生",
  "Okaba-Papua Isl": "奥卡巴-巴布亚岛",
  "Kzyl-Yar": "克孜勒亚尔",
  "Oakey Airport": "奥基机场",
  "Orland": "奥兰",
  "Sao Paulo De Ol": "圣保罗-德奥利文萨",
  "Old Town": "旧镇",
  "Olean": "奥利安",
  "Wolf Point": "沃尔夫波因特",
  "Rif": "里夫",
  "Fuerte Olimpo": "奥林波堡",
  "Olympia": "奥林匹亚",
  "Sarmiento": "萨米恩托",
  "Olomouc": "奥洛穆茨",
  "Olympic Dam": "奥林匹克坝",
  "Nogales": "诺加莱斯",
  "Olive Branch": "奥利布兰奇",
  "Olney-Noble": "奥尔尼-诺布尔",
  "Olyokminsk": "奥廖克明斯克",
  "Omboue": "翁布埃",
  "Ormoc City": "奥尔莫克市",
  "Nome": "诺姆",
  "Mafraq": "马夫拉克",
  "Omidiyeh": "奥米迪耶",
  "Omak": "奥马克",
  "Marmul": "马尔穆尔",
  "Winona": "威诺纳",
  "Mornington Isla": "莫宁顿岛",
  "Moanamani-Papua": "莫阿纳马尼-巴布亚",
  "Odate": "大馆",
  "Olenyok": "奥列尼奥克",
  "O'Neill": "奥尼尔",
  "Socorro": "索科罗",
  "Zonguldak": "宗古尔达克",
  "Monkira Airport": "蒙基拉机场",
  "Onslow Airport": "昂斯洛机场",
  "Colon": "科隆",
  "Olney": "奥尔尼",
  "Oskaloosa": "奥斯卡卢萨",
  "Newman": "纽曼",
  "Toksook Bay": "托克苏克湾",
  "Cooma": "库马",
  "Mooraberree Air": "穆拉贝里机场",
  "Onotoa": "奥诺托阿",
  "Kopasker": "科帕斯克",
  "Oenpelli Airpor": "奥恩佩利机场",
  "Opelousas": "奥珀卢萨斯",
  "Salinopolis": "萨利诺波利斯",
  "Balimo": "巴利莫",
  "Orocue": "奥罗奎",
  "Worcester": "伍斯特",
  "Northampton": "北安普敦",
  "Orapa Airport": "奥拉帕机场",
  "Northway": "诺斯韦",
  "Oruro": "奥鲁罗",
  "Noorvik": "努尔维克",
  "Ormara Raik": "奥尔马拉莱克",
  "Oriximina": "奥里希米纳",
  "Oscoda": "奥斯科达",
  "Omora": "奥莫拉",
  "Oskarshamn Airp": "奥斯卡港机场",
  "Osan Air Base": "乌山空军基地",
  "Osborne Mine Ai": "奥斯本矿场机场",
  "Ostend": "奥斯坦德",
  "Kosciusko": "科修斯科",
  "Namsos": "纳姆索斯",
  "Koszalin Zegrze": "科沙林-泽格热",
  "Bol": "波尔",
  "Worthington": "沃辛顿",
  "North Bend": "北本德",
  "Gotalalamo-Moro": "戈塔拉拉莫-莫罗泰",
  "Tillamook": "蒂拉穆克",
  "Boutilimit": "布提利米特",
  "Ottumwa": "奥塔姆瓦",
  "Corredores": "科雷多雷斯",
  "El Rhin": "莱茵",
  "Kotzebue": "科策布",
  "Ouesso Airport": "韦索机场",
  "Oudtshoorn": "奥茨胡恩",
  "Ban Huoeisay Ai": "会晒机场",
  "Norman": "诺曼",
  "Batouri": "巴图里",
  "Bousso": "布索",
  "Zouerate": "祖埃拉特",
  "Ranon": "拉农",
  "Oroville": "奥罗维尔",
  "Overberg": "奥弗贝格",
  "Ovalle": "奥瓦列",
  "Olavarria": "奥拉瓦里亚",
  "Sovetskiy": "苏维埃茨基",
  "Owatonna": "奥瓦通纳",
  "Norwood": "诺伍德",
  "Norridgewock": "诺里奇沃克",
  "Kidlington": "基德灵顿",
  "Saint-Georges-d": "圣乔治-德洛耶龙",
  "Oxnard": "奥克斯纳德",
  "Morney Airport": "莫尼机场",
  "Goya": "戈亚",
  "Oyem": "奥耶姆",
  "Tres Arroyos": "特雷斯阿罗约斯",
  "Ozona": "奥佐纳",
  "Ozamiz City": "奥三棉示市",
  "Zagora": "扎戈拉",
  "Hpa-N": "帕安",
  "Bilaspur Airpor": "比拉斯布尔机场",
  "Albrook": "阿尔布鲁克",
  "Pagadian City": "巴加甸市",
  "Hanapepe": "哈纳佩佩",
  "Pattani Airport": "北大年机场",
  "Palo Alto": "帕洛阿尔托",
  "Port-au-Prince": "太子港",
  "Palmer": "帕尔默",
  "Paros Island": "帕罗斯岛",
  "Pauk": "包镇",
  "Paulo Afonso": "保罗阿方索",
  "Port-de-Paix": "和平港",
  "Pamol": "帕莫尔",
  "Poza Rica": "波萨里卡",
  "Paranaiba": "巴拉那伊巴",
  "Puerto Berrio": "贝里奥港",
  "Pine Bluff": "派恩布拉夫",
  "General Bartolo": "巴托洛梅·萨洛姆将军镇",
  "Zandery": "赞德赖",
  "Port Amboim": "安博因港",
  "Nandayure": "南达尤雷",
  "Putao": "葡萄",
  "Porto Dos Gauch": "南加州港",
  "St George": "圣乔治",
  "Porto Alegre Do": "北阿雷格里港",
  "Portage Creek": "波蒂奇克里克",
  "Prairie Du Chie": "普雷里德欣",
  "Potchefstroom": "波切夫斯特鲁姆",
  "Paso Caballos": "帕索卡瓦略斯",
  "Palacios": "帕拉西奥斯",
  "Picton": "皮克顿",
  "La Ribera": "里韦拉",
  "Principe Airpor": "普林西比机场",
  "Puerto Carreno": "卡雷尼奥港",
  "Picos": "皮库斯",
  "Puerto Inirida": "伊尼里达港",
  "Ponta do Ouro": "黄金角",
  "Prado": "普拉多",
  "Pindiu": "平迪乌",
  "Talang Gudang-S": "塔朗古当-苏门答腊",
  "Piedras Negras": "彼德拉斯内格拉斯",
  "Paysandu": "派桑杜",
  "Pedernales Airp": "佩德纳莱斯机场",
  "Pardubice": "帕尔杜比采",
  "Peenemunde": "佩内明德",
  "Pehuajo": "佩瓦霍",
  "Pelaneng": "佩拉嫩",
  "Puerto Maldonad": "马尔多纳多港",
  "Pecos": "佩科斯",
  "Pelotas": "佩洛塔斯",
  "Pecs-Pogany": "佩奇-波加尼",
  "Pechora": "伯朝拉",
  "Pacific City": "太平洋城",
  "Patreksfjordur": "帕特雷克斯菲厄泽",
  "Parsabad": "帕尔萨巴德",
  "Ilebo": "伊莱博",
  "Petersburg": "彼得斯堡",
  "Pantnagar": "潘特纳加尔",
  "Pangkal Pinang-": "邦加槟榔-邦加岛",
  "Pascagoula": "帕斯卡古拉",
  "Pagosa Springs": "帕戈萨斯普林斯",
  "Paragould": "帕拉古尔德",
  "Ponta Grossa": "蓬塔格罗萨",
  "Phan Rang": "潘郎",
  "New Philadelphi": "新费城",
  "Newport News": "纽波特纽斯",
  "Pinheiro": "皮涅罗",
  "Pahokee": "帕霍基",
  "Port Huron": "休伦港",
  "Philip": "菲利普",
  "The Monument Ai": "纪念碑机场",
  "Phitsanulok Air": "彭世洛机场",
  "Phetchabun Airp": "碧差汶机场",
  "St Petersburg-C": "圣彼得堡-克利尔沃特",
  "Pilar": "皮拉尔",
  "Pine Mountain": "派恩芒廷",
  "Parintins": "帕林廷斯",
  "Pisco": "皮斯科",
  "Pilot Point": "派洛特波因特",
  "Pirapora": "皮拉波拉",
  "Pikwitonei": "皮克维托内",
  "Pico Island": "皮库岛",
  "Pajala Airport": "帕亚拉机场",
  "Payson": "佩森",
  "Pedro Juan Caba": "佩德罗胡安卡瓦列罗",
  "Napaskiak": "纳帕斯基亚克",
  "Park Rapids": "帕克拉皮兹",
  "Parkes": "帕克斯",
  "Park Falls": "帕克福尔斯",
  "Porto Cheli": "波多河丽",
  "Playa Grande": "大普拉亚",
  "Pakhokku": "木各具",
  "Pangkalanbun-Bo": "庞卡兰布翁-婆罗洲",
  "Parakou": "帕拉库",
  "Port Keats Airp": "基茨港机场",
  "Pekanbaru-Sumat": "北干巴鲁-苏门答腊",
  "Pskov": "普斯科夫",
  "Palangkaraya-Ka": "帕朗卡拉亚-加里曼丹",
  "Playa Samara": "萨马拉海滩",
  "Pala": "帕拉",
  "Plymouth": "普利茅斯",
  "Point Lookout": "卢考特角",
  "La Palma": "拉帕尔马",
  "Pell City": "佩尔城",
  "Plato": "普拉托",
  "Palu-Celebes Is": "帕卢-西里伯斯岛",
  "Semey": "塞米伊",
  "Chake": "查克",
  "Pembina": "彭比纳",
  "Palmdale": "帕姆代尔",
  "Palma De Mallor": "马略卡岛帕尔马",
  "Palm Island Air": "棕榈岛机场",
  "Cold Bay": "冷湾",
  "Perito Moreno": "佩里托莫雷诺",
  "Palmerston Nort": "北帕默斯顿",
  "Palmyra Airport": "巴尔米拉机场",
  "Isla Margarita": "玛格丽塔岛",
  "Palmas": "帕尔马斯",
  "Puerto Madryn": "马德林港",
  "Palmar Sur": "南帕尔马",
  "Porto Nacional": "国家港",
  "Ponca City": "庞卡城",
  "Paranagua": "巴拉那瓜",
  "Pontianak-Borne": "坤甸-婆罗洲",
  "Princeton": "普林斯顿",
  "Popondetta": "波蓬德塔",
  "Puerto Natales": "纳塔莱斯港",
  "Panevezys": "帕内韦日斯",
  "Pondicherry Air": "本地治里机场",
  "Petrolina": "彼得罗利纳",
  "La Verne": "拉文",
  "Podor": "波多尔",
  "Fort Polk": "波尔克堡",
  "Poplar Bluff": "波普勒布拉夫",
  "Pocahontas": "波卡洪塔斯",
  "Potosi": "波托西",
  "Patos De Minas": "帕图斯迪米纳斯",
  "Poptun": "波普顿",
  "Pocos De Caldas": "波苏斯迪卡尔达斯",
  "Port of Spain": "西班牙港",
  "Ken Jones": "肯·琼斯",
  "Presov": "普雷绍夫",
  "Portoroz": "波尔托罗",
  "Pontoise": "蓬图瓦兹",
  "Powell": "鲍威尔",
  "Pampa": "潘帕",
  "Presidente Prud": "普鲁登特总统城",
  "Prospect Creek": "普罗斯佩克特克里克",
  "Puerto Penasco": "佩尼亚斯科港",
  "Parsons": "帕森斯",
  "Perai Tepuy Air": "佩莱特普伊机场",
  "Port Pirie Airp": "皮里港机场",
  "Tjipara-Java Is": "芝帕拉-爪哇岛",
  "Petropavlosk": "彼得罗巴甫洛夫斯克",
  "Phaplu": "帕普卢",
  "Pompano Beach": "庞帕诺比奇",
  "Popayan": "波帕扬",
  "Proserpine": "普罗瑟派恩",
  "Paraparaumu Air": "帕拉帕拉乌穆机场",
  "Pasir Pengaraya": "巴西彭加拉延",
  "Pa Pun": "帕本",
  "Papa Westray": "帕帕韦斯特雷",
  "Pouso Alegre": "波苏阿雷格里",
  "La Dorada": "拉多拉达",
  "Palenque Intern": "帕伦克国际机场",
  "Paso Robles": "帕索罗布尔斯",
  "Phrae Airport": "帕府机场",
  "Praslin Island": "普拉兰岛",
  "Prieska": "普里斯卡",
  "Portimao Airpor": "波尔蒂芒机场",
  "Prishtina": "普里什蒂纳",
  "Propriano": "普罗普里亚诺",
  "Presidencia Roq": "罗克总统城",
  "Paruma": "帕鲁马",
  "Pye": "派伊",
  "Prerov": "普热罗夫",
  "Philipsburg": "菲利普斯堡",
  "Pittsfield": "皮茨菲尔德",
  "Sankt Peter-Ord": "圣彼得-奥尔丁",
  "Poso-Celebes Is": "波索-西里伯斯岛",
  "Palestine": "巴勒斯坦",
  "Putussibau-Born": "普图西包-婆罗洲",
  "Passos": "帕苏斯",
  "Port Alsworth": "奥尔斯沃思港",
  "Malolo Lailai I": "马洛洛莱莱岛",
  "Potgietersrus": "波特希特勒斯",
  "Port Heiden": "海登港",
  "Portland Airpor": "波特兰机场",
  "Pontiac": "庞蒂亚克",
  "Palmarito": "帕尔马里托",
  "Patterson": "帕特森",
  "Pato Branco": "帕图布兰库",
  "Pointe-a-Pitre": "皮特尔角城",
  "Porto De Moz": "莫斯港",
  "Pittsburg": "匹兹堡",
  "Pratt": "普拉特",
  "Porterville": "波特维尔",
  "Pottstown": "波茨敦",
  "Pitalito": "皮塔利托",
  "Tocumen": "托库门",
  "Shell Mera": "梅拉",
  "Price": "普赖斯",
  "Puerto Deseado": "德塞阿多港",
  "Puerto Obaldia": "奥瓦尔迪亚港",
  "Port Augusta Ai": "奥古斯塔港机场",
  "Pukarua": "普卡鲁阿",
  "Po": "波城",
  "Puerto Asis": "阿西斯港",
  "Puerto Varas": "巴拉斯港",
  "Providencia": "普罗维登西亚",
  "Provincetown": "普罗温斯敦",
  "El Porvenir": "波韦尼尔",
  "Placerville": "普莱瑟维尔",
  "Paranavai": "巴拉那瓦伊",
  "Pikeville": "派克维尔",
  "Dolna Mitropoli": "下米特罗波利亚",
  "Portoviejo": "波托维耶霍",
  "Chukotka": "楚科奇",
  "Plainview": "普莱恩维尤",
  "Plentywood": "普伦蒂伍德",
  "Pevek": "佩韦克",
  "Bremerton": "布雷默顿",
  "Pinedale": "派恩代尔",
  "Puerto Escondid": "埃斯孔迪多港",
  "Vila Baleira": "巴莱拉镇",
  "Surin Airport": "素林机场",
  "Velasquez": "贝拉斯克斯",
  "Jeypore": "杰伊波尔",
  "Pakyong": "帕克容",
  "Cacique Aramare": "卡西克阿拉马雷",
  "Yakutia": "雅库特",
  "Payam Airport": "帕亚姆机场",
  "Puerto Putumayo": "普图马约港",
  "Andravida": "安德拉维达",
  "Paz De Ariporo": "阿里波罗和平镇",
  "Pietermaritzbur": "彼得马里茨堡",
  "Fort Sandeman": "桑德曼堡",
  "Phinda": "芬达",
  "Puerto Ordaz-Ci": "奥尔达斯港-圭亚那城",
  "Castro": "卡斯特罗",
  "Barbacena": "巴尔巴塞纳",
  "L'Aquila": "拉奎拉",
  "Arnhem": "阿纳姆",
  "Ech Cheliff Air": "谢利夫机场",
  "Bella Coola": "贝拉库拉",
  "St Nazaire": "圣纳泽尔",
  "Sobral": "索布拉尔",
  "Colatina": "科拉蒂纳",
  "Botucatu": "博图卡图",
  "Canela": "卡内拉",
  "Currais Novos": "新库赖斯",
  "Curitibanos": "库里蒂巴诺斯",
  "Coningsby": "科宁斯比",
  "Cachoeira Do Su": "南卡舒埃拉",
  "Dracena": "德拉塞纳",
  "Conselheiro Laf": "孔塞涅罗拉法耶蒂",
  "Egelsbach": "埃格尔斯巴赫",
  "Czechowice-Dzie": "切霍维采-杰济采",
  "Boufarik Airpor": "布法里克机场",
  "Duxford": "达克斯福德",
  "Guaira": "瓜伊拉",
  "Limeira": "利梅拉",
  "Lencois Paulist": "圣保罗伦索伊斯",
  "Montenegro": "黑山",
  "Garanhuns": "加拉尼翁斯",
  "Alagoinhas": "阿拉戈伊尼亚斯",
  "Gifu": "岐阜",
  "Gyor": "杰尔",
  "Hasselt": "哈瑟尔特",
  "Piracicaba": "皮拉西卡巴",
  "Taguatinga": "塔瓜廷加",
  "Taubate": "陶巴特",
  "Husum": "胡苏姆",
  "Novo Hamburgo": "新汉堡",
  "Tres Coracoes": "三心市",
  "Iguatu": "伊瓜图",
  "Rio Claro": "里奥克拉鲁",
  "Itapetinga": "伊塔佩廷加",
  "Jubail": "朱拜勒",
  "Jindabyne Airpo": "金德拜恩机场",
  "Kautokeino Air": "凯于图凯努机场",
  "Lasham": "拉舍姆",
  "Gliwice Glider": "格利维采滑翔机机场",
  "Blida Airport": "卜利达机场",
  "Lahti Vesivehma": "拉赫蒂-韦西韦赫马",
  "Lausanne": "洛桑",
  "Latina": "拉蒂纳",
  "Lublin Radwiec": "卢布林-拉德维茨",
  "Mafra": "马夫拉",
  "Shahid Asyaee A": "沙希德阿西亚埃机场",
  "Marina Di Massa": "马萨码头",
  "Mainz": "美因茨",
  "Neuchatel Airpo": "纳沙泰尔机场",
  "Annemasse": "阿讷马斯",
  "Namur": "那慕尔",
  "Nova Iguacu": "新伊瓜苏",
  "Mococa": "莫科卡",
  "Ansbach": "安斯巴赫",
  "Norvenich Airpo": "诺尔韦尼希机场",
  "Sao Borja": "圣博尔雅",
  "Owerri": "奥韦里",
  "Padova": "帕多瓦",
  "Palapye": "帕拉佩",
  "Opole": "奥波莱",
  "Pirassununga": "皮拉苏农加",
  "Piacenza": "皮亚琴察",
  "Rancagua": "兰卡瓜",
  "Narromine Airpo": "纳罗迈恩机场",
  "Warren Airport": "沃伦机场",
  "Rieti": "列蒂",
  "Resende": "雷森迪",
  "Sabadell": "萨瓦德尔",
  "Sao Carlos": "圣卡洛斯",
  "Setif": "塞提夫",
  "Moshi": "莫希",
  "San Nicolas": "圣尼古拉斯",
  "Salerno": "萨勒诺",
  "New Amsterdam": "新阿姆斯特丹",
  "Blois": "布卢瓦",
  "Chichester": "奇切斯特",
  "Chun Chon City": "春川市",
  "Gusau": "古绍",
  "Utsunomiya Airp": "宇都宫机场",
  "St. Ives": "圣艾夫斯",
  "Varese": "瓦雷泽",
  "Uniao Da Vitori": "维多利亚联盟",
  "Forssa": "福尔萨",
  "Avare": "阿瓦雷",
  "Nowy Targ": "新塔尔格",
  "Barra De Santo": "圣安东尼奥-达巴拉",
  "Gdynia": "格丁尼亚",
  "Bialystok": "比亚韦斯托克",
  "Szeged": "塞格德",
  "Relizane Airpor": "雷利扎内机场",
  "Arezzo": "阿雷佐",
  "Tokua": "托库阿",
  "Racine": "拉辛",
  "Arar": "阿尔阿尔",
  "Rafaela": "拉斐拉",
  "Raglan Airfield": "拉格伦机场",
  "Riverside": "里弗赛德",
  "Ramingining Air": "拉明吉宁机场",
  "Ravenna": "拉文纳",
  "Ribeirao Preto": "里贝朗普雷图",
  "Rasht": "拉什特",
  "Cravo Norte": "北克拉沃",
  "Rawalakot": "拉瓦拉科特",
  "Borba": "博尔巴",
  "Robinvale Airpo": "罗宾韦尔机场",
  "Roseburg": "罗斯堡",
  "Rebun Airport A": "礼文机场",
  "Red Bluff": "雷德布拉夫",
  "Straubing": "施特劳宾",
  "Robore": "罗博雷",
  "Rurenabaque": "鲁雷纳瓦克",
  "Orbost Airport": "奥博斯特机场",
  "Marsabit": "马萨比特",
  "Walterboro": "沃尔特伯勒",
  "Ruby": "鲁比",
  "Rockdale": "罗克代尔",
  "Redcliffe": "雷德克利夫",
  "Richmond Airpor": "里士满机场",
  "Reconquista": "雷孔基斯塔",
  "Reed City": "里德城",
  "Rio Cuarto": "里奥夸尔托",
  "Rum Cay Airport": "朗姆礁机场",
  "Red Dog": "红狗",
  "Redencao": "雷登桑",
  "Merdei-Papua Is": "梅尔代-巴布亚岛",
  "Rincon de los S": "林孔-德洛斯索斯",
  "Richard Toll": "理查德托尔",
  "Reao Airport": "雷奥机场",
  "Larz": "拉尔茨",
  "Reedsville": "里德斯维尔",
  "Rawson": "罗森",
  "Requena": "雷克纳",
  "Retalhuleu": "雷塔卢莱乌",
  "Rost Airport": "勒斯特机场",
  "Reyes": "雷耶斯",
  "Rafai": "拉法伊",
  "Refugio": "雷富希奥",
  "Raufarhofn": "勒伊法赫本",
  "Uturoa": "乌图罗阿",
  "La Rosita": "拉罗西塔",
  "Balurghat": "巴卢尔加特",
  "Rangiroa Airpor": "朗伊罗阿机场",
  "Gorno-Altaysk": "戈尔诺-阿尔泰斯克",
  "Orang Airport": "奥兰机场",
  "Burgos": "布尔戈斯",
  "Rengat-Sumatra": "仁卡-苏门答腊",
  "Reykholar": "雷克霍拉尔",
  "Rio Hondo": "里奥翁多",
  "Ruhengeri": "鲁亨盖里",
  "Rodes Island": "罗得岛",
  "Ramechhap": "拉梅查普",
  "Badanjilin": "巴丹吉林",
  "Riberalta": "里韦拉尔塔",
  "Rice Lake": "赖斯莱克",
  "Richfield": "里奇菲尔德",
  "Rio Hato": "里奥阿托",
  "Rioja": "里奥哈",
  "Rifle": "赖夫尔",
  "Rodriguez de Me": "罗德里格斯-德门多萨",
  "Riverton": "里弗顿",
  "Riyan": "里扬",
  "Rajbiraj": "拉杰比拉杰",
  "Logrono": "洛格罗尼奥",
  "Rafsanjan Airpo": "拉夫桑詹机场",
  "Montague": "蒙塔古",
  "Rock Hill": "罗克希尔",
  "Sipora Island": "西波拉岛",
  "Rockport": "罗克波特",
  "Poteau": "波托",
  "Ras Al Khaimah": "哈伊马角",
  "Rockwood": "罗克伍德",
  "Merlo": "梅洛",
  "Arlit": "阿尔利特",
  "Buraimi": "布赖米",
  "Marsa Alam": "马萨阿拉姆",
  "Renmark Airport": "伦马克机场",
  "Rumginae Airpor": "鲁姆吉奈机场",
  "Ramstein": "拉姆施泰因",
  "Corvera": "科尔韦拉",
  "Mariposa": "马里波萨",
  "Ronneby Airport": "龙讷比机场",
  "Mc Minnville": "麦克明维尔",
  "Universal City": "环球城",
  "New Richmond": "新里士满",
  "Yoron Airport": "与论机场",
  "Ghaba": "加巴",
  "Renton": "伦顿",
  "Ranau": "兰瑙",
  "Rensselaer": "伦斯勒",
  "Robertson": "罗伯逊",
  "Rogers": "罗杰斯",
  "Robinhood Airpo": "罗宾汉机场",
  "Roi Et Airport": "黎逸机场",
  "Paipa": "派帕",
  "Rondonopolis": "龙多诺波利斯",
  "Rota Island": "罗塔岛",
  "Babelthuap Isla": "巴伯尔图阿普岛",
  "Rostov-on-Don": "顿河畔罗斯托夫",
  "Roseau": "罗索",
  "Rio Mayo": "里奥马约",
  "Rolpa": "罗尔帕",
  "Ngukurr Airport": "努古尔机场",
  "Rosh Pina": "罗什皮纳",
  "Roundup": "朗德阿普",
  "Ruoqiang": "若羌",
  "El Reno": "埃尔里诺",
  "Qayyarah": "卡亚拉",
  "Shimoga": "希莫加",
  "Marree Airport": "马里机场",
  "Port Mathurin": "马蒂兰港",
  "Rourkela Airpor": "鲁尔克拉机场",
  "Merrill": "梅里尔",
  "Raroia Airport": "拉罗亚机场",
  "Warroad": "沃罗德",
  "Roseberth Airpo": "罗斯伯斯机场",
  "Rock Sound": "罗克桑德",
  "Russian Mission": "俄罗斯米申",
  "Ransiki-Papua I": "兰西基-巴布亚岛",
  "Russell": "拉塞尔",
  "Ruston": "拉斯顿",
  "Ad Damazin": "达马津",
  "Rotuma": "罗图马",
  "Roatan Island": "罗阿坦岛",
  "Ratnagiri Airpo": "勒德纳吉里机场",
  "Satar Tacik-Flo": "萨塔尔塔西克-弗洛勒斯岛",
  "Raton": "拉顿",
  "Rutland Plains": "拉特兰平原",
  "Rottnest Island": "罗特内斯特岛",
  "Maratua Island": "马拉图阿岛",
  "Arua": "阿鲁阿",
  "Shahroud Airpor": "沙赫鲁德机场",
  "Butembo": "布滕博",
  "Ruidoso": "鲁伊多索",
  "Rukumkot": "鲁库姆科特",
  "Gadhdhoo": "加杜",
  "Rumjatar": "鲁姆贾塔尔",
  "St Denis": "圣但尼",
  "Rupsi India Air": "鲁普西印度机场",
  "Rurutu Airport": "鲁鲁图机场",
  "Rutland": "拉特兰",
  "Rubelsanto": "鲁贝尔桑托",
  "Ruinas de Copan": "科潘遗址",
  "Rio Verde": "里奥韦尔德",
  "Saravena": "萨拉韦纳",
  "Rorvik": "勒尔维克",
  "Reivilo": "雷维洛",
  "Tulsa": "塔尔萨",
  "Ravensthorpe Ai": "雷文斯索普机场",
  "Raivavae Airpor": "赖瓦瓦埃机场",
  "Rivera": "里韦拉",
  "Redwood Falls": "雷德伍德福尔斯",
  "Rawlins": "罗林斯",
  "Rivne": "罗夫诺",
  "Rexburg": "雷克斯堡",
  "Roxas City": "罗哈斯市",
  "Rybinsk": "雷宾斯克",
  "Rygge": "吕格",
  "Rahim Yar Khan": "拉希姆亚尔汗",
  "El Turbio": "图尔比奥",
  "Ryazan": "梁赞",
  "Taytay Airport": "泰泰机场",
  "Ramsar Airport": "拉姆萨尔机场",
  "Roanoke Rapids": "罗阿诺克拉皮兹",
  "Saratoga": "萨拉托加",
  "Safford": "萨福德",
  "Kakadi": "卡卡迪",
  "Saudarkrokur": "索伊达克罗库尔",
  "La Mesa": "拉梅萨",
  "Andros Island": "安德罗斯岛",
  "Salton City": "索尔顿城",
  "Sawu-Sawu Islan": "萨武-萨武岛",
  "Siena": "锡耶纳",
  "Sasstown": "萨斯敦",
  "San Bernardino": "圣贝纳迪诺",
  "Suabi Airport": "苏阿比机场",
  "Sabang-We Islan": "沙璜-韦岛",
  "Koundara": "孔达拉",
  "Sao Mateus": "圣马特乌斯",
  "Santa Ana del Y": "圣安娜-德尔亚库马",
  "Sheboygan": "希博伊根",
  "Sibi": "锡比",
  "Saibai Island": "赛拜岛",
  "Steamboat Sprin": "斯廷博特斯普林斯",
  "Sabetta": "萨贝塔",
  "Springbok": "斯普林博克",
  "Shelby": "谢尔比",
  "Sibiu": "锡比乌",
  "Scribner": "斯克里布纳",
  "Sulaco": "苏拉科",
  "Scottsdale": "斯科茨代尔",
  "Schenectady": "斯克内克塔迪",
  "Paramillo Airpo": "帕拉米洛机场",
  "Saarbrucken": "萨尔布吕肯",
  "Aktau": "阿克套",
  "Mende": "芒德",
  "Santiago de Com": "圣地亚哥-德孔波斯特拉",
  "Shetland Island": "设得兰群岛",
  "Socotra Islands": "索科特拉群岛",
  "Langebaanweg": "兰格班韦格",
  "Lubango": "卢班戈",
  "Santiago del Es": "圣地亚哥-德尔埃斯特罗",
  "Sanandaj Airpor": "萨南达季机场",
  "Santa Rosa de C": "圣罗莎-德科潘",
  "Sand Point": "桑德波因特",
  "Sado Airport": "佐渡机场",
  "Tel Aviv": "特拉维夫",
  "Sedona": "塞多纳",
  "Sebring": "赛百灵",
  "Selinsgrove": "塞林斯格罗夫",
  "Senggeh-Papua I": "森格-巴布亚岛",
  "Selma": "塞尔玛",
  "Seguela": "塞盖拉",
  "Bengkalis-Sumat": "明古鲁-苏门答腊",
  "Seymour": "西摩",
  "Seronera": "塞罗勒那",
  "Sievierodonetsk": "北顿涅茨克",
  "Siwa": "锡瓦",
  "Selibaby": "塞利巴比",
  "Sfax": "斯法克斯",
  "St-Francois": "圣弗朗索瓦",
  "Inglaterra": "英格兰",
  "San Fernando Ai": "圣费尔南多机场",
  "San Felipe Inte": "圣费利佩国际机场",
  "Safi": "萨菲",
  "Soure": "苏雷",
  "Pawtucket": "波塔基特",
  "Sheghnan": "舍格南",
  "Sonderborg": "桑德堡",
  "Siegerland Airp": "锡格兰德机场",
  "Simanggang": "新巫鲁",
  "St George Airpo": "圣乔治机场",
  "Shay Gap": "谢伊加普",
  "Sanggata-Timor": "桑加塔-帝汶",
  "Sanga Sanga Air": "桑加桑加机场",
  "Sierra Grande": "谢拉格兰德",
  "Songea": "松盖阿",
  "Songkhla Airpor": "宋卡机场",
  "Nakashibetsu": "中标津",
  "Shire": "希雷",
  "Shungnak": "顺那克",
  "Shishmaref": "希什马廖夫",
  "Sehonghong": "塞洪洪",
  "Shirahama": "白滨",
  "Shelton": "谢尔顿",
  "Sokcho Airport": "束草机场",
  "Southport Airpo": "绍斯波特机场",
  "Shepparton Airp": "谢珀顿机场",
  "Shageluk": "沙格卢克",
  "Shinyanga": "欣延加",
  "Seshutes": "塞舒特斯",
  "Sibiti": "西比蒂",
  "Espargos": "埃斯帕戈斯",
  "Simara": "锡马拉",
  "Silgadi Doti": "锡尔加迪多蒂",
  "Sidi Ifni": "西迪伊夫尼",
  "Siglufjordur": "锡格吕菲厄泽",
  "Sikeston": "西克斯顿",
  "Sila Mission": "西拉米申",
  "Simbai": "辛拜",
  "Smithton Airpor": "史密斯顿机场",
  "Pasirkuning-Sin": "巴西古宁-辛唐",
  "Sishen": "西申",
  "Sullivan": "沙利文",
  "Singleton": "辛格尔顿",
  "San Juan de Mar": "圣胡安-德马尔科纳",
  "San Joaquin": "圣华金",
  "San Jose del Ca": "圣何塞-德尔卡沃",
  "Sao Jose Dos Ca": "圣若泽-杜斯坎普斯",
  "Sao Gabriel Da": "圣加布里埃尔-达卡舒埃拉",
  "St Johns": "圣约翰斯",
  "Sao Jose Do Rio": "圣若泽-杜里约普雷图",
  "Sesheke": "塞谢凯",
  "San Jose de Chi": "圣何塞-德奇基托斯",
  "Velas": "维拉斯",
  "Basseterre": "巴斯特尔",
  "Suki": "苏基",
  "Geiteryggen": "盖特吕根",
  "Thessaloniki": "塞萨洛尼基",
  "Surkhet": "苏尔赫特",
  "Shaktoolik": "沙克图利克",
  "Hadsel": "哈德瑟尔",
  "Sekakes": "塞卡克斯",
  "Vojens": "沃延斯",
  "Skiros Island": "斯基罗斯岛",
  "St Catherine In": "圣凯瑟琳国际机场",
  "Skwentna": "斯昆特纳",
  "Saransk": "萨兰斯克",
  "Mirpur Khas": "米尔普尔哈斯",
  "Salta": "萨尔塔",
  "Storm Lake": "斯托姆莱克",
  "Sliac": "斯利亚奇",
  "Sulayel Airport": "苏莱伊勒机场",
  "Siloam Springs": "西罗亚泉",
  "Solwesi": "索卢韦齐",
  "Karijini Nation": "卡里基尼国家公园",
  "Saranac Lake": "萨拉纳克湖",
  "Sulphur Springs": "萨尔弗斯普林斯",
  "Silistra": "锡利斯特拉",
  "Salida": "萨利达",
  "Castries": "卡斯特里",
  "Shimla Airport": "西姆拉机场",
  "Saltillo": "萨尔蒂约",
  "Vila do Porto": "波尔图镇",
  "Cerro Sombrero": "索姆布雷罗山",
  "Somerset": "萨默塞特",
  "Samos Island": "萨摩斯岛",
  "St Michael": "圣迈克尔",
  "Stella Maris": "斯特拉马里斯",
  "Semporna": "仙本那",
  "Salmon": "萨蒙",
  "Santa Monica": "圣莫尼卡",
  "Sampit-Borneo I": "桑皮特-婆罗洲岛",
  "Sheep Mountain": "羊山",
  "Samedan Airport": "萨梅丹机场",
  "Smara": "斯马拉",
  "Simenti": "西门蒂",
  "Stoelmanseiland": "斯托尔曼塞兰",
  "Snake Bay Airpo": "蛇湾机场",
  "Preguica": "普雷吉萨",
  "San Ignacio de": "圣伊格纳西奥-德贝拉斯科",
  "Stanthorpe Airn": "斯坦索普机场",
  "Pinar Del Rio": "比那尔德里奥",
  "Snyder": "斯奈德",
  "Shawnee": "肖尼",
  "Shannon": "香农",
  "Sakon Nakhon Ai": "沙功那空机场",
  "St Paul Island": "圣保罗岛",
  "Santa Elena de": "圣埃莱娜-德瓦伊伦",
  "Thandwe": "丹兑",
  "Sabana de Mar": "萨瓦纳-德马尔",
  "Semnan": "塞姆南",
  "Sarmellek": "萨尔梅莱克",
  "Sorocaba": "索罗卡巴",
  "Souanke": "苏安凯",
  "Semonkong": "塞蒙孔",
  "San Tome Airpor": "圣多美机场",
  "Luganville": "卢甘维尔",
  "Soderhamn": "南泰利耶",
  "Sorong-Papua Is": "索龙-巴布亚岛",
  "Seldovia": "塞尔多维亚",
  "Show Low": "肖洛",
  "Sogamoso": "索加莫索",
  "Stronsay": "斯特朗赛",
  "Solenzara": "索伦扎拉",
  "Sta Cruz de la": "拉帕尔马圣克鲁斯",
  "Sepulot": "塞普洛特",
  "Spearfish": "斯皮尔菲什",
  "St Petersburg": "圣彼得堡",
  "Sparti": "斯巴达",
  "Trier": "特里尔",
  "Menongue": "梅农盖",
  "Spencer": "斯潘塞",
  "Giza": "吉萨",
  "San Pedro Airpo": "圣佩德罗机场",
  "Springdale": "斯普林代尔",
  "Santa Ynez": "圣伊内斯",
  "Southern Cross": "南十字",
  "San Francisco d": "圣弗朗西斯科-德阿西斯",
  "Son-La": "山罗",
  "Sleetmute": "斯利特缪特",
  "Sao Miguel Do A": "圣米格尔-杜阿拉瓜亚",
  "Sanana-Seram Is": "萨纳纳-斯兰岛",
  "Storuman Airpor": "斯图吕曼机场",
  "Soroako-Celebes": "索罗阿科-西里伯斯",
  "Skive": "斯基沃",
  "Sao Miguel Do O": "西圣米格尔",
  "Sao Lourenco Do": "南圣洛伦索",
  "Scampton": "斯坎普顿",
  "Searcy": "瑟西",
  "Semarang-Java I": "三宝垄-爪哇岛",
  "Sarh": "萨尔",
  "San Borja": "圣博尔哈",
  "Strahan Airport": "斯特拉恩机场",
  "Svea": "斯韦阿",
  "Leirvik": "莱尔维克",
  "Soroti": "索罗提",
  "Sari": "萨里",
  "Sumter": "萨姆特",
  "Solapur": "索拉普",
  "Alstahaug": "阿尔斯塔海于格",
  "Seoul Air Base": "首尔空军基地",
  "Sao Lourenco": "圣洛伦索",
  "Santa Teresita": "圣特雷西塔",
  "Mbanza Congo": "姆班扎刚果",
  "Guaruja": "瓜鲁雅",
  "Santa Barbara d": "西圣巴巴拉",
  "St Cloud": "圣克劳德",
  "Stevens Point": "史蒂文斯波因特",
  "St Joseph": "圣约瑟夫",
  "Sterling": "斯特灵",
  "St Paul": "圣保罗",
  "St Marys": "圣玛丽斯",
  "Charlotte Amali": "夏洛特阿马利亚",
  "Surat Airport": "苏拉特机场",
  "Christiansted": "克里斯琴斯特德",
  "Santa Terezinha": "圣特雷西尼亚",
  "Stuart": "斯图尔特",
  "Stroud": "斯特劳德",
  "Sturgeon Bay": "斯特金湾",
  "Surigao City": "苏里高市",
  "Sur": "苏尔",
  "Hailey": "海利",
  "Sunriver": "森里弗",
  "Sumenep-Madura": "苏民纳-马都拉",
  "Sucua": "苏库阿",
  "Summer Beaver": "夏日海狸",
  "St Louis": "圣路易斯",
  "Sumbawanga": "松巴万加",
  "Nausori": "瑙索里",
  "Superior": "苏必利尔",
  "Savoonga": "萨文加",
  "Silver City": "银城",
  "Susanville": "苏珊维尔",
  "Save": "萨韦",
  "Statesville": "斯泰茨维尔",
  "San Vicente Del": "圣维森特-德尔卡瓜",
  "Kuito": "奎托",
  "Sevilla": "塞维利亚",
  "Savuti": "萨武蒂",
  "Sparrevohn": "斯帕雷文",
  "San Antonio Del": "圣安东尼奥-德尔塔奇拉",
  "Stawell Airport": "斯塔威尔机场",
  "Newburgh": "纽堡",
  "Swan Hill Airpo": "斯旺希尔机场",
  "Sahiwal": "萨希瓦尔",
  "Stillwater": "斯蒂尔沃特",
  "Swakopmund": "斯瓦科普蒙德",
  "Sumbawa Island": "松巴哇岛",
  "Swansea": "斯旺西",
  "Strezhevoy": "斯特列热沃伊",
  "Suwon Airport": "水原机场",
  "Sweetwater": "斯威特沃特",
  "Shakawe": "沙卡韦",
  "Sitiawan": "实兆远",
  "RAAF Base East": "澳大利亚皇家空军东部基地",
  "West Sale Airpo": "西塞尔机场",
  "Senanga": "塞南加",
  "Sirri Island Ai": "西里岛机场",
  "Saumlaki-Yamden": "萨温拉基-延德纳岛",
  "Sua Pan Airport": "苏阿潘机场",
  "Sao Felix Do Ar": "圣费利斯-杜阿拉瓜亚",
  "Soldotna": "索尔多特纳",
  "Sahabat": "萨哈巴特",
  "Taman Negara": "国家公园",
  "Salem Airport": "塞勒姆机场",
  "Sao Felix Do Xi": "圣费利斯-杜欣古",
  "Siirt": "锡尔特",
  "Shiringayoc": "希林加约克",
  "Sadah": "萨达",
  "Shelbyville": "谢尔比维尔",
  "Sirjan Airport": "锡尔詹机场",
  "Stykkisholmur": "斯蒂基斯霍尔米",
  "Stanton": "斯坦顿",
  "Saint-Yan": "圣扬",
  "Sue Islet": "苏岛",
  "Sylvester": "西尔维斯特",
  "Sehwan Sharif": "塞赫万谢里夫",
  "Soyo": "索约",
  "Semera": "塞梅拉",
  "Isla de la Juve": "青年岛",
  "Knob Noster": "诺布诺斯特",
  "Sesriem Airstri": "塞斯里姆简易机场",
  "Santa Paula": "圣保拉",
  "Stara Zagora": "旧扎戈拉",
  "Oban": "奥本",
  "San Cristobal D": "圣克里斯托瓦尔-德拉斯卡萨斯",
  "Schwerin Parchi": "什未林-帕尔希姆",
  "Szymany": "什奇特诺",
  "Goleniow": "戈莱纽夫",
  "Scarborough": "斯卡伯勒",
  "Tacloban City": "塔克洛班市",
  "Trinidad": "特立尼达",
  "Tafaraoui Airpo": "塔法拉维机场",
  "Panglao": "邦劳",
  "Tagbilaran City": "塔比拉兰市",
  "Tanna Airport": "坦纳机场",
  "Ta'izz": "塔伊兹",
  "Aitape": "艾塔佩",
  "Tanana": "塔纳纳",
  "Tampico": "坦皮科",
  "Tapachula": "塔帕丘拉",
  "Grottaglie": "格罗塔列",
  "Tashkent": "塔什干",
  "Tauramena": "陶拉梅纳",
  "Tikong-Taliabu": "蒂孔-塔利亚布",
  "Tartu": "塔尔图",
  "Dashoguz": "达沙古兹",
  "Tuy Hoa": "绥和",
  "Tabiteuea North": "北塔比特韦亚",
  "Tabubil": "塔布比尔",
  "Romblon": "朗布隆",
  "Tabarka": "塔巴卡",
  "Timber Creek Ai": "廷伯克里克机场",

  // ...and so on for the rest of the list.
  // The provided list is extremely long, and this pattern should be continued for all entries.