  "Kalkgurung Airp": "卡尔克古龙机场",
  "False Pass": "福尔斯帕斯",
  "Kastamonu": "卡斯塔莫努",
  "Kukes": "库克斯",
  "Kingscote Airpo": "金斯科特机场",
  "Kedougou": "凯杜古",
  "Koliganek": "科利加内克",
  "Kasongo": "卡松戈",
  "Kirovograd": "基洛沃格勒",
  "Kogalym": "科加雷姆",
  "Kos Island": "科斯岛",
  "Keningau": "根地咬",
  "Kingaroy Airpor": "金格罗伊机场",
  "Kerch": "刻赤",
  "Khoram Abad Air": "霍拉马巴德机场",
  "Kauhajoki Airpo": "考哈约基机场",
  "Khark Island Ai": "哈尔克岛机场",
  "Kanti": "坎蒂",
  "Kharkhorin Airp": "哈拉和林机场",
  "Khasab": "海塞卜",
  "Khost": "霍斯特",
  "Khwai River Lod": "奎河小屋",
  "Khoy": "霍伊",
  "King City": "金城",
  "Kristianstad": "克里斯蒂安斯塔德",
  "Kieta": "基埃塔",
  "Kingfisher Lake": "翠鸟湖",
  "Kish Island": "基什岛",
  "Kirkuk": "基尔库克",
  "Wichita Falls": "威奇托福尔斯",
  "Killarney": "基拉尼",
  "Kithira Island": "基西拉岛",
  "Kitwe": "基特韦",
  "Kilwa Masoko": "基卢瓦马索科",
  "Kurnool": "库努尔",
  "Wevelgem": "韦弗尔海姆",
  "Kerama": "庆良间",
  "Kertajati": "科塔贾蒂",
  "Koyuk": "科尤克",
  "Kokoda": "科科达",
  "Kerikeri": "凯里凯里",
  "Kongiganak": "孔吉加纳克",
  "Sa Pran Nak Air": "萨普兰纳克机场",
  "Khok Kathiam Ai": "柯叻机场",
  "Kaikohe Airport": "凯科希机场",
  "Koolburra": "库尔布拉",
  "Kaukura Airport": "考库拉机场",
  "Kashan Airport": "卡尚机场",
  "Kikwit": "基奎特",
  "Kikai Airport": "喜界机场",
  "Kilkenny": "基尔肯尼",
  "Kalabo": "卡拉博",
  "Kaolack": "考拉克",
  "Tver": "特维尔",
  "Kaele": "凯莱",
  "Kalskag": "卡尔斯卡格",
  "Kolhapur Airpor": "戈尔哈布尔机场",
  "Kotakoli Airpor": "科塔科利机场",
  "Kalokol": "卡洛科尔",
  "Kalaleh Airport": "卡拉雷机场",
  "Larsen Bay": "拉森湾",
  "Kalmar Airport": "卡尔马机场",
  "Kelso": "凯尔索",
  "Klagenfurt am W": "克拉根福",
  "Karlovy Vary": "卡罗维发利",
  "Kleinsee": "克莱因西",
  "Kerema": "克雷马",
  "Kamembe": "卡蒙贝",
  "Kuruman": "库鲁曼",
  "Makabana": "马卡巴纳",
  "Kamileroi Airpo": "卡米勒罗伊机场",
  "Manokotak": "马诺科塔克",
  "Keetmanshoop": "基特曼斯胡普",
  "Karimui": "卡里穆伊",
  "Kisimayu Airpor": "基斯马尤机场",
  "Kalemyo": "格礼谬",
  "Kostroma": "科斯特罗马",
  "Dyagilevo Air B": "佳吉列沃空军基地",
  "Kaoma": "考马",
  "Vina Del Mar": "比尼亚德尔马",
  "Kanab": "卡纳布",
  "Kindu": "金杜",
  "Shang-I": "尚义",
  "Kindamba": "金丹巴",
  "Kokhanok": "科哈诺克",
  "Kaniama": "卡尼亚马",
  "Kankan": "康康",
  "Kangan": "坎甘",
  "King Island Air": "金岛机场",
  "Kennett": "肯尼特",
  "Kanpur": "坎普尔",
  "Kanpur Airport": "坎普尔机场",
  "New Stuyahok": "新斯图亚霍克",
  "Kununurra": "库努纳拉",
  "Kenieba": "凯涅巴",
  "Kupang-Timor Is": "古邦-帝汶岛",
  "Komatipoort": "科马提普特",
  "Orkney Islands": "奥克尼群岛",
  "Nakhon Phanom A": "那空拍侬机场",
  "Kothen": "克滕",
  "Sihanukville": "西哈努克城",
  "Kotlik": "科特利克",
  "Koulamoutou": "库拉穆图",
  "Kokshetau": "科克舍套",
  "Port Clarence": "克拉伦斯港",
  "Kapit": "加帛",
  "Kompiam Airport": "科姆皮安机场",
  "Kipnuk": "基普努克",
  "Pohang": "浦项",
  "Kempsey Airport": "肯普西机场",
  "Keperveem": "克佩尔韦姆",
  "Kishangarh": "基申格尔",
  "Kurgan-Tyube": "库尔干秋别",
  "Kerang Airport": "克朗机场",
  "Karumba Airport": "卡伦巴机场",
  "Kirundo": "基龙多",
  "Karasabai": "卡拉萨拜",
  "Redhill": "雷德希尔",
  "Kikori": "基科里",
  "Karawari Airstr": "卡拉瓦里简易机场",
  "Krakow": "克拉科夫",
  "Karanambo": "卡拉南博",
  "Kiruna Airport": "基律纳机场",
  "Kurgan": "库尔干",
  "Kramatorsk": "克拉马托尔斯克",
  "Krasnodar": "克拉斯诺达尔",
  "Kjevik": "克耶维克",
  "Okat": "奥卡特",
  "Kasese": "卡塞塞",
  "Kissidougou": "基西杜古",
  "Kasos Island": "卡索斯岛",
  "Karlskoga Airpo": "卡尔斯库加机场",
  "Kassala": "卡萨拉",
  "St Mary's": "圣玛丽",
  "Kostanay": "库斯塔奈",
  "Khanabad": "哈纳巴德",
  "Sikasso": "锡卡索",
  "Kosti": "科斯蒂",
  "Kvernberget": "克文贝格特",
  "Kiryat Shmona": "谢莫纳城",
  "Kotlas": "科特拉斯",
  "Kitadaito Airpo": "北大东机场",
  "Kerteh": "克帖",
  "Takaka Airport": "塔卡卡机场",
  "Kitale": "基塔莱",
  "Kato": "卡托",
  "Tinson Pen": "廷森彭",
  "Kitee Airport": "基泰机场",
  "Brevig Mission": "布雷维格米申",
  "Kota Airport": "哥打机场",
  "Koutiala": "库佳拉",
  "Kalutara": "卡卢特勒",
  "Kuantan": "关丹",
  "Kudat": "古达",
  "Kubin Airport": "库宾机场",
  "Kasigluk": "卡西格卢克",
  "Yakushima Airpo": "屋久岛机场",
  "Kuri": "库里",
  "Kulusuk": "库卢苏克",
  "Kullu Manali Ai": "库鲁马纳里机场",
  "Kunsan": "群山",
  "Skovde": "舍夫德",
  "King Cove": "金科夫",
  "Kavieng": "卡维恩",
  "Apatity": "阿帕季特",
  "Kivalina": "基瓦利纳",
  "Kwajalein": "夸贾林",
  "Kryvyi Rih": "克里沃罗格",
  "Khwahan": "赫瓦汉",
  "Kwigillingok": "奎吉林戈克",
  "Kowanyama": "科瓦尼亚马",
  "Quinhagak": "昆哈加克",
  "Kawito": "卡维托",
  "Kwethluk": "克韦斯卢克",
  "Kolwezi Airport": "科卢韦齐机场",
  "Kolaka": "科拉卡",
  "Kondinskoye": "孔金斯科耶",
  "Klerksdorp": "克勒克斯多普",
  "Koro Island": "科罗岛",
  "Komsomolsk-on-A": "阿穆尔河畔共青城",
  "Katiu": "卡蒂乌",
  "Orchid Island": "兰屿",
  "Tripoli": "的黎波里",
  "Karluk": "卡尔卢克",
  "Kyaukpyu": "皎漂",
  "Kayes Dag Dag A": "卡伊达格达格机场",
  "Kyauktu": "觉图",
  "Koyukuk": "科尤库克",
  "Kyzyl": "克孜勒",
  "Kampong Chhnang": "磅清扬",
  "Kaintiba": "凯恩蒂巴",
  "Kitzingen Army": "基青根陆军机场",
  "Kozani": "科扎尼",
  "Kzyl-Orda": "克孜勒奥尔达",
  "Altintas": "阿尔滕塔什",
  "Kastelorizo Isl": "卡斯泰洛里佐岛",
  "Nadzab": "纳扎布",
  "Labuha-Halmaher": "拉布哈-哈马黑拉岛",
  "Aklavik": "阿克拉维克",
  "Lakeland": "莱克兰",
  "Los Alamos": "洛斯阿拉莫斯",
  "Ladysmith": "拉迪史密斯",
  "Bom Jesus Da La": "邦雅苏斯-达拉帕",
  "North Platte": "北普拉特",
  "Labuan Bajo-Flo": "纳闽巴霍-弗洛勒斯岛",
  "Lusambo": "卢桑博",
  "Lambarene": "兰巴雷内",
  "Labrea": "拉布雷亚",
  "Labasa Airport": "兰巴萨机场",
  "Lumberton": "兰伯顿",
  "Long Bawan-Born": "龙巴万-婆罗洲",
  "Lubang Airport": "卢邦机场",
  "La Baule-Escoub": "拉波勒-埃斯库布拉克",
  "Lucapa": "卢卡帕",
  "Larnarca": "拉纳卡",
  "Lecce Airport": "莱切机场",
  "Louis Trichardt": "路易特里哈特",
  "Rio Dulce": "杜尔塞河",
  "Culleredo": "库列雷多",
  "Laconia": "拉科尼亚",
  "Lodz": "罗兹",
  "Pinar del Rio": "比那尔德里奥",
  "La Cumbre": "拉昆布雷",
  "Balcanoona Airp": "巴尔卡努纳机场",
  "Lague": "拉格",
  "Lake City": "莱克城",
  "Lucca": "卢卡",
  "Malda": "马尔达",
  "Londrina": "隆德里纳",
  "Leshukonskoye": "列舒孔斯科耶",
  "Lord Howe Islan": "豪勋爵岛",
  "Lindi": "林迪",
  "Linden": "林登",
  "Lidkoping": "利德雪平",
  "Ludington": "拉丁顿",
  "Lamidanda": "拉米丹达",
  "Aurora": "奥罗拉",
  "Lahad Datu": "拿笃",
  "Landivisiau": "朗迪维肖",
  "Saint-Laurent-d": "圣洛朗-迪马罗尼",
  "Derry": "德里",
  "Londolozi": "隆多洛济",
  "Exmouth": "埃克斯茅斯",
  "Lencois": "伦索伊斯",
  "Leesburg": "利斯堡",
  "Lebakeng": "莱巴肯",
  "Labe Airport": "拉贝机场",
  "Lake Evella Air": "埃维拉湖机场",
  "Lemmon": "莱蒙",
  "Leopoldina": "莱奥波尔迪纳",
  "Land's End": "兰兹角",
  "Leinster Airpor": "伦斯特机场",
  "Lesobeng": "莱索벵",
  "Bureta": "布雷塔",
  "Lelystad": "莱利斯塔德",
  "La Esperanza": "拉埃斯佩兰萨",
  "Lumbo": "伦博",
  "Lufkin": "拉夫金",
  "Lamerd": "拉梅尔德",
  "Louisburg": "刘易斯堡",
  "La Fria": "拉弗里亚",
  "New York": "纽约",
  "Lagrange": "拉格朗日",
  "Yuma Proving Gr": "尤马试验场",
  "Leigh Creek Air": "利溪机场",
  "Deadman's Cay": "死人礁",
  "Long Datih": "龙达蒂",
  "Langeoog": "朗格奥格岛",
  "Legazpi City": "黎牙实比市",
  "Cochrane": "科克伦",
  "Malargue": "马拉圭",
  "Logan": "洛根",
  "Lahr Airport": "拉尔机场",
  "Lightning Ridge": "闪电岭",
  "Lereh-Papua Isl": "莱雷-巴布亚岛",
  "Las Heras": "拉斯埃拉斯",
  "Lock Haven": "洛克哈芬",
  "Limon": "利蒙",
  "Libenge": "利本盖",
  "Lifou": "利富岛",
  "Mulia-Papua Isl": "穆利亚-巴布亚岛",
  "Puerto Limon": "利蒙港",
  "Lins": "林斯",
  "Lisala": "利萨拉",
  "Liberia": "利比里亚",
  "Likoma Island": "利科马岛",
  "Lodja": "洛贾",
  "Larantuka-Flore": "拉兰图卡-弗洛勒斯岛",
  "Lakeba Island": "莱坎巴岛",
  "Lokichoggio": "洛基乔基奥",
  "Long Akah": "长阿卡",
  "Kulik Lake": "库利克湖",
  "Lake Placid": "普莱西德湖",
  "Lakeview": "莱克维尤",
  "Lekhwair Airpor": "莱克怀尔机场",
  "Lake Manyara Na": "马尼亚拉湖国家公园",
  "Lakenheath": "莱肯希思",
  "Malelane": "马莱拉内",
  "Chillagoe Airpo": "奇拉戈机场",
  "Lalmonirhat": "拉尔莫尼尔哈德",
  "Lankaran": "连科兰",
  "Las Lomitas": "拉斯洛米塔斯",
  "Lobito": "洛比托",
  "Lyndonville": "林登维尔",
  "Mount Holly": "霍利山",
  "Minchumina": "明丘米纳",
  "Salima": "萨利马",
  "Lumi": "卢米",
  "Lossiemouth": "洛西茅斯",
  "Lime Acres": "莱姆阿克雷斯",
  "Naifaru": "奈法鲁",
  "Lake Murray": "默里湖",
  "Lamen Bay": "拉门湾",
  "Lonorore": "洛诺罗雷",
  "Lonely": "朗利",
  "Willoughby": "威洛比",
  "Wise": "怀斯",
  "Lone Rock": "孤岩",
  "Londolovit": "隆多洛维特",
  "Smolensk": "斯摩棱斯克",
  "Lanai City": "拉奈市",
  "Lorraine Airpor": "洛林机场",
  "Los Andes": "洛斯安第斯",
  "Lock": "洛克",
  "Longana": "隆加纳",
  "Loei Airport": "黎机场",
  "Lontras": "隆特拉斯",
  "Lodwar": "洛德瓦尔",
  "Lovelock": "洛夫洛克",
  "Laghouat": "拉格瓦特",
  "Monclova Intern": "蒙克洛瓦国际机场",
  "Louisa": "路易莎",
  "Loyengalani": "洛延加拉尼",
  "Gran Canaria Is": "大加那利岛",
  "Lompoc": "隆波克",
  "La Pedrera": "拉佩德雷拉",
  "La Plata": "拉普拉塔",
  "Guayabal": "瓜亚瓦尔",
  "Lipetsk": "利佩茨克",
  "Lamap": "拉马普",
  "La Porte": "拉波特",
  "Lampang Airport": "南邦机场",
  "Long Apung-Born": "龙阿邦-婆罗洲",
  "Liepaja": "利耶帕亚",
  "Pickens": "皮肯斯",
  "Puerto Leguizam": "莱吉萨莫港",
  "Qala-I-Naw": "瑙堡",
  "Larisa": "拉里萨",
  "Leribe": "莱里贝",
  "Loralai": "洛拉莱",
  "Le Mars": "勒马尔斯",
  "Niamtougou": "尼亚姆图古",
  "Lar": "拉尔",
  "Leros Island": "莱罗斯岛",
  "Los Roques": "洛斯罗克斯群岛",
  "Losuia": "洛苏亚",
  "Lordsburg": "洛兹堡",
  "La Serena-Coqui": "拉塞雷纳-科金博",
  "Lerwick": "勒威克",
  "Lusk": "勒斯克",
  "Los Chiles": "洛斯奇莱斯",
  "Long Semado": "长塞马多",
  "Los Banos": "洛斯巴诺斯",
  "Les Sables-d'Ol": "莱萨布勒多洛讷",
  "Paraguana": "巴拉瓜纳",
  "Les Saintes": "桑特群岛",
  "Long Sukang": "长苏康",
  "Lhok Seumawe-Su": "司马威-苏门答腊",
  "Lhok Sukon-Suma": "司马功-苏门答腊",
  "Losinj": "洛希尼",
  "Tzaneen": "察嫩",
  "Lai": "莱城",
  "Langtang": "朗塘",
  "Altai": "阿尔泰",
  "Latakia": "拉塔基亚",
  "Lastourville": "拉斯图尔维尔",
  "Lethem": "莱瑟姆",
  "Loreto": "洛雷托",
  "Le Touquet-Pari": "勒图凯-巴黎",
  "Letterkenny": "莱特肯尼",
  "Altus": "阿尔特斯",
  "La Mole": "拉莫尔",
  "Latur": "拉图尔",
  "Lumid Pau": "卢米德保",
  "Laucala Island": "劳萨拉岛",
  "Glendale": "格伦代尔",
  "Ludhiana Airpor": "卢迪亚纳机场",
  "Lusikisiki": "卢西基西基",
  "Luxi": "潞西",
  "Luena": "卢埃纳",
  "Kalaupapa": "卡劳帕帕",
  "Cape Lisburne": "利斯本角",
  "Langgur-Seram I": "朗古尔-斯兰岛",
  "Luwok-Celebes I": "卢武克-西里伯斯岛",
  "Livramento Do B": "利夫拉门图-杜布鲁马杜",
  "Itirapina": "伊蒂拉皮纳",
  "Livermore": "利弗莫尔",
  "Lawrenceville": "劳伦斯维尔",
  "Livingston": "利文斯顿",
  "Laverton Airpor": "拉弗顿机场",
  "Lavan Island Ai": "拉万岛机场",
  "Lucas do Rio Ve": "南卢卡斯",
  "Lewisburg": "刘易斯堡",
  "Lawrence": "劳伦斯",
  "Lawn Hill Airpo": "劳恩希尔机场",
  "Wells": "韦尔斯",
  "Gyumri": "久姆里",
  "Leeuwarden": "吕伐登",
  "Lawas": "老越",
  "Luang Namtha": "琅南塔",
  "Limnos Island": "利姆诺斯岛",
  "Lukulu": "卢库卢",
  "Lycksele Airpor": "吕克瑟勒机场",
  "Lyneham": "莱纳姆",
  "Lyons": "里昂",
  "Lydd": "利德",
  "Lazaro Cardenas": "拉萨罗卡德纳斯",
  "Langzhong": "阆中",
  "Luozi": "罗齐",
  "Luzamba": "卢赞巴",
  "Nangang Island": "南竿岛",
  "Lizard Island A": "蜥蜴岛机场",
  "Madera": "马德拉",
  "Menorca Island": "梅诺卡岛",
  "Mangochi": "曼戈切",
  "Mangole Island": "曼戈莱岛",
  "Mae Sot Airport": "湄索机场",
  "Momote Airport": "莫莫特机场",
  "Matadi": "马塔迪",
  "Maupiti Airport": "莫皮蒂机场",
  "Malden": "莫尔登",
  "Matam": "马塔姆",
  "Mangrove Cay": "红树林礁",
  "Marble Bar Airp": "马布尔巴机场",
  "M'Bigou": "姆比古",
  "Mafeking": "马弗京",
  "Monbetsu": "纹别",
  "Porepunkah Airp": "波雷蓬卡机场",
  "Mobridge": "莫布里奇",
  "Maryborough Air": "马里伯勒机场",
  "Mbeya": "姆贝亚",
  "Matupa": "马图帕",
  "Manistee": "马尼斯蒂",
  "Mamburao Airpor": "曼布劳机场",
  "Moyobamba": "莫约班巴",
  "Mbarara": "姆巴拉拉",
  "Maribor": "马里博尔",
  "Moberly": "莫伯利",
  "Maues": "毛埃斯",
  "Macenta": "马森塔",
  "Mc Comb": "麦库姆",
  "Mackinac Island": "麦基诺岛",
  "Tampa": "坦帕",
  "McGrath": "麦格拉思",
  "Machala": "马查拉",
  "La Mina-Maicao": "拉米纳-迈考",
  "Mc Cook": "麦库克",
  "Mckinley Park": "麦金利公园",
  "Miskolc": "米什科尔茨",
  "Melchor de Menc": "梅尔乔-德门科斯",
  "Monte Caseros": "蒙特卡塞罗斯",
  "McArthur River": "麦克阿瑟河",
  "Mason City": "梅森城",
  "Maroochydore": "马卢奇郡",
  "Rionegro": "里奥内格罗",
  "Makurdi": "马库尔迪",
  "Middleton Islan": "米德尔顿岛",
  "Maldonado": "马尔多纳多",
  "Mindiptana-Papu": "明迪普塔纳-巴布亚",
  "Mendi Airport": "门迪机场",
  "Mercedes": "梅赛德斯",
  "Macae": "马卡埃",
  "Melbourne Essen": "墨尔本埃森登",
  "Malanje": "马兰热",
  "Mehamn": "梅港",
  "Meadville": "米德维尔",
  "Meknes": "梅克内斯",
  "Manteo": "曼蒂奥",
  "Mersing": "丰盛港",
  "Peureumeue-Suma": "珀勒默-苏门答腊",
  "Minden": "明登",
  "Meghauli": "梅高利",
  "Musina": "穆西纳",
  "Silveroaks": "银橡树",
  "Mafia Island": "马菲亚岛",
  "Mafeteng": "马费滕",
  "Mansfield": "曼斯菲尔德",
  "Mc Allen": "麦卡伦",
  "Moanda": "姆旺达",
  "Muzaffarabad": "穆扎法拉巴德",
  "Marshfield": "马什菲尔德",
  "Moala": "莫阿拉",
  "Beigan Island": "北竿岛",
  "Milford Sound A": "米尔福德峡湾机场",
  "Manguna": "曼古纳",
  "Miraflores": "米拉弗洛雷斯",
  "Mfuwe": "姆富韦",
  "Melfa": "梅尔法",
  "Mount Gambier A": "甘比尔山机场",
  "Michigan City": "密歇根城",
  "Magdalena": "马格达莱纳",
  "Marietta": "玛丽埃塔",
  "Maringa": "马林加",
  "Mong Tong": "孟通",
  "Monchengladbach": "门兴格拉德巴赫",
  "Magangue": "马甘格",
  "Moultrie": "莫尔特里",
  "Milingimbi Isla": "米林金比岛",
  "Manaung": "马瑙恩",
  "Margaret River": "玛格丽特河",
  "Moabi": "莫阿比",
  "Mkeik": "墨吉",
  "Mahdia": "马赫迪耶",
  "Dalcahue": "达尔卡韦",
  "Mitchell": "米切尔",
  "Mannheim": "曼海姆",
  "Manhattan": "曼哈顿",
  "Marshall": "马歇尔",
  "Mount House Air": "芒特豪斯机场",
  "Mariehamn Airpo": "玛丽港机场",
  "Dunsmuir": "邓斯缪尔",
  "Mount Hotham": "霍瑟姆山",
  "Mojave": "莫哈韦",
  "El Banado": "巴尼亚多",
  "Mildenhall": "米尔登霍尔",
  "Muncie": "曼西",
  "Mili Island": "米利岛",
  "Minnipa Airport": "明尼帕机场",
  "Mitzpe Ramon": "米茨佩拉蒙",
  "Beersheba": "贝尔谢巴",
  "Shafter": "沙夫特",
  "Maiduguri": "迈杜古里",
  "Millville": "米尔维尔",
  "Marshalltown": "马歇尔敦",
  "Man Airport": "芒机场",
  "Mosjoen Airport": "莫舍恩机场",
  "Mayajigua": "马亚希瓜",
  "Monkey Mia": "猴子米亚",
  "Mouila": "穆伊拉",
  "Mbuji Mayi": "姆布吉马伊",
  "Mount Etjo Airp": "埃乔山机场",
  "Manjimup Airpor": "曼吉马普机场",
  "Miramar": "米拉马尔",
  "Mamuju-Celebes": "马穆朱-西里伯斯",
  "San Javier": "圣哈维尔",
  "Toms River": "汤姆斯河",
  "Marianske Lazne": "玛丽安温泉市",
  "Mekambo": "梅坎博",
  "Mokhotlong": "莫霍特隆",
  "Mboki": "姆博基",
  "Makoua": "马库阿",
  "Kaunakakai": "考纳卡卡伊",
  "Muskogee": "马斯科吉",
  "Makemo Airport": "马克莫机场",
  "Merauke-Papua I": "马老奇-巴布亚岛",
  "Meekatharra Air": "米卡萨拉机场",
  "Mankato": "曼凯托",
  "Makokou": "马科库",
  "Manokwari-Papua": "马诺夸里-巴布亚",
  "Luqa": "卢加",
  "Mc Alester": "麦卡莱斯特",
  "Malad City": "马拉德城",
  "Milford": "米尔福德",
  "Malang-Java Isl": "玛琅-爪哇岛",
  "Milledgeville": "米利奇维尔",
  "Melilla Island": "梅利利亚岛",
  "Milos Island": "米洛斯岛",
  "Malabang": "马拉邦",
  "Millicent Airpo": "米利森特机场",
  "Millinocket": "米利诺基特",
  "Manley Hot Spri": "曼利温泉",
  "Melo": "梅洛",
  "Ciudad Mante": "曼特城",
  "Minami Daito Ai": "南大东机场",
  "Durham": "达勒姆",
  "Mamfe": "曼菲",
  "Mount Magnet Ai": "芒特马格内特机场",
  "Mammoth Lakes": "马默斯湖",
  "Middlemount Air": "米德尔芒特机场",
  "Stow": "斯托",
  "Vila do Maio": "马约镇",
  "Mompos": "蒙波斯",
  "Mbala": "姆巴拉",
  "Marks": "马克斯",
  "Eastover": "伊斯特奥弗",
  "Morristown": "莫里斯敦",
  "Miyako City": "宫古市",
  "Maimana Airport": "迈马纳机场",
  "Karakelong Isla": "卡拉克隆岛",
  "Muanda Airport": "穆安达机场",
  "Nacala": "纳卡拉",
  "Maningrida": "马宁里达",
  "Al Muladdah": "穆拉达",
  "Polonnaruwa Tow": "波隆纳鲁沃镇",
  "Gerald's Park": "杰拉尔德公园",
  "Maiana": "迈亚纳",
  "Menominee": "梅诺米尼",
  "Marion": "马里昂",
  "Manono": "马诺诺",
  "Monto Airport": "蒙托机场",
  "Mongu": "蒙固",
  "Mansa": "曼萨",
  "Mawlamyine": "毛淡棉",
  "Manicore": "马尼科雷",
  "Manassas": "马纳萨斯",
  "Moa": "莫阿",
  "Modesto": "莫德斯托",
  "Momeik Airport": "孟密机场",
  "Maumere-Flores": "毛梅雷-弗洛勒斯岛",
  "Mong Hsat": "孟萨",
  "Moengo": "姆恩戈",
  "Muynak": "穆伊纳克",
  "Aro": "阿罗",
  "Moudjeria": "穆杰里亚",
  "Mount Cook Airp": "库克山机场",
  "Moomba Airport": "蒙巴机场",
  "Morondava Airpo": "穆龙达瓦机场",
  "Mountain Villag": "山村",
  "Morris": "莫里斯",
  "Moorea Airport": "莫雷阿机场",
  "Mpacha": "姆帕查",
  "Sindhri": "信德里",
  "Malay": "马来",
  "Morrilton": "莫里尔顿",
  "Mc Pherson": "麦克弗森",
  "Mariupol": "马里乌波尔",
  "Maripasoula": "马里帕苏拉",
  "Macomb": "马科姆",
  "Miquelon": "密克隆岛",
  "Maquinchao": "马金乔",
  "Minacu": "米纳苏",
  "Honuu": "霍努乌",
  "San Matias": "圣马蒂亚斯",
  "Mpumalanga": "普马兰加",
  "Moundou Airport": "蒙杜机场",
  "Mustique Island": "马斯蒂克岛",
  "Mariquita": "马里基塔",
  "Mc Rae": "麦克雷",
  "Mekele Airport": "默克莱机场",
  "Smyrna": "士麦那",
  "Masai Mara": "马赛马拉",
  "Marfa": "马尔法",
  "Mareeba Airport": "马里巴机场",
  "Marham": "马勒姆",
  "Marco Island": "马可岛",
  "Morganton": "摩根顿",
  "Masterton": "马斯特顿",
  "Marla Airport": "马拉机场",
  "Gasan": "加桑",
  "Macara": "马卡拉",
  "Mineralnyye Vod": "矿水城",
  "Lolland Falster": "洛兰-法尔斯特",
  "Mahshahr Airpor": "马赫夏赫尔机场",
  "Muskrat Dam": "马斯科拉特坝",
  "Mesa": "梅萨",
  "Manston": "曼斯顿",
  "Matsaile": "马察莱",
  "Masirah": "马西拉",
  "Morro Agudo": "莫鲁阿古杜",
  "Massena": "马塞纳",
  "Monticello": "蒙蒂塞洛",
  "Massawa": "马萨瓦",
  "Mossendjo": "莫松乔",
  "New Orleans": "新奥尔良",
  "Namibe": "纳米贝",
  "Matamata Glider": "马塔马塔滑翔机机场",
  "Montelibano": "蒙特利瓦诺",
  "Mount Clemens": "克莱门斯山",
  "Mount Sanford S": "桑福德山",
  "Monte Alegre": "蒙蒂阿莱格里",
  "Vila Bela Da Sa": "圣三一贝拉镇",
  "Vila do Mosteir": "莫斯泰罗什镇",
  "Maitland Airpor": "梅特兰机场",
  "Montauk": "蒙托克",
  "Mitchell Airpor": "米切尔机场",
  "Manitowoc": "马尼托瓦克",
  "Murateweh-Borne": "穆拉特维-婆罗洲",
  "Monterrey": "蒙特雷",
  "Masada": "马萨达",
  "Mueda": "穆埃达",
  "Mulege": "穆莱赫",
  "Fort Indiantown": "印第安敦堡",
  "Maturin": "马图林",
  "Mountain Home": "芒廷霍姆",
  "Muccan Station": "穆坎站",
  "Marudi": "马鲁帝",
  "Minami Torishim": "南鸟岛",
  "Muscatine": "马斯卡廷",
  "Ghriss Airport": "格里斯机场",
  "Mouyondzi": "穆永济",
  "Musoma": "穆索马",
  "Myvatn": "米湖",
  "Franceville": "弗朗斯维尔",
  "Monroeville": "门罗维尔",
  "Mossoro": "莫索罗",
  "Morrisville": "莫里斯维尔",
  "Mount Vernon": "芒特弗农",
  "Mongo": "蒙戈",
  "Mitu": "米图",
  "Mogilev": "莫吉廖夫",
  "Mucuri": "穆库里",
  "Verdun": "凡尔登",
  "Minvoul": "明武尔",
  "Martha's Vineya": "玛莎葡萄园",
  "Masvingo": "马斯温戈",
  "Morawa Airport": "莫拉瓦机场",
  "Mianwali": "米扬瓦利",
  "Merowe": "麦洛维",
  "Matthews Ridge": "马修斯里奇",
  "Matak Island": "马塔克岛",
  "Mineral Wells": "米纳勒尔韦尔斯",
  "Windom": "温德姆",
  "Mwadui": "姆瓦杜伊",
  "Middletown": "米德尔敦",
  "Magway": "马圭",
  "Masamba-Celebes": "马桑巴-西里伯斯",
  "Maxton": "马克顿",
  "Moro": "莫罗",
  "Mati National A": "马蒂国家机场",
  "Minna": "明纳",
  "Mindik": "明迪克",
  "Morombe Airport": "穆龙贝机场",
  "Mullewa Airport": "穆勒瓦机场",
  "Moron": "莫龙",
  "Mora Airport": "莫拉机场",
  "Mccarthy": "麦卡锡",
  "Mayumba": "马永巴",
  "Maracay": "马拉开",
  "Miyakejima": "三宅岛",
  "Mayaguana": "马亚瓜纳",
  "Mc Call": "麦考尔",
  "Monkey Mountain": "猴山",
  "Mareb": "马雷布",
  "Mysore": "迈索尔",
  "Mekoryuk": "梅科留克",
  "Marysville": "马里斯维尔",
  "Mtwara": "姆特瓦拉",
  "Menyamya": "门亚米亚",
  "Monkey Bay": "猴子湾",
  "Mazamari": "马萨马里",
  "Mocimboa da Pra": "普拉亚的莫辛布瓦",
  "Mitzic": "米齐克",
  "Makung City": "马公市",
  "Amasya": "阿马西亚",
  "Ambodedjo Airpo": "安博德霍机场",
  "Marakei": "马拉凯",
  "Motueka Airport": "莫图伊卡机场",
  "Mkuze": "姆库泽",
  "Mazar I Sharif": "马扎里沙里夫",
  "Muzaffarpur Air": "穆扎法尔普尔机场",
  "Mulu": "姆鲁",
  "Mecheria": "梅谢里亚",
  "Masslo": "马斯洛",
  "Mossel Bay": "莫塞尔贝",
  "Narrabri": "纳拉布赖",
  "Naracoorte Airp": "纳拉库特机场",
  "Naqpur": "那格浦尔",
  "Tahuna-Sangihe": "塔胡纳-桑义赫",
  "Annai": "安奈",
  "Nakhchivan": "纳希切万",
  "Nakhon Ratchasi": "呵叻",
  "Namlea-Buru Isl": "南里-布鲁岛",
  "Napoli": "那不勒斯",
  "Armenia": "亚美尼亚",
  "Nassau": "拿骚",
  "Natal": "纳塔尔",
  "Napuka Island": "纳普卡岛",
  "Nevsehir": "内夫谢希尔",
  "Narathiwat Airp": "那拉提瓦机场",
  "Nizhnekamsk": "下卡姆斯克",
  "Enfidha": "恩菲达",
  "Wannukandi": "万努坎迪",
  "Guantanamo Bay": "关塔那摩湾",
  "Nabire-Papua Is": "纳比雷-巴布亚岛",
  "Nice": "尼斯",
  "Nuevo Casas Gra": "新卡萨斯格兰德斯",
  "Nachingwea": "纳钦圭阿",
  "Necocli": "内科克利",
  "Sunchales": "孙查莱斯",
  "Chenega": "切内加",
  "North Kingstown": "北金斯敦",
  "San Carlos": "圣卡洛斯",
  "Nukus": "努库斯",
  "Banda Island": "班达岛",
  "Nouadhibou": "努瓦迪布",
  "Nanded": "南德",
  "Sumbe": "松贝",
  "Mandera": "曼德拉",
  "N'Djamena": "恩贾梅纳",
  "N'Dele": "恩代莱",
  "Sanday": "桑迪岛",
  "Nordholz Airpor": "诺德霍尔茨机场",
  "Necochea": "内科切阿",
  "Neftekamsk": "涅夫捷卡姆斯克",
  "Negril": "尼格瑞尔",
  "Lakehurst": "莱克赫斯特",
  "Sam Neua Airpor": "桑怒机场",
  "Charlestown": "查尔斯敦",
  "Nefteyugansk": "涅夫捷尤甘斯克",
  "Young Airport": "杨机场",
  "N'Gaoundere": "恩冈代雷",
  "Kaneohe": "卡内奥赫",
  "Ngau": "高岛",
  "Ngala": "恩加拉",
  "Norfolk": "诺福克",
  "Ngawal": "恩加瓦尔",
  "New Halfa": "新哈勒法",
  "Patuxent River": "帕塔克森特河",
  "Nushki": "努什基",
  "Nuku Hiva Airpo": "努库希瓦机场",
  "Foley": "福利",
  "Nimba": "宁巴",
  "Nikolai": "尼古拉",
  "Camp Nifty Airp": "尼夫蒂营机场",
  "Nikunau": "尼库瑙",
  "Niamey": "尼亚美",
  "Simberi Island": "辛贝里岛",
  "Angaha": "安加哈",
  "Nioro du Sahel": "萨赫勒地区尼奥罗",
  "Atsugi Naval Ai": "厚木海军航空基地",
  "Nizhnevartovsk": "下瓦尔托夫斯克",
  "Najaf": "纳杰夫",
  "El Centro": "埃尔森特罗",
  "Nouakchott": "努瓦克肖特",
  "Nkolo Fuma": "恩科洛富马",
  "Nkongsamba": "恩孔桑巴",
  "Nkaus": "恩考斯",
  "Nkayi": "恩卡伊",
  "Ndola": "恩多拉",
  "Lemoore": "勒穆尔",
  "Nuevo Laredo": "新拉雷多",
  "Nelson Lagoon": "纳尔逊泻湖",
  "Nullagine Airpo": "纳拉金机场",
  "Ndolo Airport": "恩多洛机场",
  "Nelspruit": "内尔斯普雷特",
  "Nikolayev": "尼古拉耶夫",
  "Namangan": "纳曼干",
  "Daman Airport": "达曼机场",
  "Normans Cay Air": "诺曼礁机场",
  "Nightmute": "奈特缪特",
  "Maafaru": "马法鲁",
  "Nappa Merrie Ai": "纳帕梅里机场",
  "Namsang": "南桑",
  "Nondalton": "农达尔顿",
  "Naryan Mar": "纳里扬马尔",
  "Inverin": "因弗林",
  "Nan Airport": "难府机场",
  "Nanuque": "纳努克",
  "Nunukan-Nunukan": "努努坎-努努坎",
  "Nowra Airport": "诺拉机场",
  "Nicoya": "尼科亚",
  "Norddeich": "诺德代希",
  "Nogales Interna": "诺加莱斯国际机场",
  "Noyabrsk": "诺亚布里斯克",
  "Nova Xavantina": "新沙万蒂纳",
  "Nonouti": "诺努蒂",
  "Sinop": "锡诺普",
  "Nordfjordur": "诺德峡湾",
  "Nosy Be": "诺西贝",
  "Novato": "诺瓦托",
  "Huambo": "万博",
  "Novokuznetsk": "新库兹涅茨克",
  "Napier Airport": "内皮尔机场",
  "New Plymouth": "新普利茅斯",
  "Nanga Pinoh-Bor": "南加皮诺-婆罗洲",
  "Novo Progresso": "新普罗格雷索",
  "Millington": "米灵顿",
  "Kingsville": "金斯维尔",
  "Niquelandia": "尼克兰迪亚",
  "Neuquen": "内乌肯",
  "Nuqui": "努基",
  "Newquay": "纽基",
  "Narrandera": "纳兰德拉",
  "Mayport": "梅波特",
  "Norderney": "诺德奈",
  "Namrole-Buru Is": "南罗莱-布鲁岛",
  "Narrogin Airpor": "纳罗金机场",
  "Norrkoping": "北雪平",
  "North Ronaldsay": "北罗纳德赛",
  "Nara": "奈良",
  "Weeze": "韦策",
  "Ceiba": "塞瓦",
  "Imperial Beach": "因皮里尔比奇",
  "Milton": "米尔顿",
  "Noshahr Airport": "诺沙赫尔机场",
  "Slayton": "斯莱顿",
  "Norseman Airpor": "诺斯曼机场",
  "Nelson": "纳尔逊",
  "Scone Airport": "斯昆机场",
  "Cavite City":