const airportNames = {
  "Bemichi": "贝米奇",
  "Baucau": "包考",
  "Barcaldine": "巴卡尔丁",
  "Pococi": "波科西",
  "Bacau": "巴克乌",
  "Boca Do Acre": "阿克里河口",
  "Bartow": "巴托",
  "Borroloola Airp": "博罗卢拉机场",
  "Bozoum": "博祖姆",
  "Bamenda": "巴门达",
  "Batuna Mission": "巴图纳米申",
  "Barra Do Garcas": "巴拉杜加萨斯",
  "Bislig Airport": "比斯利格机场",
  "Big Piney": "大派尼",
  "Balikpapan-Born": "巴厘巴板-婆罗洲",
  "Borongan City": "博龙岸市",
  "Porto Seguro": "塞古罗港",
  "Besalampy Airpo": "贝萨兰皮机场",
  "Baler": "巴莱尔",
  "Busselton": "巴瑟尔顿",
  "Budardalur": "布达达鲁尔",
  "Boulia Airport": "布利亚机场",
  "Bequia": "贝基亚岛",
  "Balgo Hill Airp": "巴尔戈山机场",
  "Barreiras": "巴雷拉斯",
  "Barreirinhas Ai": "巴雷里尼亚斯机场",
  "San Carlos de B": "圣卡洛斯-德巴里洛切",
  "Bourke Airport": "伯克机场",
  "Barquisimeto": "巴基西梅托",
  "Bern": "伯尔尼",
  "Eoligarry": "埃奥利加里",
  "Bathurst Island": "巴瑟斯特岛",
  "Bremerhaven": "不来梅哈芬",
  "Barahona": "巴拉奥纳",
  "Bardstown": "巴兹敦",
  "Bosaso": "博萨索",
  "Bahia Solano": "索拉诺湾",
  "Sematan": "实马丹",
  "Camp Pohakuloa": "波哈库洛亚营地",
  "Bata Airport": "巴塔机场",
  "Bairnsdale Airp": "贝恩斯代尔机场",
  "Biskra": "比斯克拉",
  "Amol": "阿莫勒",
  "Bossangoa": "博桑戈阿",
  "Basco": "巴斯科",
  "Bisbee": "比斯比",
  "Basrah": "巴士拉",
  "Balsas": "巴尔萨斯",
  "Bost": "博斯特",
  "Basankusu": "巴桑库苏",
  "Boswell Bay": "博斯韦尔贝",
  "Pathein": "勃生",
  "Bardera Airport": "巴尔代雷机场",
  "Egegik": "埃格吉克",
  "Bertoua": "贝尔图阿",
  "Betou": "贝图",
  "Batticaloa": "拜蒂克洛",
  "Brunette Downs": "布鲁内特唐斯",
  "Bonthe": "邦特",
  "Bountiful": "邦蒂富尔",
  "Batangafo": "巴坦加福",
  "Barter Island L": "巴特岛",
  "Banda Aceh-Suma": "班达亚齐-苏门答腊",
  "Battle Creek": "巴特尔克里克",
  "Bennettsville": "贝内茨维尔",
  "Botopasi": "博托帕西",
  "Butler": "巴特勒",
  "Butare": "布塔雷",
  "Bettles": "贝特尔斯",
  "Batu Licin-Born": "巴图利钦-婆罗洲",
  "Betoota Airport": "贝图塔机场",
  "Beatty": "比蒂",
  "Yarom": "亚罗姆",
  "Bursa": "布尔萨",
  "Buka Island": "布卡岛",
  "Burwell": "伯韦尔",
  "Burketown Airpo": "伯克敦机场",
  "Benguela": "本格拉",
  "Bou Saada Airpo": "布萨达机场",
  "Bulolo": "布洛洛",
  "Buenaventura": "布埃纳文图拉",
  "Burao": "布拉奥",
  "Bhatinda Air Fo": "珀丁达空军基地",
  "Batumi": "巴统",
  "Bau Bau-Butung": "Bau Bau-Butung",
  "Bunbury Airport": "班伯里机场",
  "Bushehr": "布什尔",
  "Rabil": "拉比尔",
  "Brive-la-Gailla": "布里夫拉盖亚尔德",
  "St Dizier": "圣迪济耶",
  "Berlevag": "贝尔莱沃格",
  "Vilhena": "维列纳",
  "Birdsville Airp": "伯兹维尔机场",
  "Bovanenkovo": "博瓦年科沃",
  "Itenes": "伊特内斯",
  "Baures": "鲍勒斯",
  "Belmonte": "贝尔蒙特",
  "Bartlesville": "巴特尔斯维尔",
  "Brava Island": "布拉瓦岛",
  "Breves": "布雷维斯",
  "Beluga": "别卢加",
  "Iturup Island": "择捉岛",
  "Batesville": "贝茨维尔",
  "Beverly": "贝弗利",
  "Beverley Spring": "贝弗利斯普林",
  "Bhairawa": "派勒瓦",
  "Barrow Island A": "巴罗岛机场",
  "Brawley": "布劳利",
  "Brownwood": "布朗伍德",
  "Braunschweig Wo": "不伦瑞克",
  "Barrow-in-Furne": "巴罗因弗内斯",
  "Bowling Green": "鲍灵格林",
  "Brac Island": "布拉奇岛",
  "Blackwell": "布莱克威尔",
  "Bowman": "鲍曼",
  "Balakovo": "巴拉科沃",
  "Brewarrina Airp": "布雷瓦里纳机场",
  "Cayo Santa Mari": "圣玛丽亚岛",
  "Bogalusa": "博加卢萨",
  "Babo-Papua Isla": "巴博-巴布亚岛",
  "Bade-Papua Isla": "巴德-巴布亚岛",
  "Bakel": "巴克尔",
  "Bellburn": "贝尔本",
  "Bendigo Airport": "本迪戈机场",
  "Balkhash": "巴尔喀什",
  "Aima Ata": "阿拉木图",
  "Buckeye": "巴克艾",
  "Buochs": "布奥克斯",
  "Biala Podlaska": "比亚瓦-波德拉斯卡",
  "Bam Airport": "巴姆机场",
  "Borrego Springs": "博雷戈斯普林斯",
  "Bontang-Borneo": "邦唐-婆罗洲",
  "Butuan City": "武端市",
  "Breiddalsvik": "布雷达尔斯维克",
  "Baikonur": "拜科努尔",
  "Al-Bayda": "贝达",
  "Blytheville": "布莱斯维尔",
  "Burley": "伯利",
  "Beja": "贝雅",
  "Bouake Airport": "布瓦凯机场",
  "Bayamo": "巴亚莫",
  "Bayankhongor": "巴彦洪戈尔",
  "Bonito": "博尼图",
  "Barimunya Airpo": "巴里穆尼亚机场",
  "Bunju Island": "班珠岛",
  "Laeso": "莱斯岛",
  "Bantry": "班特里",
  "Bayreuth": "拜罗伊特",
  "Blakely Island": "布莱克利岛",
  "Cabo Frio": "卡布弗里乌",
  "Balranald Airpo": "巴尔拉纳德机场",
  "Balikesir": "巴勒克埃西尔",
  "Bryansk": "布良斯克",
  "Bolzano": "博尔扎诺",
  "Lakefield Natio": "莱克菲尔德国家公园",
  "Strymba": "斯特里姆巴",
  "Brize Norton": "布莱兹诺顿",
  "Catacamas": "卡塔卡马斯",
  "Cabinda": "卡宾达",
  "Cascavel": "卡斯卡韦尔",
  "Cadillac": "凯迪拉克",
  "Carauari": "卡劳阿里",
  "Ca Mau City": "金瓯市",
  "Canaima": "卡奈马",
  "Akron": "阿克伦",
  "Camiri": "卡米里",
  "Clayton": "克莱顿",
  "Cap Haitien": "海地角",
  "Caucasia": "考卡西亚",
  "Caribou": "卡里布",
  "Carmelo": "卡梅洛",
  "Cat Island": "卡特岛",
  "Cascais": "卡斯卡伊斯",
  "Caruaru": "卡鲁阿鲁",
  "Cazombo": "卡宗博",
  "Campos Dos Goyt": "坎普斯-杜斯戈伊塔卡济斯",
  "Carlisle": "卡莱尔",
  "Cobar Airport": "科巴机场",
  "Car Nicobar Air": "卡尔尼科巴空军基地",
  "Cumberland": "坎伯兰",
  "Council Bluffs": "康瑟尔布拉夫斯",
  "Bechar": "贝沙尔",
  "Cabo Rojo": "卡沃罗霍",
  "Colby": "科尔比",
  "Cirebon-Java Is": "井里汶-爪哇岛",
  "Cotabato City": "哥打巴托市",
  "Coimbra Airport": "科英布拉机场",
  "Calabar": "卡拉巴尔",
  "Cabimas": "卡比马斯",
  "Cottbus": "科特布斯",
  "Coban": "科万",
  "Campo Mourao": "坎普莫朗",
  "Condobolin Airp": "康多博林机场",
  "Upland": "厄普兰",
  "New Administrat": "新行政首都",
  "Crane": "克兰",
  "Chile Chico": "奇莱奇科",
  "Concordia": "康科迪亚",
  "Calicut": "卡利卡特",
  "Chinchilla Airp": "钦奇利亚机场",
  "Criciuma": "克里西乌马",
  "Chakcharan": "查赫查兰",
  "Puerto Lopez": "洛佩斯港",
  "Colonia Catriel": "科洛尼亚卡特列尔",
  "Craig Cove": "克雷格科夫",
  "Cowell Airport": "考埃尔机场",
  "Caceres": "卡塞雷斯",
  "Charles City": "查尔斯城",
  "Chub Cay Airpor": "丘布岛机场",
  "Cooinda Airport": "库因达机场",
  "Cedar City": "锡达城",
  "Cauquira": "考奎拉",
  "Cortina D'Ampez": "科尔蒂纳丹佩佐",
  "Camden": "卡姆登",
  "Cachoeiro Do It": "伊塔佩米林河畔卡舒埃鲁",
  "Conceicao Do Ar": "康塞桑-杜阿拉瓜亚",
  "Cedar Key": "锡达礁",
  "Candle": "坎德尔",
  "Cradock": "克拉多克",
  "Cuddapah Airpor": "卡达帕机场",
  "Croydon Airport": "克罗伊登机场",
  "Chadron": "查德龙",
  "Childress": "奇尔德里斯",
  "Calamocha": "卡拉莫查",
  "Castellon de La": "卡斯特利翁-德拉普拉纳",
  "Camden Airport": "卡姆登机场",
  "Caldwell": "考德威尔",
  "Wichita": "威奇托",
  "Crescent City": "克雷森特城",
  "Ceduna Airport": "塞杜纳机场",
  "Hawarden": "哈瓦登",
  "Chelinda Malawi": "切林达马拉维",
  "Central": "森特勒尔",
  "Waco Kungo": "瓦科昆戈",
  "Cessnock Airpor": "塞斯诺克机场",
  "Clemson": "克莱姆森",
  "Connersville": "康纳斯维尔",
  "Crestview": "克雷斯特维尤",
  "Chena Hot Sprin": "切纳温泉",
  "Murray": "默里",
  "Cortez": "科尔特斯",
  "Cacador": "卡萨多尔",
  "Bryan": "布赖恩",
  "Clermont-Ferran": "克莱蒙费朗",
  "Confresa": "孔弗雷萨",
  "Kerkyra Island": "克基拉岛",
  "Coffeyville": "科菲维尔",
  "Cape Girardeau": "开普吉拉多",
  "Camiguin Airpor": "卡米金机场",
  "College Park": "科利奇帕克",
  "Caiguna Airport": "凯古纳机场",
  "Cagayan De Oro": "卡加延德奥罗",
  "Malaybalay City": "马拉巴莱市",
  "Casa Grande": "卡萨格兰德",
  "Chilas": "奇拉斯",
  "Jinhae": "镇海",
  "Chipinge": "奇平加",
  "Chickasha": "奇克谢",
  "Challis": "查利斯",
  "Chimbote": "钦博特",
  "Jeon Ju": "全州",
  "Souda": "苏达",
  "Waitangi": "怀唐伊",
  "Chuathbaluk": "丘阿斯巴卢克",
  "Changuinola": "钱吉诺拉",
  "Roma": "罗马",
  "Aydin": "艾登",
  "Cobija": "科维哈",
  "Chalkyitsik": "乔基齐克",
  "Cimitarra": "西米塔拉",
  "Carroll": "卡罗尔",
  "Chipata": "奇帕塔",
  "Chiquimula": "奇基穆拉",
  "Abariringa": "阿巴里林加",
  "Shymkent": "奇姆肯特",
  "Sault Ste Marie": "苏圣玛丽",
  "Canouan": "卡努安岛",
  "Chiclayo": "奇克拉约",
  "Comiso": "科米索",
  "Coari": "科阿里",
  "Cajamarca": "卡哈马卡",
  "Coondewanna Wa": "昆德万纳",
  "Chumphon Airpor": "春蓬机场",
  "Comitan Airport": "科米坦机场",
  "Cherokee": "切罗基",
  "Cherkasy": "切尔卡瑟",
  "Chokurdah": "乔库尔达赫",
  "Croker Island A": "克罗克岛机场",
  "Ash Flat": "阿什弗拉特",
  "Clarksdale": "克拉克斯代尔",
  "Crookston": "克鲁克斯顿",
  "Cornelio Procop": "科内利乌-普罗科皮乌",
  "Carajas": "卡拉雅斯",
  "Sarakhs": "萨拉赫斯",
  "Clarksville": "克拉克斯维尔",
  "Canakkale": "恰纳卡莱",
  "Comilla": "科米拉",
  "Coolah Airport": "库拉机场",
  "Clintonville": "克林顿维尔",
  "Cluj-Napoca": "克卢日-纳波卡",
  "Clinton": "克林顿",
  "Carolina": "卡罗利纳",
  "Clarks Point": "克拉克斯波因特",
  "Calipatria": "卡利帕特里亚",
  "Chehalis": "奇黑利斯",
  "Caldas Novas": "卡尔达斯诺瓦斯",
  "Clearwater": "克利尔沃特",
  "Clorinda": "克洛林达",
  "Guarico": "瓜里科",
  "Cunnamulla Airp": "坎纳马拉机场",
  "Camocim": "卡莫辛",
  "Cootamundra Air": "库塔曼德拉机场",
  "Ciudad del Carm": "卡门城",
  "Club Makokola": "马科科拉俱乐部",
  "Camooweal Airpo": "卡莫威尔机场",
  "Carmelita": "卡梅利塔",
  "Obbia": "奥比亚",
  "Santana Do Arag": "圣安娜-杜阿拉瓜亚",
  "Clermont Airpor": "克莱蒙机场",
  "Scusciuban": "斯库斯库班",
  "Kundiawa": "昆迪亚瓦",
  "Coromandel Aero": "科罗曼德",
  "Hancock": "汉考克",
  "Sparta": "斯巴达",
  "Cananea Airport": "卡纳内阿机场",
  "Coonamble Airpo": "库南布尔机场",
  "Coconut Island": "椰子岛",
  "Claremont": "克莱蒙特",
  "Changhai": "长海",
  "Cloncurry": "克朗克里",
  "Sindal": "辛达尔",
  "Mattanur": "马塔努尔",
  "Chino": "奇诺",
  "Neerlerit Inaat": "内尔莱里特伊纳特",
  "Corrientes": "科连特斯",
  "Chanaral": "查尼亚拉尔",
  "Chanute": "查努特",
  "Canavieiras": "卡纳维耶拉斯",
  "Moab": "摩押",
  "Coeur d'Alene": "科达莲",
  "Cocoa Beach": "可可比奇",
  "Condoto": "孔多托",
  "Cooch Behar Air": "库奇比哈尔机场",
  "Merritt Island": "梅里特岛",
  "Coonabarabran A": "库纳巴拉布兰机场",
  "Coll Island": "科尔岛",
  "Coleman": "科尔曼",
  "Choibalsan Airp": "乔巴山机场",
  "Colorado Spring": "科罗拉多斯普林斯",
  "Cotulla": "科图拉",
  "Covilha Airport": "科维良机场",
  "Coquimbo": "科金博",
  "Andros": "安德罗斯",
  "Costanza": "康斯坦萨",
  "Harper": "哈珀",
  "Capurgana": "卡普尔加纳",
  "Coober Pedy Air": "库伯佩迪机场",
  "Tjepu-Java Isla": "Cepu-爪哇岛",
  "Chaparral": "查帕拉尔",
  "Compton": "康普顿",
  "Pica": "皮卡",
  "Campinas": "坎皮纳斯",
  "Cururupu": "库鲁鲁普",
  "Culebra Island": "库莱布拉岛",
  "Canarana": "卡纳拉纳",
  "Shahrekord": "沙赫尔库尔德",
  "Marck": "马克",
  "Ciudad Real": "雷阿尔城",
  "Costa Marques": "科斯塔马克斯",
  "Wulong": "武隆",
  "Craiova": "克拉约瓦",
  "Collarenebri Ai": "科拉雷内布赖机场",
  "Cartago": "卡塔戈",
  "Comodoro Rivada": "里瓦达维亚海军准将城",
  "North Myrtle Be": "北默特尔比奇",
  "Carnot": "卡诺",
  "Colonel Hill": "科洛内尔希尔",
  "Catarman": "卡塔曼",
  "Corcoran": "科克伦",
  "Caravelas": "卡拉韦拉斯",
  "Ceres": "塞雷斯",
  "Corsicana": "科西卡纳",
  "Crossett": "克罗塞特",
  "Crotone": "克罗托内",
  "Corinth": "科林斯",
  "Turkmenabat": "土库曼纳巴特",
  "Colonsay": "科伦赛",
  "Caransebes": "卡兰塞贝什",
  "Guapiles": "瓜皮莱斯",
  "Canas": "卡尼亚斯",
  "Creil": "克雷伊",
  "Solovetsky Isla": "索洛韦茨基群岛",
  "Casino Airport": "卡西诺机场",
  "Cap Skirring": "斯基灵角",
  "Cabo San Lucas": "卡波圣卢卡斯",
  "Carson City": "卡森城",
  "Magdeburg": "马格德堡",
  "Creston": "克雷斯顿",
  "Cassilandia": "卡西兰迪亚",
  "Santa Cruz Do S": "南圣克鲁斯",
  "Crossville": "克罗斯维尔",
  "Cheboksary": "切博克萨雷",
  "Coronel Suarez": "苏亚雷斯上校镇",
  "Cut Bank": "卡特班克",
  "Catamarca": "卡塔马卡",
  "Chitre": "奇特雷",
  "Coatepeque": "科阿特佩克",
  "Coatesville": "科茨维尔",
  "Chetumal": "切图马尔",
  "Cooktown Airpor": "库克敦机场",
  "Carutapera": "卡鲁塔佩拉",
  "Santa Vitoria D": "圣维多利亚-杜帕尔马",
  "Le Castellet": "勒卡斯特雷",
  "Cross City": "克罗斯城",
  "Ciudad Constitu": "宪法城",
  "Cucuta": "库库塔",
  "Caloundra Airpo": "卡伦德拉机场",
  "Cuenca": "昆卡",
  "Cuneo": "库内奥",
  "Cudal Airport": "库达尔机场",
  "Cushing": "库欣",
  "Caruru": "Caruru",
  "Carupano": "卡鲁帕诺",
  "Coen Airport": "科恩机场",
  "Cutral-Co": "库特拉尔科",
  "Casigua El Cubo": "卡西瓜-埃尔库博",
  "Cue Airport": "丘机场",
  "Cusco": "库斯科",
  "Cleve Airport": "克利夫机场",
  "Courcheval": "库尔舍韦勒",
  "Hebron": "希伯伦",
  "Lafontaine": "拉方丹",
  "General Mariano": "马里亚诺将军",
  "Clovis": "克洛维斯",
  "Corvallis": "科瓦利斯",
  "Carnarvon Airpo": "卡那封机场",
  "Mosinee": "莫西尼",
  "Chernivtsi": "切尔诺夫策",
  "El Cairo": "开罗",
  "Chitrakoot": "奇特拉库特",
  "Cowarie Airport": "考阿里机场",
  "Cowra Airport": "考拉机场",
  "Corowa Airport": "科罗瓦机场",
  "Willcox": "威尔科克斯",
  "Caicara del Ori": "奥里诺科河畔凯卡拉",
  "Cox's Bazar": "科克斯巴扎尔",
  "Coldfoot": "科尔德富特",
  "Banana": "巴纳纳",
  "Caxias Do Sul": "南卡希亚斯",
  "Calexico": "卡莱克西科",
  "Camaxilo": "卡马希洛",
  "Candala": "坎达拉",
  "Charters Towers": "查特斯堡",
  "Les Cayes": "莱凯",
  "Chefornak": "切福尔纳克",
  "Corryong Airpor": "科里扬机场",
  "Chiayi City": "嘉义市",
  "Coyoles": "科约莱斯",
  "Cayo Largo del": "拉戈岛",
  "Calbayog City": "卡尔巴约格市",
  "Colonia": "科洛尼亚",
  "Yakataga": "亚卡塔加",
  "Celaya": "塞拉亚",
  "Cherskiy": "切尔斯基",
  "Cauayan City": "卡瓦扬市",
  "Chichen Itza In": "奇琴伊察国际机场",
  "Coro": "科罗",
  "Cape Romanzof": "罗曼佐夫角",
  "Cruzeiro Do Sul": "南克鲁赛罗",
  "Carrizo Springs": "卡里索斯普林斯",
  "Corozal": "科罗萨尔",
  "Czestochowa": "琴斯托霍瓦",
  "Cluny Airport": "克鲁尼机场",
  "Fort Belvoir": "贝尔沃堡",
  "Daporijo Airpor": "达波里霍机场",
  "Daggett": "达格特",
  "Dakhla Airport": "达赫拉机场",
  "Danville": "丹维尔",
  "Darchula": "达尔楚拉",
  "Great Bear Lake": "大熊湖",
  "Daru": "达鲁",
  "David": "戴维",
  "Darwaz": "达瓦兹",
  "Dalbandin": "达尔本丁",
  "El Alamein": "阿拉曼",
  "Dhanbad Airport": "丹巴德机场",
  "Debra Marcos": "德布雷马尔科斯",
  "Darbhanga": "达尔彭加",
  "Dalby Airport": "多尔比机场",
  "Canefield": "肯菲尔德",
  "Decimomannu": "德奇莫曼努",
  "RAAF Base Curti": "澳大利亚皇家空军柯蒂斯基地",
  "Duncan Town Air": "邓肯镇机场",
  "Dodge City": "道奇城",
  "Delta Downs Air": "三角洲唐斯机场",
  "Rikaze Dingri A": "日喀则定日机场",
  "Dadu": "达杜",
  "Dehradun": "德拉敦",
  "Kunashir Island": "国后岛",
  "Dezful Airport": "迪兹富勒机场",
  "Decorah": "迪科拉",
  "Derim": "德里姆",
  "Deir ez-Zor": "代尔祖尔",
  "Defiance": "迪法恩斯",
  "Dalgaranga Gold": "达尔加兰加金矿",
  "Mudgee": "马吉",
  "Douglas Lake": "道格拉斯湖",
  "Deoghar": "德奥加尔",
  "Douglas": "道格拉斯",
  "Dahlgren": "达尔格伦",
  "Daugavpils": "陶格夫匹尔斯",
  "Dargaville Aero": "达格维尔",
  "Dumaguete City": "杜马格特市",
  "St. Athan": "圣阿萨",
  "King Abdulaziz": "阿卜杜勒-阿齐兹国王",
  "Durham Downs Ai": "达勒姆唐斯机场",
  "Al Dhafra Air B": "哈弗拉空军基地",
  "Dhangarhi": "丹加地",
  "Kangra Airport": "康格拉机场",
  "Den Helder": "登海尔德",
  "Dalhart": "达尔哈特",
  "Arrachart Airpo": "阿拉查特机场",
  "Dimbokro": "丁博克罗",
  "Divinopolis": "迪维诺波利斯",
  "Dire Dawa": "德雷达瓦",
  "Dolisie": "多利西",
  "Djougou": "朱古",
  "Djanet": "贾奈特",
  "Djambala": "占巴拉",
  "Daloa Airport": "达洛亚机场",
  "Dajarra Airport": "达贾拉机场",
  "Djupivogur": "都皮沃古尔",
  "Dunk Island Air": "邓克岛机场",
  "Dunkirk": "敦刻尔克",
  "Dikson": "迪克森",
  "Docker River Ai": "多克河机场",
  "Dagali": "达加利",
  "Del Rio": "德尔里奥",
  "Dalat": "大叻",
  "Dillon": "狄龙",
  "The Dalles": "达尔斯",
  "Delissaville Ai": "德利萨维尔机场",
  "Dillon's Bay": "狄龙湾",
  "Dalanzadgad": "达兰扎德盖德",
  "Tucson": "图森",
  "Taraz": "塔拉兹",
  "Doomadgee Airpo": "杜马吉机场",
  "Ad Dammam": "达曼",
  "Deming": "德明",
  "Sedalia": "塞达利亚",
  "Diamantino": "迪亚曼蒂努",
  "Dimapur": "迪马普尔",
  "Kadena Air Base": "嘉手纳空军基地",
  "Dunbar Airport": "邓巴机场",
  "Dundee": "邓迪",
  "Dnipropetrovsk": "第聂伯罗彼得罗夫斯克",
  "Dianopolis": "迪亚诺波利斯",
  "Dang": "当",
  "Deniliquin Airp": "德尼利昆机场",
  "Denison": "丹尼森",
  "Dobo-Kobror Isl": "多博-科布罗尔岛",
  "Djumu-Djomoe": "朱umu",
  "Dongola": "栋古拉",
  "Deauville": "多维尔",
  "Marigot": "马里戈特",
  "Dos Lagunas": "多斯拉古纳斯",
  "Dolpa": "多尔帕",
  "Dori": "多里",
  "Dourados": "多拉杜斯",
  "Dover": "多佛",
  "Dieppe": "迪耶普",
  "Dugway Proving": "达格威试验场",
  "Dipolog City": "第波罗市",
  "Deadhorse": "戴德霍斯",
  "Duqm": "杜库姆",
  "Mercury": "默丘里",
  "Derby Airport": "德比机场",
  "Dorunda Airport": "多伦达机场",
  "Drummond Island": "德拉蒙德岛",
  "Deering": "迪灵",
  "De Ridder": "德里德",
  "Drietabbetje": "德里塔贝杰",
  "Puntarenas": "彭塔雷纳斯",
  "Dirranbandi Air": "迪兰班迪机场",
  "Daraga": "达拉加",
  "Durrie Airport": "杜里机场",
  "Drysdale River": "干河",
  "Dschang": "德昌",
  "Grande Anse": "大灣",
  "Destin": "德斯坦",
  "Dera Ismael Kha": "德拉伊斯梅尔汗",
  "Sondok Airport": "宣德机场",
  "Diass": "迪亚斯",
  "Dansville": "丹斯维尔",
  "Delta": "德尔塔",
  "Siborong-Borong": "锡博龙博龙",
  "Datadawai-Borne": "达塔达瓦伊-婆罗洲",
  "Daet": "达特",
  "Diamantina": "迪亚曼蒂纳",
  "Detroit Lakes": "底特律湖",
  "Durant": "杜兰特",
  "Duncan": "邓肯",
  "Chitato": "奇塔托",
  "Corolla": "卡罗拉",
  "Douglas Bisbee": "道格拉斯-比斯比",
  "Dubois": "杜波依斯",
  "Mubatuba": "穆巴图巴",
  "Dumai-Sumatra I": "杜迈-苏门答腊岛",
  "Unalaska": "乌纳拉斯卡",
  "Diavik": "戴维科",
  "Devils Lake": "魔鬼湖",
  "Davenport": "达文波特",
  "Davenport Downs": "达文波特唐斯",
  "Dwangwa": "德旺瓦",
  "Dawadmi": "达瓦德米",
  "New Dixie": "新迪克西",
  "Noida": "诺伊达",
  "Danbury": "丹伯里",
  "Dysart Airport": "戴萨特机场",
  "Doylestown": "多伊尔斯敦",
  "Daly Waters": "戴利沃特斯",
  "Dzaoudzi": "藻德济",
  "Zhezkazgan": "热兹卡兹甘",
  "Durazno": "杜拉斯诺",
  "Eagle": "伊格尔",
  "Wheatland": "惠特兰",
  "Hondarribia": "丰特拉维亚",
  "Marina Di Camp": "迪坎普码头",
  "Kampala": "坎帕拉",
  "Al-Ubayyid": "奥贝德",
  "El Bagre": "巴格雷",
  "El Bayadh": "贝耶德",
  "Arbil": "阿尔贝拉",
  "El Borma": "博尔马",
  "Webster City": "韦伯斯特城",
  "Ebolowa": "埃博洛瓦",
  "Elizabeth City": "伊丽莎白城",
  "Echuca Airport": "伊丘卡机场",
  "Nicosia": "尼科西亚",
  "Panama City Bea": "巴拿马城海滩",
  "Newcastle": "纽卡斯尔",
  "Edenton": "伊登顿",
  "La Roche-sur-Yo": "永河畔拉罗什",
  "Edremit": "埃德雷米特",
  "Pormpuraaw Airp": "波姆普劳机场",
  "Edwards": "爱德华兹",
  "Needles": "尼德尔斯",
  "Eek": "埃克",
  "Newport": "纽波特",
  "Kefallinia Isla": "凯法利尼亚岛",
  "Jefferson": "杰斐逊",
  "El Gora Airport": "埃尔戈拉机场",
  "Geneina": "朱奈纳",
  "Eagle River": "伊格尔里弗",
  "El Bolson": "埃尔博尔松",
  "Cape Newenham": "纽芬兰角",
  "Eisenach": "爱森纳赫",
  "Yeniseysk": "叶尼塞斯克",
  "Yeysk": "叶伊斯克",
  "Sapir": "萨皮尔",
  "Al Wajh": "瓦季赫",
  "Ejina Banner Ta": "额济纳旗",
  "Ekibastuz": "埃基巴斯图兹",
  "Elkhart": "埃尔克哈特",
  "Elkins": "埃尔金斯",
  "Shakhtersk": "沙赫乔尔斯克",
  "Eskilstuna": "埃斯基尔斯蒂纳",
  "Elizabethtown": "伊丽莎白镇",
  "Eagle Lake": "伊格尔莱克",
  "El Banco": "埃尔班科",
  "Elcho Island": "埃尔乔岛",
  "El Golea Airpor": "古莱阿机场",
  "North Eleuthera": "北伊柳塞拉",
  "Elim": "埃利姆",
  "Elk City": "埃尔克城",
  "Ellisras": "埃利斯拉斯",
  "Ellensburg": "埃伦斯堡",
  "El Tor Airport": "图尔机场",
  "Guemar": "盖马尔",
  "Ely": "伊利",
  "Wellsville": "韦尔斯维尔",
  "Nottingham": "诺丁汉",
  "Emden": "埃姆登",
  "Empangeni": "恩潘盖尼",
  "Emmonak": "埃莫纳克",
  "Emmen Airport": "埃门机场",
  "Kemmerer": "肯默勒",
  "Nema": "内马",
  "Emporia": "恩波里亚",
  "El Monte": "艾尔蒙地",
  "El Maiten": "迈滕",
  "Ende-Flores Isl": "恩德-弗洛勒斯岛",
  "Enontekio": "埃农泰基厄",
  "El Nido": "爱妮岛",
  "Enniskillen": "恩尼斯基林",
  "Centralia": "森特勒利亚",
  "Nenana": "尼纳纳",
  "Encarnacion": "恩卡纳西翁",
  "Eniwetok Atoll": "埃尼威托克环礁",
  "Enegu": "埃内古",
  "Wendover": "温多弗",
  "Kenosha": "基诺沙",
  "Eday": "伊代",
  "Keokuk": "基奥卡克",
  "Bolivar": "玻利瓦尔",
  "Neosho": "尼奥绍",
  "Elorza Airport": "埃洛萨机场",
  "El Palomar": "帕洛马尔",
  "Ephrata": "埃夫拉塔",
  "Esperance Airpo": "埃斯佩兰斯机场",
  "Arroyo Barril": "阿罗约巴里尔",
  "Samana": "萨马纳",
  "Parnu": "派尔努",
  "Erigavo": "埃里加沃",
  "Ernabella Airpo": "恩纳贝拉机场",
  "Berdyansk": "别尔江斯克",
  "Erbogachen": "叶尔博加琴",
  "Erechim": "埃雷欣",
  "Eirunepe": "埃鲁内佩",
  "Errol": "埃勒尔",
  "Windhoek": "温得和克",
  "Kerrville": "克尔维尔",
  "Eastsound": "东湾",
  "Ensenada Airpor": "恩塞纳达机场",
  "Mariscal Estiga": "马里斯卡尔埃斯蒂加里维亚",
  "Brighton": "布莱顿",
  "Espinosa": "埃斯皮诺萨",
  "Eskisehir": "埃斯基谢希尔",
  "Elista": "埃利斯塔",
  "Tachina": "塔奇纳",
  "Easton": "伊斯顿",
  "Essen Mulheim A": "埃森/米尔海姆机场",
  "Estherville": "埃斯特维尔",
  "West Bend": "西本德",
  "Metema": "梅泰马",
  "Eilat": "埃拉特",
  "Eastland": "伊斯特兰",
  "Enterprise": "恩特普赖斯",
  "Eua Island": "埃瓦岛",
  "Eufaula": "尤福拉",
  "Neumunster": "新明斯特",
  "El Aaiun": "阿尤恩",
  "Sint Eustatius": "圣尤斯特歇斯",
  "Sveg Airport": "斯韦格机场",
  "Evans Head Aero": "埃文斯黑德",
  "Eveleth": "伊夫莱斯",
  "Evanston": "埃文斯顿",
  "New Bedford": "新贝德福德",
  "Enarotali-Papua": "埃纳罗塔利-巴布亚",
  "Newton": "牛顿",
  "New Bern": "新伯尔尼",
  "Ewo": "埃沃",
  "Yelimane": "耶利马内",
  "El Yopal": "约帕尔",
  "Yerington": "耶灵顿",
  "Ezeiza": "埃塞萨",
  "Berezovo Airpor": "别廖佐沃机场",
  "Faranah Airport": "法拉纳机场",
  "Farnborough": "法恩伯勒",
  "Faaite Airport": "法艾特机场",
  "Vagar": "瓦格",
  "Fort Eustis": "尤斯蒂斯堡",
  "Fagurholsmyri": "法古霍斯梅里",
  "Farah": "法拉",
  "Fajardo": "法哈多",
  "Farsund": "法尔松",
  "Frieda River": "弗里达河",
  "Faskrudsfjordur": "福斯克鲁斯菲厄泽",
  "Fahud": "法胡德",
  "Fakarava Airpor": "法卡拉瓦机场",
  "Fasa": "法萨",
  "Fonte Boa": "丰蒂博阿",
  "Faizabad": "法扎巴德",
  "Francisco Beltr": "弗朗西斯科贝尔特朗",
  "Fort Bragg": "布拉格堡",
  "Faribault": "法里博",
  "Fort Bridger": "布里杰堡",
  "Fairbury": "费尔伯里",
  "Ficksburg": "菲克斯堡",
  "Fort Carson": "卡森堡",
  "Forrest City": "福雷斯特城",
  "Fundacion": "丰达西翁",
  "Forde": "福德",
  "Fort-de-France": "法兰西堡",
  "Frederick": "弗雷德里克",
  "Bandundu Airpor": "班顿杜机场",
  "Findlay": "芬德利",
  "Sanfebagar": "桑费巴加尔",
  "Feira De Santan": "圣安娜-迪费拉",
  "Fergana": "费尔干纳",
  "Feijo": "费若",
  "Furstenfeldbruc": "菲尔斯滕费尔德布鲁克",
  "Fernando De Nor": "费尔南多-迪诺罗尼亚",
  "Fremont": "弗里蒙特",
  "Kill Devil Hill": "基尔德夫尔希尔斯",
  "Fairford": "费尔福德",
  "Fairfield": "费尔菲尔德",
  "Fergus Falls": "弗格斯福尔斯",
  "Frankfort": "法兰克福",
  "Futaleufu": "富塔莱乌富",
  "Fderik": "德里克",
  "Fangatau Airpor": "方阿陶机场",
  "Fernandina Beac": "费南迪纳比奇",
  "Fort Huachuca S": "瓦丘卡堡",
  "Fishers Island": "费舍斯岛",
  "Fria Airport": "弗里亚机场",
  "Fillmore": "菲尔莫尔",
  "Buki": "布基",
  "Fitzroy Crossin": "菲茨罗伊克罗辛",
  "Fujairah Intern": "富查伊拉国际机场",
  "Baden-Baden": "巴登-巴登",
  "Fukui Airport": "福井机场",
  "Franklin": "富兰克林",
  "Floriano": "弗洛里亚诺",
  "Fond du Lac": "拉克",
  "Flensburg": "弗伦斯堡",
  "Flateyri": "弗拉泰里",
  "Filadelfia": "费城",
  "Flippin": "弗利平",
  "Firenze": "佛罗伦萨",
  "Flinders Island": "弗林德斯岛",
  "Fort Leavenwort": "莱文沃思堡",
  "Santa Cruz das": "圣克鲁斯达斯弗洛雷斯",
  "Fallon": "法伦",
  "Sibolga-Sumatra": "实武牙-苏门答腊",
  "Formosa": "福莫萨",
  "Five Mile": "五英里",
  "Brasilito": "巴西利托",
  "Falmouth": "法尔茅斯",
  "Kalemie Airport": "卡莱米机场",
  "Memmingen": "梅明根",
  "Munster": "明斯特",
  "Fort Madison": "麦迪逊堡",
  "Neubrandenburg": "新勃兰登堡",
  "Funchal": "丰沙尔",
  "Funadhoo": "富纳杜",
  "Fane Mission": "法恩米申",
  "Fada N'gourma": "法达恩古尔马",
  "Oristano": "奥里斯塔诺",
  "Topeka": "托皮卡",
  "Foggia": "福贾",
  "Westhampton Bea": "西汉普顿海滩",
  "Foumban": "丰班",
  "Kornasoren-Numf": "科纳索伦-努姆福尔",
  "Forrest Airport": "福雷斯特机场",
  "Fougamou": "富加穆",
  "Fort Pierce": "皮尔斯堡",
  "Perry": "佩里",
  "Forbes": "福布斯",
  "Franca": "弗兰卡",
  "Friday Harbor": "星期五港",
  "Oschersleben": "奥舍斯莱本",
  "Farmingdale": "法明代尔",
  "French Lick": "弗伦奇利克",
  "Fregate Island": "弗雷格特岛",
  "Forli": "弗利",
  "Fairmont": "费尔蒙特",
  "Fort Richardson": "理查森堡",
  "Front Royal": "弗兰特罗亚尔",
  "San Benito": "圣贝尼托",
  "Frutillar": "富鲁蒂亚尔",
  "Fryeburg": "弗赖堡",
  "Fritzlar": "弗里茨拉尔",
  "Figari Sud-Cors": "菲加里南科西嘉",
  "Fort Sill": "西尔堡",
  "Fort Scott": "斯科特堡",
  "Kinloss": "金洛斯",
  "Fort Stockton": "斯托克顿堡",
  "Fort Sumner": "萨姆纳堡",
  "Futuna Island": "富图纳岛",
  "El Calafate": "埃尔卡拉法特",
  "Fitiuta Village": "菲蒂乌塔村",
  "Fort Knox": "诺克斯堡",
  "Owando": "奥旺多",
  "Fuerteventura I": "富埃特文图拉岛",
  "Goto": "五岛",
  "Fullerton": "富勒顿",
  "Fuvahmulah Isla": "富瓦穆拉岛",
  "Farewell": "费尔韦尔",
  "Cuamba": "库安巴",
  "Forest City": "福雷斯特城",
  "Faya Largeau Ai": "法亚-拉若机场",
  "Fort Yukon": "育空堡",
  "Gabbs": "加布斯",
  "El Molino": "莫利诺",
  "Gabes": "加贝斯",
  "Gafsa": "加夫萨",
  "Gage": "盖奇",
  "Gayndah Airport": "盖恩达机场",
  "Gaithersburg": "盖瑟斯堡",
  "Galena": "加利纳",
  "Gambell": "甘贝尔",
  "Gan": "甘岛",
  "Guantanamo": "关塔那摩",
  "Gusap": "古萨普",
  "Gao Airport": "加奥机场",
  "Garaina": "加莱纳",
  "Garissa": "加里萨",
  "Avignon": "阿维尼翁",
  "Guwahati": "古瓦哈提",
  "Gangaw": "甘高",
  "Gaya Airport": "格雅机场",
  "Kemble": "肯布尔",
  "Gabala": "盖贝莱",
  "Great Bend": "大本德",
  "Negarbo": "内加尔博",
  "Galesburg": "盖尔斯堡",
  "Galbraith Lake": "高尔布雷斯湖",
  "Grand Bahama": "大巴哈马",
  "Kalaburagi": "卡拉布拉吉",
  "Grand Bourg": "大布尔",
  "Gbangbatok": "邦巴托克",
  "South Goulburn": "南古尔本",
  "Great Barringto": "大巴林顿",
  "Gorgan": "戈尔甘",
  "Gibb River Airp": "吉布河机场",
  "Ginbata": "金巴塔",
  "Claris": "克拉里斯",
  "Electric City": "电气城",
  "Gachsaran Airpo": "加奇萨兰机场",
  "Saint Peter Por": "圣彼得港",
  "Midrand": "米德兰",
  "Garden City": "加登城",
  "Grand Canyon": "大峡谷",
  "Peach Springs": "桃泉",
  "Greeneville": "格林维尔",
  "Gordon Downs": "戈登唐斯",
  "Gode": "戈德",
  "Melle": "梅勒",
  "Gandajika": "甘达吉卡",
  "Guadalajara": "瓜达拉哈拉",
  "Gardner": "加德纳",
  "Guasdalito Airp": "瓜斯达利托机场",
  "Guadalupe": "瓜达卢佩",
  "Gondar": "贡德尔",
  "Gladwin": "格拉德温",
  "Grundy": "格兰迪",
  "Gelendzhik": "格连吉克",
  "Noumea": "努美阿",
  "Gebe Island": "格贝岛",
  "Santo Angelo": "圣安热卢",
  "Nueva Gerona": "新赫罗纳",
  "General Santos": "桑托斯将军城",
  "Tambler Airport": "坦布勒机场",
  "Geraldton Airpo": "杰拉尔顿机场",
  "Gallivare": "耶利瓦勒",
  "Geelong Airport": "吉朗机场",
  "Greybull": "格雷布尔",
  "Griffith": "格里菲斯",
  "Glens Falls": "格伦斯福尔斯",
  "Grafton Airport": "格拉夫顿机场",
  "Bartica": "巴蒂卡",
  "Granville": "格兰维尔",
  "Grootfontein": "赫鲁特方丹",
  "Agua Boa": "阿瓜博阿",
  "Gregory Downs A": "格雷戈里唐斯机场",
  "Almeirim": "阿尔梅林",
  "Cianorte": "夏诺特",
  "Kakamega": "卡卡梅加",
  "Gagnoa": "加尼奥阿",
  "Gobernador Greg": "格雷戈雷斯省长镇",
  "George Town": "乔治敦",
  "Ghardaia": "盖尔达耶",
  "Governor's Harb": "州长港",
  "Great Harbour C": "大港岛",
  "Giebelstadt Arm": "吉伯尔斯塔特",
  "Centerville": "森特维尔",
  "Gualeguaychu": "瓜莱瓜伊丘",
  "Boigu Airport": "博伊古机场",
  "Gitega": "基特加",
  "Winter Haven": "温特黑文",
  "Rio De Janeiro": "里约热内卢",
  "Siguiri": "西吉里",
  "Girardot": "希拉多特",
  "Sigiriya": "锡吉里耶",
  "Giyani": "吉亚尼",
  "Jizan": "吉赞",
  "Guanaja": "瓜纳哈",
  "Guajara-Mirim": "瓜雅拉米林",
  "Gjogur": "焦古尔",
  "Goronka": "戈龙卡",
  "Gokceada": "格克切岛",
  "Geilenkirchen A": "盖伦基尔兴机场",
  "Gorkha": "廓尔喀",
  "Great Keppel Is": "大克佩尔岛",
  "Gulkana": "古尔卡纳",
  "Sevierville": "塞维尔维尔",
  "Glengyle Airpor": "格伦盖尔机场",
  "Glen Innes Airp": "格伦因尼斯机场",
  "Garzon": "加尔松",
  "Galcaio": "加勒卡约",
  "Klanten": "克拉滕",
  "Glenormiston Ai": "格伦诺米斯顿机场",
  "Staverton": "斯塔弗顿",
  "Gaylord": "盖洛德",
  "Galveston": "加尔维斯顿",
  "Golovin": "戈洛温",
  "Galela-Celebes": "加莱拉-西里伯斯",
  "Breda": "布雷达",
  "Gemena": "格梅纳",
  "Ben Slimane": "本斯利曼",
  "Gomel": "戈梅利",
  "Gasmata Island": "加斯马塔岛",
  "Gamboma": "甘博马",
  "Greymouth Airpo": "格雷茅斯机场",
  "Gombe": "贡贝",
  "Totegegie Airpo": "托泰日日机场",
  "Granite Mountai": "格兰尼特芒廷",
  "Alajero": "阿拉赫罗",
  "Hrodna": "格罗德诺",
  "Saint George's": "圣乔治",
  "Gooding": "古丁",
  "Lyudao": "绿岛",
  "Ganja": "占贾",
  "Guanambi": "瓜南比",
  "Ghinnir": "吉尼尔",
  "General Roca": "罗卡将军镇",
  "Gunung Sitoli-N": "古农西托利-尼亚斯",
  "Grants": "格兰茨",
  "Sanliurfa": "尚勒乌尔法",
  "Ghanzi": "杭济",
  "Genova": "热那亚",
  "Goba": "戈巴",
  "Dabolim": "达波里姆",
  "Nizhny Novgorod": "下诺夫哥罗德",
  "Guthrie": "格思里",
  "Goondiwindi Air": "贡迪温迪机场",
  "Gorakhpur": "哥拉普",
  "Nhulunbuy": "纽兰拜",
  "Amparai": "安帕赖",
  "Gorna Oryahovit": "上奥里亚霍维察",
  "Guarapuava": "瓜拉普瓦瓦",
  "Guapi": "瓜皮",
  "Garden Point Ai": "花园角机场",
  "General Pico": "皮科将军镇",
  "Baltra": "巴尔特拉",
  "Gulfport": "格尔夫波特",
  "Galion": "加利恩",
  "Greenwood": "格林伍德",
  "Au": "奥",
  "Grand Marais": "大马雷",
  "Gordon": "戈登",
  "Girona": "赫罗纳",
  "Gurupi": "古鲁皮",
  "Groningen": "格罗宁根",
  "Grosetto": "格罗塞托",
  "Santa Cruz da G": "圣克鲁斯达格拉西奥萨",
  "Grimsey": "格里姆塞岛",
  "Long Miau": "长喵",
  "Goldsboro": "戈尔兹伯勒",
  "Goshen": "戈申",
  "Grand-Santi": "大圣蒂",
  "Puerto San Jose": "圣何塞港",
  "Dayrestan Airpo": "代雷斯坦机场",
  "Mount Gunson": "冈森山",
  "Shark El Oweina": "沙尔克奥韦纳特",
  "Gardo": "加尔多",
  "Gustavus": "古斯塔夫斯",
  "Fort Drum": "德拉姆堡",
  "Groote Eylandt": "格鲁特岛",
  "Grantsburg": "格兰茨堡",
  "Rugen": "吕根岛",
  "Glentanner Stat": "格伦坦纳",
  "Gorontalo-Celeb": "哥伦打洛-西里伯斯",
  "Grants Pass": "格兰茨帕斯",
  "Granite Downs A": "格兰尼特唐斯机场",
  "Georgetown Airp": "乔治敦机场",
  "Holesov": "霍莱索夫",
  "Guatemala City": "危地马拉城",
  "Guerrero Negro": "格雷罗内格罗",
  "Gunnison": "甘尼森",
  "Goundam": "贡达姆",
  "Gulf Shores": "格尔夫海岸",
  "Gunnedah Airpor": "冈尼达机场",
  "Guaratingueta": "瓜拉廷格塔",
  "Goulburn Airpor": "古尔本机场",
  "Guanare": "瓜纳雷",
  "Gurney": "格尼",
  "Peru": "秘鲁",
  "Gutersloh": "居特斯洛",
  "Grundarfjordur": "格伦达菲厄泽",
  "Mougulu": "穆古鲁",
  "Atyrau": "阿特劳",
  "Guna Airport": "古纳机场",
  "Guymon": "盖蒙",
  "Guarapari": "瓜拉帕里",
  "Green River": "格林里弗",
  "Sovetskaya Gava": "苏维埃港",
  "Governador Vala": "瓦拉达里斯州长市",
  "Gwa": "瓜",
  "Gwadar": "瓜达尔",
  "Gwalior": "瓜廖尔",
  "Glenwood Spring": "格伦伍德斯普林斯",
  "Sayun": "赛永",
  "Negage": "内加格",
  "Coyhaique": "科伊艾克",
  "Greeley": "格里利",
  "Guayaramerin": "瓜亚拉梅林",
  "Guayaquil": "瓜亚基尔",
  "Magan": "马根",
  "Gisenyi": "吉塞尼",
  "Argyle Airport": "阿盖尔机场",
  "Guaymas": "瓜伊马斯",
  "Gympie Airport": "金皮机场",
  "Goodyear": "固特异",
  "Gruyere": "格吕耶尔",
  "Gazipasa": "加济帕夏",
  "Qazvin": "加兹温",
  "Hasvik": "哈斯维克",
  "Hachijojima": "八丈岛",
  "Half Moon Bay": "半月湾",
  "Three Rivers": "三河市",
  "Hannover": "汉诺威",
  "Haa Dhaalu Atol": "哈达鲁环礁",
  "Hail Airport": "哈伊勒机场",
  "Karmoy": "卡姆岛",
  "Haverfordwest": "哈弗福德韦斯特",
  "Aguachica": "阿瓜奇卡",
  "Hattiesburg": "哈蒂斯堡",
  "Holbrook": "霍尔布鲁克",
  "Bulgan Sum Airp": "布尔干苏木机场",
  "Hubli": "胡布利",
  "Hudson": "哈德逊",
  "Eil": "埃勒",
  "Hengchung": "恒春",
  "Halls Creek Air": "霍尔斯克里克机场",
  "Holy Cross": "霍利克罗斯",
  "Cheraw": "奇罗",
  "Chenzhou": "郴州",
  "Holdrege": "霍尔德里奇",
  "Mokuleia": "莫库莱亚",
  "Kulhudhuffushi": "库尔胡杜夫希",
  "Hamadan": "哈马丹",
  "Hayden": "海登",
  "Hindon Air Forc": "欣登空军基地",
  "Havadarya": "哈瓦达里亚",
  "Herat Airport": "赫拉特机场",
  "Herendeen Bay": "赫伦丁湾",
  "Busum": "叙尔特岛",
  "Hermiston": "赫米斯顿",
  "Gibraleon": "希夫拉莱昂",
  "Natchez": "纳奇兹",
  "Camp Mackall": "麦卡尔营",
  "Hornafjordur": "赫本",
  "Hagfors Airport": "哈格福什机场",
  "Hughenden Airpo": "休恩登机场",
  "Higuerote Airpo": "伊格罗特机场",
  "Itanagar": "伊塔那噶",
  "Helgoland": "黑尔戈兰岛",
  "Mae Hong Son Ai": "夜丰颂机场",
  "Korhogo Airport": "科霍戈机场",
  "Hogatza": "霍加察",
  "Hachinohe Airpo": "八户机场",
  "Hilton Head Isl": "希尔顿黑德岛",
  "Wahiawa": "瓦希瓦",
  "Hahn": "哈恩",
  "Hua Hin": "华欣",
  "Hawthorne": "霍桑",
  "Hikueru Atoll": "希库埃鲁环礁",
  "Hibbing": "希宾",
  "Horn Island": "霍恩岛",
  "Whitefield": "怀特菲尔德",
  "Ogden": "奥格登",
  "Lake Havasu Cit": "哈瓦苏湖城",
  "Sacheon": "泗川",
  "Hiroshimanishi": "广岛西",
  "Khujirt Airport": "忽吉尔特机场",
  "Hokitika Airfie": "霍基蒂卡机场",
  "Hoskins": "霍斯金斯",
  "Haskovo": "哈斯科沃",
  "Hill City": "希尔城",
  "Hultsfred Airpo": "胡尔茨弗雷德机场",
  "Wheeling": "惠灵",
  "Hollister": "霍利斯特",
  "Barysiai": "巴里西亚伊",
  "Holland": "霍兰",
  "Onundarfjordur": "厄嫩达菲厄泽",
  "St Helens Airpo": "圣海伦斯机场",
  "Hamilton Airpor": "汉密尔顿机场",
  "Hluhluwe": "赫卢赫卢韦",
  "Angelsey": "安格尔西岛",
  "Sohag": "索哈杰",
  "Hassi Messaoud": "哈西迈萨乌德",
  "Hermannsburg Ai": "赫曼斯堡机场",
  "Khmelnytskyi": "赫梅利尼茨基",
  "Alamogordo": "阿拉莫戈多",
  "Hamar": "哈马尔",
  "Hemet": "赫米特",
  "Hemavan Airport": "海马凡机场",
  "Seosan": "瑞山",
  "Huntingburg": "亨廷堡",
  "Hatteras": "哈特拉斯",
  "Tahneta Pass Lo": "塔赫内塔山口",
  "Hoonah": "胡纳",
  "Hana": "哈纳",
  "Haines": "海恩斯",
  "Hola": "奥拉",
  "Hodeida": "荷台达",
  "Al Ahsa Airport": "哈萨机场",
  "Hao Airport": "哈奥机场",
  "Hooker Creek Ai": "胡克克里克机场",
  "Chos Malal": "乔斯马拉尔",
  "Orsta": "奥勒斯塔",
  "Hommalinn": "霍马林",
  "Lifuka": "利富卡",
  "Hooper Bay": "胡珀湾",
  "Hampton": "汉普顿",
  "Baytown": "贝敦",
  "Tashkurgan": "塔什库尔干",
  "Hoquiam": "霍奎厄姆",
  "Hoarafushi": "霍拉富希",
  "Hassi R'Mel Air": "哈西鲁迈勒机场",
  "Harrison": "哈里森",
  "Harrismith": "哈里史密斯",
  "Linton-On-Ouse": "林顿-昂-乌斯",
  "Horizontina": "奥里藏蒂纳",
  "Turkistan": "突厥斯坦",
  "Hastings": "黑斯廷斯",
  "Huslia": "胡斯利亚",
  "Horsham Airport": "霍舍姆机场",
  "Hissar Airport": "希萨尔机场",
  "Homestead": "霍姆斯特德",
  "Hsinchu City": "新竹市",
  "Khatanga": "哈坦加",
  "Hamilton Island": "汉密尔顿岛",
  "Houghton Lake": "霍顿湖",
  "East Hampton": "东汉普顿",
  "Hateruma": "波照间",
  "Hopetoun Airpor": "霍普敦机场",
  "Hatay": "哈塔伊",
  "Hato Corozal": "阿托科罗萨尔",
  "Redstone Arsnl": "雷德斯通兵工厂",
  "Terre Haute": "特雷霍特",
  "Huehuetenango": "韦韦特南戈",
  "Fare": "法雷",
  "Hugo": "雨果",
  "Houlton": "霍尔顿",
  "Houma": "霍马",
  "Holingol": "霍林郭勒",
  "Hughes": "休斯",
  "Hutchinson": "哈钦森",
  "Huanuco": "瓦努科",
  "Humaita": "乌迈塔",
  "Grimsby": "格里姆斯比",
  "Khovd": "科布多",
  "Hanksville": "汉克斯维尔",
  "Holmavik": "霍尔马维克",
  "Hvammstangi": "瓦姆斯唐吉",
  "New Haven": "纽黑文",
  "Hartsville": "哈茨维尔",
  "Hayward": "海沃德",
  "Hawker": "霍克",
  "Hwange": "万盖",
  "Hollywood": "好莱坞",
  "Hay Airport": "海伊机场",
  "High Wycombe": "海威科姆",
  "Hays": "海斯",
  "Hyvinkaa Airfir": "海门屈莱机场",
  "Hazleton": "黑泽尔顿",
  "Fort Mackay": "麦凯堡",
  "Niagara Falls": "尼亚加拉瀑布",
  "Amenas": "阿梅纳斯",
  "Kiana": "基亚纳",
  "Del Carmen": "德尔卡门",
  "Bastak Airport": "巴斯塔克机场",
  "Tunoshna Airpor": "图诺什纳机场",
  "Iasi": "雅西",
  "Ibadan": "伊巴丹",
  "Isabela": "伊莎贝拉",
  "Ibague": "伊瓦格",
  "Iberia": "伊比利亚",
  "Icabaru": "伊卡巴鲁",
  "Isla de Coche": "科切岛",
  "Cicia": "西西亚",
  "Nieuw Nickerie": "新尼克里",
  "Clarinda": "克拉琳达",
  "Nicaro": "尼卡罗",
  "Cascade": "喀斯喀特",
  "Icy Bay": "冰湾",
  "Ida Grove": "艾达格罗夫",
  "Grangeville": "格兰吉维尔",
  "Indiana": "印第安纳",
  "Indulkana Airpo": "印杜尔卡纳机场",
  "Cristalandia": "克里斯塔兰迪亚",
  "Independence": "独立城",
  "Ile d'Yeu": "约岛",
  "Babimost": "巴比莫斯特",
  "Ie Jima Airport": "伊江岛机场",
  "Riesa": "里萨",
  "Iowa Falls": "艾奥瓦福尔斯",
  "Iffley Airport": "伊夫利机场",
  "Hesa": "赫萨",
  "Innisfail Airpo": "因尼斯费尔机场",
  "Bullhead City": "布尔海德城",
  "Ifuru": "伊富鲁",
  "Matthew Town": "马修镇",
  "Ingeniero Jacob": "工程师哈科巴奇",
  "Igdir": "伊迪尔",
  "Igiugig": "伊久吉格",
  "Ingham Airport": "英厄姆机场",
  "Chigorodo": "奇戈罗多",
  "Manching": "曼兴",
  "Magas": "马加斯",
  "Foz Do Iguacu": "伊瓜苏",
  "Inhaca": "伊尼亚卡",
  "Qishn": "基什恩",
  "Ihosy": "伊胡西",
  "Iran Shahr Airp": "伊兰沙赫尔机场",
  "Inis Meain": "伊尼什曼岛",
  "Ilam": "伊拉姆",
  "Ijui": "伊茹伊",
  "Tehran": "德黑兰",
  "North Wilkesbor": "北威尔克斯伯勒",
  "Iki": "壹岐",
  "Kankakee": "坎卡基",
  "Ikela": "伊克拉",
  "Nikolski": "尼科尔斯基",
  "Inkerman Airpor": "因克曼机场",
  "Tiksi": "季克西",
  "Tamchy": "塔姆奇",
  "Illaga-Papua Is": "伊拉加-巴布亚岛",
  "Lleida": "莱里达",
  "Ilford": "伊尔福德",
  "Wilmington": "威尔明顿",
  "Illesheim Air B": "伊勒斯海姆空军基地",
  "Willmar": "威尔马",
  "Iloilo City": "伊洛伊洛市",
  "Ilo": "伊洛",
  "Kilaguni": "基拉古尼",
  "Port Ellen": "埃伦港",
  "Imbaimadai": "因拜马代",
  "Simikot": "锡米科特",
  "Immokalee": "伊莫卡利",
  "Zemio": "泽米奥",
  "Iron Mountain K": "艾恩芒廷",
  "Inta": "因塔",
  "In Guezzam": "因盖扎姆",
  "Inhambabe": "伊尼扬巴内",
  "Nis": "尼什",
  "Injune Airport": "因詹机场",
  "Wink": "温克",
  "International F": "国际瀑布城",
  "Innamincka Airp": "因纳明卡机场",
  "Inis Oirr": "伊尼希尔岛",
  "Indian Springs": "印第安斯普林斯",
  "Winston Salem": "温斯顿-塞勒姆",
  "Winslow": "温斯洛",
  "Inanwatan Airpo": "伊南瓦坦机场",
  "In Salah": "因萨拉赫",
  "Castletown": "卡斯尔敦",
  "Impfondo": "因普丰多",
  "Inis Mor": "伊尼什莫尔岛",
  "Ilheus": "伊列乌斯",
  "Iowa City": "艾奥瓦城",
  "Ipota": "伊波塔",
  "Isla De Pascua": "复活节岛",
  "Santo Antonio D": "圣安东尼奥-杜伊萨",
  "Ipiales": "伊皮亚莱斯",
  "Ipatinga": "伊帕廷加",
  "Williamsport": "威廉斯波特",
  "Ipiau": "伊皮奥",
  "Perez Zeledon": "佩雷斯塞莱东",
  "Hit": "希特",
  "Circle": "瑟克尔",
  "Ishurdi": "伊舒尔迪",
  "Irece": "伊雷塞",
  "Lockhart River": "洛克哈特河",
  "Nduli": "恩杜利",
  "La Rioja": "拉里奥哈",
  "Kirksville": "柯克斯维尔",
  "Igrim Airport": "伊格里姆机场",
  "Iriona": "伊里奥纳",
  "Birao": "比劳",
  "Sturgis": "斯特吉斯",
  "Santa Isabel Do": "圣伊莎贝尔-杜里约内格罗",
  "St. Mary's": "圣玛丽",
  "Isparta": "伊斯帕尔塔",
  "Isisford Airpor": "伊西斯福德机场",
  "Isla Mujeres Ai": "女人岛机场",
  "Nashik": "纳西克",
  "Nasik": "纳西克",
  "Isla La Tortuga": "拉托尔图加岛",
  "Williston": "威利斯顿",
  "Manistique": "马尼斯蒂克",
  "Wiscasset": "威斯卡西特",
  "Arnavutkoy": "阿尔纳武特科伊",
  "Sulaymaniyah": "苏莱曼尼亚",
  "Wisconsin Rapid": "威斯康星拉皮兹",
  "Itacoatiara": "伊塔科蒂亚拉",
  "Itaituba": "伊泰图巴",
  "Itubera": "伊图贝拉",
  "Cumaru Do Norte": "库马鲁-杜诺尔蒂",
  "Itaperuna": "伊塔佩鲁纳",
  "Itaqui": "伊塔基",
  "Ar Rayyan": "赖扬",
  "Inverell Airpor": "因弗雷尔机场",
  "Masuda": "益田",
  "Iwo Jima Airpor": "硫磺岛机场",
  "Agartala": "阿加尔塔拉",
  "Siliguri": "西里古里",
  "Allahabad": "安拉阿巴德",
  "Belgaum Airport": "贝尔高姆机场",
  "Kailashahar Air": "凯拉萨哈尔机场",
  "Lilabari": "利拉巴里",
  "Jammu": "查谟",
  "Keshod Airport": "克肖德机场",
  "Khowai": "科瓦伊",
  "Pathankot Air F": "伯坦科德空军基地",
  "Kamalpur Airpor": "卡迈勒普尔机场",
  "Silchar": "西尔查尔",
  "Pasighat": "巴昔卡",
  "Aurangabad": "奥兰加巴德",
  "Along Airport": "阿隆机场",
  "Jamshedpur Airp": "贾姆谢德布尔机场",
  "Inyokern": "印多克恩",
  "Wasilla": "瓦西拉",
  "Juiz De Fora": "茹伊斯迪福拉",
  "Ixtepec Airport": "伊斯塔佩克机场",
  "Jalalabad Airpo": "贾拉拉巴德机场",
  "Jabiru Airport": "贾比鲁机场",
  "Jaen": "哈恩",
  "Jaffna": "贾夫纳",
  "Jacobabad": "雅各布阿巴德",
  "Jacmel": "雅克梅勒",
  "Xalapa": "哈拉帕",
  "Yambol": "扬博尔",
  "Jahrom Airport": "贾赫罗姆机场",
  "Jasper": "贾斯珀",
  "Jauja": "豪哈",
  "Araripina": "阿拉里皮纳",
  "La Isabela": "伊莎贝拉",
  "Joacaba": "若阿萨巴",
  "Olathe": "奥拉西",
  "Julia Creek Air": "朱莉娅克里克机场",
  "Jacobina": "雅各比纳",
  "Jacareacanga": "雅卡雷阿坎加",
  "Junction": "章克申",
  "John Day": "约翰迪",
  "Jeongseok Airpo": "正石机场",
  "Jordan": "约旦",
  "Juazeiro Do Nor": "北茹阿泽鲁",
  "Sao Joao Del Re": "圣若昂-德雷",
  "Jeremie": "热雷米",
  "Aasiaat": "阿西亚特",
  "Lower Zambezi N": "下赞比西国家公园",
  "Jequie": "热基耶",
  "Saint Helier": "圣赫利尔",
  "Ashtabula": "阿什塔比拉",
  "Albian Village": "阿尔比恩村",
  "Lahaina": "拉海纳",
  "Shute Harbour A": "舒特港机场",
  "Juina": "瑞纳",
  "Djibouti City": "吉布提市",
  "Ikaria Island": "伊卡里亚岛",
  "Jipijapa": "希皮哈帕",
  "Jijoca de Jeric": "日若卡-迪热里科阿科阿拉",
  "Juanjui": "胡安胡伊",
  "Meru-Kinna": "梅鲁-金纳",
  "Chios Island": "希俄斯岛",
  "Kalymnos Island": "卡林诺斯岛",
  "Janakpur": "贾纳克布尔",
  "Landskrona": "兰斯克鲁纳",
  "Jabalpur Airpor": "贾巴尔普尔机场",
  "Jales": "雅雷斯",
  "Mykonos Island": "米科诺斯岛",
  "Januaria": "雅努阿里亚",
  "Junin": "胡宁",
  "Naxos Island": "纳克索斯岛",
  "Yogyakarta-Java": "日惹-爪哇",
  "Port St Johns": "圣约翰斯港",
  "Yoshkar-Ola": "约什卡尔奥拉",
  "Jolo Airport": "霍洛机场",
  "Njombe": "恩琼贝",
  "Joliet": "乔利埃特",
  "Ji-Parana": "吉帕拉纳",
  "Jaque": "哈克",
  "Kapolei": "卡波莱",
  "Jharsuguda": "贾尔苏古达",
  "Juruena": "茹鲁埃纳",
  "Jaisalmer Airpo": "贾沙梅尔机场",
  "Crete Island": "克里特岛",
  "Skiathos": "斯基亚索斯",
  "Chubut": "丘布特",
  "Jashahor": "贾沙霍尔",
  "Syros Island": "锡罗斯岛",
  "Jatai": "雅塔伊",
  "Santorini Islan": "圣托里尼岛",
  "Astypalaia Isla": "阿斯提帕莱亚岛",
  "Juara": "茹阿拉",
  "San Salvador de": "圣萨尔瓦多-德胡胡伊",
  "Jundah Airport": "君达机场",
  "Jurien Bay Airp": "朱里恩湾机场",
  "Jutigalpa": "胡蒂加尔帕",
  "Manville": "曼维尔",
  "Jwaneng Airport": "朱瓦能机场",
  "Zanjan Airport": "赞詹机场",
  "Jungwon Air Bas": "中原空军基地",
  "Jiroft Airport": "吉罗夫特机场",
  "Jyvaskylan Maal": "于韦斯屈莱",
  "Kasama": "卡萨马",
  "Kamishly": "卡米什利",
  "Kaduna": "卡杜纳",
  "Kaltag": "卡尔塔格",
  "Kuusamo": "库萨莫",
  "Kamarang": "卡马朗",
  "Kaitaia": "凯塔亚",
  "Kauhava": "考哈瓦",
  "Kavanayen Airpo": "卡瓦纳延机场",
  "Kawthoung": "高当",
  "Kalbarri Airpor": "卡尔巴里机场",
  "Kao-Celebes Isl": "高-西里伯斯岛",
  "Kabala": "卡巴拉",
  "Kabalega Falls": "卡巴莱加瀑布",
  "Kalat": "卡拉特",
  "Kribi": "克里比",
  "Kushinagar": "库施那加",
  "Kabwum": "卡布武姆",
  "Kabinda": "卡宾达",
  "Kasungu": "卡松古",
  "Kota Baharu": "哥打巴鲁",
  "Bo": "博",
  "Laut Island": "劳特岛",
  "Streaky Bay Air": "斯特里基贝机场",
  "Kaikoura Airpor": "凯库拉机场",
  "Kasikasima": "卡西卡西马",
  "Collinsville Ai": "柯林斯维尔机场",
  "Kahramanmaras": "卡赫拉曼马拉什",
  "Cengiz Topel Ai": "坚吉兹托佩尔机场",
  "Kings Creek Air": "金斯克里克机场",
  "Galle": "加勒",
  "Masindi": "马辛迪",
  "Kolda": "科尔达",
  "Kandi": "坎迪",
  "Kandahar Airpor": "坎大哈机场",
  "Kendari-Celebes": "肯达里-西里伯斯",
  "N'Djole": "恩乔莱",
  "Kardla": "凯尔德拉",
  "Huvadhu Atoll": "胡瓦杜环礁",
  "Ndende": "恩登代",
  "Kadhdhoo": "卡杜胡",
  "Kandrian": "坎德里安",
  "Nakhon Pathom": "佛统",
  "Skardu": "斯卡都",
  "Kadugli": "卡杜格利",
  "Kerki": "克尔基",
  "Kasenga": "卡森加",
  "Kaedi": "卡埃迪",
  "Kelle": "凯勒",
  "Kepi-Papua Isla": "凯皮-巴布亚岛",
  "Kenema": "凯内马",
  "Odienne": "奥迭内",
  "Nepalgunj": "尼泊尔根戈",
  "Kebar-Papua Isl": "克巴尔-巴布亚岛",
  "Kengtung": "景栋",
  "Keekorok": "基科罗克",
  "Keewaywin": "基韦温",
  "Kericho": "凯里乔",
  "Kiffa": "基法",
  "Cloudbreak Vill": "云歇村",
  "Kalkgurung Airp": "卡