const airportNamesContinuation = {
  "Fort Leonard Wo": "伦纳德伍德堡",
  "Tabora": "塔波拉",
  "Tumbes": "通贝斯",
  "Statesboro": "斯泰茨伯勒",
  "Nuku'alofa": "努库阿洛法",
  "Tambov": "坦波夫",
  "Tshabong": "察邦",
  "Tennant Creek": "滕南特克里克",
  "Tucumcari": "图克姆卡里",
  "Tulcea": "图尔恰",
  "Tchibanga": "奇班加",
  "Tuscaloosa": "塔斯卡卢萨",
  "Tehuacan Airpor": "特瓦坎机场",
  "Tumaco": "图马科",
  "Taba": "塔巴",
  "Tacna": "塔克纳",
  "Thoothukkudi": "杜蒂戈林",
  "Truth Or Conseq": "真理或后果城",
  "Homeward": "霍姆沃德",
  "Tocumwal Airpor": "托克姆沃尔机场",
  "Tabas": "塔巴斯",
  "Tengchong": "腾冲",
  "Tandag Airport": "坦达格机场",
  "Tadjoura": "塔朱拉",
  "Taldy Kurgan": "塔尔迪库尔干",
  "Tandil": "坦迪尔",
  "Toledo": "托莱多",
  "Theodore Airpor": "西奥多机场",
  "Welverdiend": "韦尔弗丁德",
  "Trat Airport": "达叻机场",
  "Tela": "特拉",
  "Teterboro": "泰特伯勒",
  "Telemaco Borba": "特莱马库博尔巴",
  "Thisted": "蒂斯泰兹",
  "Tebessi": "泰贝西",
  "Telfer Airport": "特尔弗机场",
  "Tezu": "德祖",
  "Telupid": "特鲁必",
  "Temora Airport": "特莫拉机场",
  "Corlu": "乔尔卢",
  "Lajes": "拉日什",
  "Tete": "太特",
  "Manapouri Airpo": "玛纳普里机场",
  "Teruel": "特鲁埃尔",
  "Telluride": "特柳赖德",
  "Tingeyri": "辛盖里",
  "Tezpur Airport": "提斯普尔机场",
  "Tefe": "特菲",
  "Tufi": "图菲",
  "Teofilo Otoni": "特奥菲卢奥托尼",
  "Telefomin": "特莱福明",
  "Tenerife Island": "特内里费岛",
  "Taftan": "塔夫坦",
  "Tanjung Manis": "丹绒马尼斯",
  "Kuala Terenggan": "瓜拉丁加奴",
  "Tongoa Island": "通戈阿岛",
  "Tingo Maria": "廷戈玛丽亚",
  "Taganrog": "塔甘罗格",
  "Targu Mures": "特尔古穆列什",
  "Latrobe Valley": "拉特罗布谷",
  "Tangara Da Serr": "坦加拉-达塞拉",
  "Touggourt": "图古尔特",
  "Tanga": "坦噶",
  "Tegucigalpa": "特古西加尔巴",
  "Targovishte": "特尔戈维什特",
  "Tuxtla Gutierre": "图斯特拉-古铁雷斯",
  "Tullahoma": "塔拉霍马",
  "Thaba-Tseka": "塔巴-采卡",
  "Tchien": "奇恩",
  "Teresina": "特雷西纳",
  "Biloela": "比洛埃拉",
  "Taharoa": "塔哈罗阿",
  "Tichitt": "提希特",
  "Thakhek": "他曲",
  "Tachileik": "大其力",
  "Thompson Falls": "汤普森福尔斯",
  "Trollhattan": "特罗尔海坦",
  "Thorshofn": "索尔斯港",
  "Sukhothai Airpo": "素可泰机场",
  "Tamchakett": "塔姆查凯特",
  "Thule": "图勒",
  "Turukhansk": "图鲁汉斯克",
  "Thohoyandou": "托霍延杜",
  "Tahoua": "塔瓦",
  "Tibu": "蒂武",
  "Tiaret": "提亚雷特",
  "Taif Airport": "塔伊夫机场",
  "Tarin Kowt": "塔林科特",
  "Tijuana": "蒂华纳",
  "Timika-Papua Is": "蒂米卡-巴布亚岛",
  "Tindouf": "廷杜夫",
  "Tilin": "提林",
  "Tinian Island": "天宁岛",
  "Tirupati": "蒂鲁帕蒂",
  "Timaru Airport": "蒂马鲁机场",
  "Titusville": "泰特斯维尔",
  "Tidjikja": "提季克贾",
  "Tari": "塔里",
  "Tarija": "塔里哈",
  "Karinmunbesar I": "卡林蒙贝萨尔岛",
  "Tanta-Tabalong-": "坦塔-塔巴隆",
  "Tajima": "但马",
  "Trujillo": "特鲁希略",
  "Tokat": "托卡特",
  "Tres Lagoas": "特雷斯Lagoas",
  "Tanjung Pandan-": "丹戎潘丹",
  "Tanjung Selor-B": "丹戎塞洛-婆罗洲",
  "Kulyab": "库利亚布",
  "Thanjavur": "坦贾武尔",
  "Talkeetna": "托基特纳",
  "Tiko": "蒂科",
  "Sekondi-Takorad": "塞康第-塔科拉迪",
  "Truckee": "特拉基",
  "Takhli Airport": "达欺里机场",
  "Tok": "托克",
  "Weno Island": "韦诺岛",
  "Tlokoeng": "特洛科恩",
  "Thakurgaon": "塔库尔冈",
  "Tokushima": "德岛",
  "Tak Airport": "达府机场",
  "Turku": "图尔库",
  "Tatakoto": "塔塔科托",
  "Tekin": "泰金",
  "Takaroa Airport": "塔卡罗阿机场",
  "Tokoroa": "托科罗阿",
  "Teller": "特勒",
  "Tarbela": "塔贝拉",
  "Toluca": "托卢卡",
  "Tuli Lodge": "图利小屋",
  "Tallahassee": "塔拉哈西",
  "Takotna": "塔科特纳",
  "Talakan Airport": "塔拉坎机场",
  "Tallinn": "塔林",
  "Tlemcen": "特莱姆森",
  "Tulare": "图莱里",
  "Tolu": "托卢",
  "Talca": "塔尔卡",
  "Tifton": "蒂夫顿",
  "Waikabubak-Sumb": "怀卡布巴克-松巴哇",
  "Timbedra": "廷贝德拉",
  "Tame": "塔梅",
  "Tomanggong": "托曼贡",
  "Tanah Merah-Pap": "丹那美拉-巴布亚",
  "Tumling Tar": "图姆林塔尔",
  "Termez": "铁尔梅兹",
  "Toamasina": "图阿马西纳",
  "Tumeremo": "图梅雷莫",
  "Tambao": "坦巴奥",
  "Tamanrasset": "塔曼拉塞特",
  "Tamworth": "塔姆沃思",
  "Timimoun": "提米蒙",
  "Thames Aerodrom": "泰晤士机场",
  "Tanah Grogot-Bo": "丹那格罗戈特-婆罗洲",
  "Tin City": "锡城",
  "New Tanegashima": "新种子岛",
  "Toussus-le-Nobl": "图苏勒诺布勒",
  "Satna Airport": "萨特纳机场",
  "Tanjung Pinang-": "丹戎槟榔",
  "Ternopil": "捷尔诺波尔",
  "Twentynine Palm": "二十九棕榈村",
  "Stung Treng": "上丁",
  "Torrance": "托伦斯",
  "Toccoa": "托科阿",
  "Pulau Tioman": "刁曼岛",
  "Tozeur": "托泽尔",
  "Tomsk": "托木斯克",
  "Togiak Village": "托贾克村",
  "Troy": "特洛伊",
  "Timbuktu": "廷巴克图",
  "Coto Brus": "科托布鲁斯",
  "Tocopilla": "托科皮亚",
  "Torrington": "托灵顿",
  "Tromso": "特罗姆瑟",
  "Totness": "托特尼斯",
  "Tobolsk": "托博尔斯克",
  "Tarapoa": "塔拉波阿",
  "Taiping": "太平",
  "Tonopah": "托诺帕",
  "Tapini": "塔皮尼",
  "Taplejung": "塔普勒琼",
  "Tapak Tuan-Suma": "塔帕克图安-苏门答腊",
  "Temple": "坦普尔",
  "Tiputini": "蒂普蒂尼",
  "Tarapoto": "塔拉波托",
  "Tepic": "特皮克",
  "Tom Price": "汤姆普赖斯",
  "Trapani": "特拉帕尼",
  "Tikapur": "蒂卡普尔",
  "Al Habbaniyah": "哈巴尼亚",
  "Tarko-Sale": "塔尔科萨列",
  "Taloqan": "塔卢坎",
  "Trepell Airport": "特雷佩尔机场",
  "Waha-Tomea Isla": "瓦哈-托梅阿岛",
  "Tres Esquinas": "特雷斯埃斯基纳斯",
  "Tarama Airport": "多良间机场",
  "Turbo": "图尔沃",
  "Torreon": "托雷翁",
  "Trondheim": "特隆赫姆",
  "Balemartine": "巴勒马丁",
  "Torp": "托尔普",
  "Tauranga": "陶朗加",
  "Tarakan Island": "打拉根岛",
  "Terrell": "特勒尔",
  "Taree": "塔里",
  "Tarauaca": "塔劳阿卡",
  "Trincomalee": "亭可马里",
  "Trieste": "的里雅斯特",
  "Tarawa": "塔拉瓦",
  "Trenton": "特伦顿",
  "Tororo": "托罗罗",
  "Tiruchirappally": "蒂鲁吉拉伯利",
  "Taisha": "泰沙",
  "Treviso": "特雷维索",
  "Tsushima": "对马",
  "Tamuin": "塔穆因",
  "Taos": "陶斯",
  "Tehachapi": "特哈查比",
  "Timisoara": "蒂米什瓦拉",
  "Trang Airport": "董里机场",
  "Townsville": "汤斯维尔",
  "Santan-Borneo I": "桑坦-婆罗洲岛",
  "Tasikmalaya-Jav": "打横-爪哇",
  "Tan Tan": "坦坦",
  "Arbatax": "阿尔巴塔克斯",
  "Taltal": "塔尔塔尔",
  "Sango-Ternate I": "桑戈-特尔纳特岛",
  "Tartagal": "塔尔塔加尔",
  "Thumrait": "塞姆赖特",
  "Britton": "布里顿",
  "Roxana": "罗克萨纳",
  "Tanah Toraja-Ce": "塔纳托拉查-西里伯斯",
  "Truscott Mungal": "特拉斯科特-蒙加兰尼",
  "Tulcan": "图尔坎",
  "Tubuai Airport": "土布艾机场",
  "San Miguel de T": "圣米格尔-德图库曼",
  "Tambacounda": "坦巴昆达",
  "Tuguegarao City": "土格加劳市",
  "Turaif Domestic": "图赖夫国内机场",
  "Maji": "马吉",
  "Turbat": "图尔伯特",
  "Tumut Airport": "图马特机场",
  "Tunis": "突尼斯",
  "Taupo": "陶波",
  "Tupelo": "图珀洛",
  "Tougan": "图冈",
  "Tucurui": "图库鲁伊",
  "Tabuk Airport": "塔布克机场",
  "Tucupita": "图库皮塔",
  "Traverse City": "特拉弗斯城",
  "Thief River Fal": "西夫里弗福尔斯",
  "Thomasville": "托马斯维尔",
  "South Lake Taho": "南太浩湖",
  "Matei": "马泰",
  "Dawei": "土瓦",
  "Toowoomba Airpo": "图文巴机场",
  "Taylor": "泰勒",
  "Twin Falls": "特温福尔斯",
  "Tawau": "斗湖",
  "Twitzel": "特威泽尔",
  "Tlaxcala Airpor": "特拉斯卡拉机场",
  "Teixeira De Fre": "特谢拉-迪弗雷塔斯",
  "Taichung City": "台中市",
  "Texarkana": "特克萨卡纳",
  "Atinjoe-Papua I": "阿廷乔-巴布亚岛",
  "Tibooburra Airp": "蒂布布拉机场",
  "Tynda": "藤达",
  "Torsby Airport": "图什比机场",
  "Thylungra Airpo": "锡隆格拉机场",
  "Capitan Montes": "蒙特斯上尉镇",
  "Staniel Cay Air": "斯坦尼尔礁机场",
  "Tyler": "泰勒",
  "Treinta y Tres": "特雷因塔伊特雷斯",
  "Caro": "卡罗",
  "Tuzla": "图兹拉",
  "Taszar": "陶萨尔",
  "Trabzon": "特拉布宗",
  "Suai": "苏艾",
  "Narsarsuaq": "纳萨尔苏瓦克",
  "Luau": "卢奥",
  "Andersen": "安徒生",
  "Uaxactun": "瓦哈克通",
  "Ubon Ratchathan": "乌汶叻差他尼",
  "Ubrub-Papua Isl": "乌布鲁布-巴布亚岛",
  "Ubatuba": "乌巴图巴",
  "Kalumburu Airpo": "卡伦布鲁机场",
  "Lutsk": "卢茨克",
  "Buchanan": "布坎南",
  "Union City": "联合市",
  "Uchiza": "乌奇萨",
  "Uden": "乌登",
  "Uzhhorod": "乌日霍罗德",
  "Udine": "乌迪内",
  "Queenstown Airp": "皇后镇机场",
  "Kumejima Airpor": "久米岛机场",
  "Waukesha": "沃基肖",
  "Bulgan": "布尔干",
  "Umnugobitour": "乌姆努戈壁游",
  "Uherske Hradist": "乌赫尔堡",
  "Quy Nohn": "归仁",
  "Utila Island": "乌蒂拉岛",
  "Ust-Ilimsk": "乌斯季伊利姆斯克",
  "Quillayute": "奎拉尤特",
  "Quion Hill": "奎昂山",
  "Quirindi Airpor": "奎林迪机场",
  "Ukiah": "尤凯亚",
  "Ust Kamenogorsk": "乌斯季卡缅诺戈尔斯克",
  "Sevastopol": "塞瓦斯托波尔",
  "Quakertown": "夸克敦",
  "Nuku": "努库",
  "Ust-Kut": "乌斯季库特",
  "San Julian": "圣胡利安",
  "Ulgii Mongolei": "乌列盖蒙古",
  "Al-'Ula": "欧拉",
  "Lensk": "连斯克",
  "New Ulm": "新乌尔姆",
  "Ulan Bator": "乌兰巴托",
  "Quilpie Airport": "奎尔皮机场",
  "Tulua": "图卢阿",
  "Gulu": "古卢",
  "Ulyanovsk": "乌里扬诺夫斯克",
  "Ulusaba": "乌卢萨巴",
  "Maisi": "迈西",
  "Quince Mil": "金塞米尔",
  "Summit": "萨米特",
  "Woomera": "伍默拉",
  "Ust-Maya": "乌斯季马亚",
  "Umiat": "乌米亚特",
  "Umuarama": "乌穆阿拉马",
  "Sumy": "苏梅",
  "Una": "乌纳",
  "Konduz Airport": "昆都士机场",
  "Qacha's Nek": "加查斯内克",
  "Kiunga": "基永加",
  "Union Island": "尤宁岛",
  "Ranong Airport": "拉廊机场",
  "Mururoa Atoll": "穆鲁罗阿环礁",
  "Buol-Celebes Is": "布奥尔-西里伯斯岛",
  "Sewanee": "塞沃尼",
  "Upala": "乌帕拉",
  "Licenciado y Ge": "伊格纳西奥·洛佩斯·拉永将军",
  "Hawi": "哈威",
  "Upavon": "阿帕文",
  "Ebermannstadt": "埃伯曼施塔特",
  "Kuressaare": "库雷萨雷",
  "Uray": "乌拉伊",
  "Uriman Airport": "乌里曼机场",
  "Urrao": "乌劳",
  "Kursk": "库尔斯克",
  "Guriat Domestic": "古里亚特国内机场",
  "Ushuahia": "乌斯怀亚",
  "Mabaruma": "马巴鲁马",
  "Usharal": "乌沙拉尔",
  "Usinsk": "乌辛斯克",
  "Ulsan": "蔚山",
  "Usak": "乌沙克",
  "Sancti Spiritus": "圣斯皮里图斯",
  "St Augustine": "圣奥古斯丁",
  "Coron": "科隆",
  "Mutare Airport": "穆塔雷机场",
  "Muttaburra Airp": "穆塔布拉机场",
  "Bultfontein": "比尔特方丹",
  "Quthing": "古廷",
  "Tunica": "图尼卡",
  "Utopia Creek": "乌托邦溪",
  "Uttaradit": "程逸",
  "Ust-Tsylma": "乌斯季齐利马",
  "Mthatha": "姆萨塔",
  "Bugulma": "布古利马",
  "Ulan Ude": "乌兰乌德",
  "Kuparuk": "库帕鲁克",
  "Baruun Urt Airp": "巴伦乌尔特机场",
  "Yuzhno-Sakhalin": "南萨哈林斯克",
  "Uvalde": "尤瓦尔迪",
  "Ouvea": "乌韦阿",
  "Vieux Fort": "维约堡",
  "El Kharga Airpo": "哈里杰机场",
  "Nyala": "尼亚拉",
  "Quijarro": "基哈罗",
  "Curuzu Cuatia": "库鲁苏夸蒂亚",
  "Cloppenburg": "克洛彭堡",
  "Vallegrande": "大峡谷镇",
  "Vanimo Airport": "瓦尼莫机场",
  "Chevak": "切瓦克",
  "Valenca": "瓦伦萨",
  "Vatukoula": "瓦图库拉",
  "Vava'u Island": "瓦瓦乌岛",
  "Aeng": "昂",
  "Bokpyinn": "博克平",
  "Brescia": "布雷西亚",
  "Vanua Balavu": "瓦努阿巴拉武",
  "Visby": "维斯比",
  "Can Tho": "芹苴",
  "Victoria River": "维多利亚河",
  "Venezia": "威尼斯",
  "Vichadero": "维查德罗",
  "Carora": "卡罗拉",
  "Con Ong": "昆翁",
  "Leirin Airport": "莱林机场",
  "Vitoria Da Conq": "维多利亚-达孔基斯塔",
  "El Hierro Islan": "耶罗岛",
  "Dong Hoi": "洞海",
  "Vidalia": "维达利亚",
  "Valle de La Pas": "拉巴斯谷",
  "Villa Dolores": "比利亚多洛雷斯",
  "Vijayanagar Aer": "维杰亚纳加尔机场",
  "Valdez": "瓦尔迪兹",
  "Venetie": "韦纳蒂",
  "Vijayawada Airp": "维杰亚瓦达机场",
  "Vologda": "沃洛格达",
  "Vigo": "维戈",
  "Villa Garzon": "比利亚加尔松",
  "Saurimo": "绍里木",
  "Vilhelmina Airp": "威廉敏娜机场",
  "Van Horn": "范霍恩",
  "Vahitahi": "瓦希塔希",
  "Videira": "维代拉",
  "Vicenza": "维琴察",
  "El Vigia": "埃尔维希亚",
  "Vinh": "荣市",
  "Dakhla": "达赫拉",
  "Vinnitsa": "文尼察",
  "Payerne": "帕耶讷",
  "Viqueque": "维克克",
  "Visalia": "维塞利亚",
  "Alava": "阿拉瓦",
  "Vitoria": "维多利亚",
  "Abingdon": "阿宾登",
  "Rach Gia": "迪石",
  "Vicksburg": "维克斯堡",
  "Vorkuta": "沃尔库塔",
  "Friendly": "弗兰德利",
  "Vandalia": "范代利亚",
  "Villa Gesell": "格塞尔镇",
  "Zavetnoe Airpor": "扎韦特诺耶机场",
  "Villamontes": "比亚蒙特斯",
  "Vila Rica": "维拉里卡",
  "Vallenar": "瓦列纳尔",
  "Valesdir": "瓦莱斯迪尔",
  "Velikiye Luki": "大卢基",
  "Villa Reynolds": "比利亚雷诺兹",
  "Baimuru": "拜穆鲁",
  "Saravane": "沙拉湾",
  "Vangaindrano": "万盖德拉努",
  "Vilnius": "维尔纽斯",
  "Vanrook Station": "凡鲁克站",
  "Ventspils": "文茨皮尔斯",
  "Vilanculo": "维兰库洛",
  "Van Nuys": "范奈斯",
  "Vodochoky": "沃多霍迪",
  "Volgograd": "伏尔加格勒",
  "Voinjama": "沃因贾马",
  "Camp Douglas": "道格拉斯营",
  "Nea Anchialos": "新安基亚洛斯",
  "Votuporanga": "沃图波兰加",
  "Voronezh": "沃罗涅日",
  "Ngiva": "恩吉瓦",
  "Vopnafjordur": "沃普纳菲厄泽",
  "Chimoio": "希莫尤",
  "Vieques Island": "别克斯岛",
  "Vero Beach": "维罗比奇",
  "Virac": "维拉克",
  "Vredendal": "弗里登达尔",
  "Varandey Airpor": "瓦兰杰伊机场",
  "Vila Real Airpo": "雷阿尔城机场",
  "Matanzas": "马坦萨斯",
  "Vyrburg": "弗赖堡",
  "Lavras": "拉夫拉斯",
  "Villahermosa": "比亚埃尔莫萨",
  "Viseu Airport": "维塞乌机场",
  "Luhansk": "卢甘斯克",
  "Kennewick": "肯纳威克",
  "Shravasti": "舍卫城",
  "Vitebsk": "维捷布斯克",
  "Vatulele": "瓦图莱莱",
  "Vung Tau": "头顿",
  "Luxeuil": "吕克瑟伊",
  "Valentine": "瓦伦丁",
  "Las Tunas": "拉斯图纳斯",
  "Visakhapatnam": "维沙卡帕特南",
  "Velikiy Ustyug": "大乌斯秋格",
  "Villavicencio": "比亚维森西奥",
  "Illizi": "伊利齐",
  "Sao Pedro": "圣佩德罗",
  "Vryheid": "弗里海德",
  "Vilyuisk": "维柳伊斯克",
  "Wales": "威尔士",
  "Wadi Al Dawasir": "达瓦西尔干河",
  "Waana": "瓦纳",
  "Wahpeton": "沃帕顿",
  "Wallops Island": "瓦勒普斯岛",
  "Wabo": "瓦博",
  "Alto Palena": "上帕莱纳",
  "Waris-Papua Isl": "瓦里斯-巴布亚岛",
  "Wave Hill Airpo": "波浪山机场",
  "Waynesburg": "韦恩斯堡",
  "Warwick Airport": "沃里克机场",
  "Seram Island": "斯兰岛",
  "Schleswig Airpo": "石勒苏益格机场",
  "Wapenamanda Air": "瓦佩纳曼达机场",
  "Beaver": "比弗",
  "Big Rapids": "大急流城",
  "Boulder": "博尔德",
  "Wilkes-Barre": "威尔克斯-巴里",
  "Chaiten": "柴滕",
  "Chandalar Lake": "钱达拉尔湖",
  "Wondai Airport": "旺代机场",
  "Winder": "温德",
  "Wagethe-Papua I": "瓦格特-巴布亚岛",
  "Wee Waa Airport": "威瓦机场",
  "Wexford": "韦克斯福德",
  "Frenchville": "弗伦奇维尔",
  "Bahawalnagar": "巴哈瓦尔讷格尔",
  "Warrangal": "瓦朗加尔",
  "Walgett Airport": "沃尔格特机场",
  "Winchester": "温彻斯特",
  "Waingapu-Sumba": "瓦英阿普-松巴",
  "Wangaratta Airp": "旺加拉塔机场",
  "Whakatane Airpo": "法卡塔尼机场",
  "Franz Josef Aer": "弗朗茨约瑟夫机场",
  "Whalsay": "沃尔赛",
  "Wharton": "沃顿",
  "Wick": "威克",
  "Wiesbaden": "威斯巴登",
  "Waiheke Reeve A": "怀希基里夫机场",
  "Nairobi": "内罗毕",
  "Winton Airport": "温顿机场",
  "Wilcannia Airpo": "威尔坎尼亚机场",
  "Wairoa": "怀罗阿",
  "Wittenoom Airpo": "威特努姆机场",
  "Tuxpan Airport": "图斯潘机场",
  "Wajir": "瓦吉尔",
  "Wonju": "原州",
  "Wanaka Airport": "瓦纳卡机场",
  "Warracknabeal A": "沃拉克纳比尔机场",
  "Wakkanai": "稚内",
  "Abaco I Walker": "阿巴科岛沃克礁",
  "Miles Airport": "迈尔斯机场",
  "Walaha": "瓦拉哈",
  "Waterloo Airpor": "滑铁卢机场",
  "West Angelas Ai": "西安吉拉斯机场",
  "Willows": "威洛斯",
  "Warrnambool Air": "瓦南布尔机场",
  "Winnemucca": "温尼马卡",
  "Mount Keith Air": "基思山机场",
  "White Mountain": "怀特芒廷",
  "Mananara Nord": "马纳纳拉北部",
  "Wamena-Papua Is": "瓦梅纳-巴布亚岛",
  "Napakiak": "纳帕基亚克",
  "Wunnumin Lake": "万努明湖",
  "Naga": "那牙",
  "Windorah Airpor": "温多拉机场",
  "Nawabash": "纳瓦布沙阿",
  "Wonenara": "沃内纳拉",
  "Bergen Op Zoom": "贝亨奥普佐姆",
  "Wollongong Airp": "卧龙岗机场",
  "Wondoola Airpor": "旺杜拉机场",
  "Wang-an": "望安",
  "Willow": "威洛",
  "Puerto Aysen": "艾森港",
  "Pincher Creek": "平彻克里克",
  "Wrotham Park Ai": "罗瑟姆公园机场",
  "Porvenir": "波韦尼尔",
  "Puerto Williams": "威廉姆斯港",
  "Warner Robins": "华纳罗宾斯",
  "Whangarei Airpo": "璜加雷机场",
  "Wrangell": "兰格尔",
  "Wrightstown": "赖茨敦",
  "Worland": "沃兰",
  "Wroclaw": "弗罗茨瓦夫",
  "Warton": "沃顿",
  "Westray": "韦斯特雷",
  "Weerawila": "维拉维拉",
  "White Sands": "白沙",
  "Cape Sarichef": "萨里切夫角",
  "Shirley": "雪莉",
  "Wushan": "巫山",
  "South Naknek": "南纳克内克",
  "Washabo": "瓦沙博",
  "Westerly": "韦斯特利",
  "Wasu": "瓦苏",
  "Westport Airpor": "韦斯特波特机场",
  "Wellcamp": "韦尔坎普",
  "West End": "西区",
  "Noatak": "诺阿塔克",
  "Waddington": "沃丁顿",
  "Fatima Mission": "法蒂玛米申",
  "Whitianga Airpo": "怀蒂昂格机场",
  "Wudinna Airport": "伍丁纳机场",
  "Murrin Murrin A": "穆林穆林机场",
  "Wiluna Airport": "威尔卢纳机场",
  "Watsonville": "沃森维尔",
  "Waterville": "沃特维尔",
  "Wilhelmshaven": "威廉港",
  "Wildwood": "怀尔德伍德",
  "Woodward": "伍德沃德",
  "Newtok": "纽托克",
  "West Wyalong": "西怀厄朗",
  "Wethersfield": "韦瑟斯菲尔德",
  "Whyalla": "怀阿拉",
  "Yengema": "延盖马",
  "Wyndham Airport": "温德姆机场",
  "West Yellowston": "西黄石",
  "Evreux": "埃夫勒",
  "Chapeco": "沙佩科",
  "Aribinda": "阿里宾达",
  "Angers": "昂热",
  "Bearskin Lake": "熊皮湖",
  "Birjand": "比尔詹德",
  "Chatham-Kent": "查塔姆-肯特",
  "Colac Airport": "科拉克机场",
  "Compiegne": "贡比涅",
  "Charleville-Mez": "沙勒维尔-梅济耶尔",
  "Djibo": "吉博",
  "Les Moeres": "莱莫埃雷斯",
  "Xingcheng Air B": "兴城空军基地",
  "Gaoua": "加瓦",
  "Gorom-Gorom": "戈罗姆戈罗姆",
  "Xangongo": "商贡戈",
  "Kangiqsualujjua": "坎吉克苏阿尔朱阿克",
  "Cahors": "卡奥尔",
  "Mangla": "曼格拉",
  "Xieng Khouang": "川圹",
  "Kasabonika": "卡萨博尼卡",
  "Laon-Chambry": "拉昂-尚布里",
  "Lemwerder": "莱姆韦德",
  "Mallacoota Airp": "马拉库塔机场",
  "Mahendranagar": "马亨德拉讷格尔",
  "Manihi Airport": "马尼希机场",
  "Masasi": "马萨西",
  "Mont-de-Marsan": "蒙德马桑",
  "Annecy": "阿讷西",
  "Montauban": "蒙托邦",
  "Comayagua": "科马亚瓜",
  "Pine Ridge": "派恩里奇",
  "Quepos": "克波斯",
  "Jerez de la For": "赫雷斯-德拉弗龙特拉",
  "Sebba": "塞巴",
  "Rochefort": "罗什福尔",
  "Thargomindah Ai": "萨戈明达机场",
  "Tadoule Lake": "塔杜勒湖",
  "Taroom Airport": "塔鲁姆机场",
  "Tara Airport": "塔拉机场",
  "Hassleholm": "海斯勒霍尔姆",
  "Ye": "耶城",
  "Yellow River Mi": "黄河任务",
  "Anahim Lake": "阿纳希姆湖",
  "Arctic Bay Airp": "北极湾机场",
  "Cat Lake": "卡特湖",
  "Fort Frances": "弗朗西斯堡",
  "Chillan": "奇廉",
  "Yakutat": "亚库塔特",
  "Alert Bay": "阿勒特湾",
  "Yap Island": "雅浦岛",
  "Yasawa Island": "亚萨瓦岛",
  "Attawapiskat": "阿塔瓦皮斯卡特",
  "Kattiniq": "卡蒂尼克",
  "Winnipeg": "温尼伯",
  "Angling Lake": "安格灵湖",
  "St. Anthony": "圣安东尼",
  "Tofino": "托菲诺",
  "Banff": "班夫",
  "Kugaaruk": "库加鲁克",
  "Baie-Comeau": "贝科莫",
  "Uranium City": "铀城",
  "Black Tickle": "布莱克蒂克尔",
  "Baker Lake": "贝克湖",
  "Campbell River": "坎贝尔里弗",
  "Bob Quinn Lake": "鲍勃奎因湖",
  "Brandon": "布兰登",
  "Brochet": "布罗谢",
  "Berens River": "贝伦斯河",
  "Lourdes-De-Blan": "卢尔德-德布兰克-萨布隆",
  "Bonnyville": "邦尼维尔",
  "Cambridge Bay": "剑桥湾",
  "Cornwall": "康沃尔",
  "Nanaimo": "纳奈莫",
  "Miramichi": "米拉米奇",
  "Colville Lake": "科尔维尔湖",
  "Charlo": "夏洛",
  "St Catharines": "圣凯瑟琳斯",
  "Kugluktuk": "库格卢克图克",
  "Chetwynd": "切特温德",
  "Cross Lake": "克罗斯莱克",
  "Chesterfield In": "切斯特菲尔德因莱特",
  "Coronation": "科罗内申",
  "Chilliwack": "奇利瓦克",
  "Clyde River": "克莱德河",
  "Fairmont Hot Sp": "费尔蒙特温泉",
  "Dawson City": "道森市",
  "Burwash": "伯沃什",
  "Town of Princet": "普林斯顿镇",
  "Digby": "迪格比",
  "Dease Lake": "迪斯湖",
  "Ross River": "罗斯河",
  "Dauphin": "多芬",
  "Dolbeau-St-Feli": "多尔博-圣费利西安",
  "Nain": "内恩",
  "Dawson Creek": "道森克里克",
  "Bloodvein River": "布拉德韦恩河",
  "Bar River": "巴尔河",
  "Yecheon Airport": "醴泉机场",
  "Asalouyeh": "阿萨卢耶",
  "Arviat": "阿尔维亚特",
  "Elliot Lake": "埃利奥特湖",
  "Manitowaning": "马尼图瓦宁",
  "Estevan": "埃斯特万",
  "Yeovil": "约维尔",
  "Fort Severn": "塞文堡",
  "Yasouj Airport": "亚苏季机场",
  "Edson": "埃德森",
  "Amos": "阿默斯",
  "Fort Albany": "奥尔巴尼堡",
  "Brantford": "布兰特福德",
  "Forestville": "福雷斯特维尔",
  "Fort Hope": "霍普堡",
  "Suncor Energy S": "森科能源",
  "Wekweeti": "韦奎提",
  "Flin Flon": "弗林弗伦",
  "Fort Resolution": "决心堡",
  "Fort Simpson": "辛普森堡",
  "St. Lewis": "圣刘易斯",
  "Texada": "特克萨达",
  "Goderich": "戈德里奇",
  "Golden": "戈尔登",
  "Fort Good Hope": "好望堡",
  "La Grande Rivie": "拉格兰德里维耶尔",
  "Gimli": "吉姆利",
  "Gods Lake Narro": "戈兹莱克纳罗斯",
  "Iles-de-la-Made": "马德莱娜群岛",
  "Igloolik": "伊格卢利克",
  "Havre St-Pierre": "阿弗尔圣皮埃尔",
  "Kuujjuarapik": "库朱阿拉皮克",
  "Gillam": "吉勒姆",
  "Grise Fiord": "格赖斯峡湾",
  "Port Hope Simps": "霍普辛普森港",
  "Hudson Bay": "哈德逊湾",
  "Dryden": "德莱顿",
  "Hope": "霍普",
  "Hearst": "赫斯特",
  "Ulukhaktok": "乌卢哈克托克",
  "Hornepayne": "霍恩佩恩",
  "Hopedale": "霍普代尔",
  "Poplar Hill": "波普勒希尔",
  "Chevery": "谢弗里",
  "Atikokan": "阿蒂科肯",
  "St-Augustin": "圣奥古斯丁",
  "Ivujivik": "伊武吉维克",
  "Pond Inlet": "庞德因莱特",
  "Fort Liard": "利亞德堡",
  "Fort St. James": "圣詹姆斯堡",
  "St Jean": "圣让",
  "Samjiyon": "三池渊",
  "Collins Bay": "柯林斯湾",
  "Kitchener": "基奇纳",
  "Kangirsuk": "坎吉尔苏克",
  "Key Lake": "基莱克",
  "Yankton": "扬克顿",
  "Yuksekova": "尤克塞科瓦",
  "Chisasibi": "奇萨西比",
  "Kirkland Lake": "柯克兰湖",
  "Kindersley": "金德斯利",
  "Toronto": "多伦多",
  "Lac La Biche": "拉拉克拉比什",
  "Kimmirut": "金米鲁特",
  "Chapleau": "沙普洛",
  "Whati": "瓦提",
  "Lansdowne House": "兰斯当豪斯",
  "Ylivieska Airpo": "上维耶斯卡机场",
  "Meadow Lake": "梅多莱克",
  "Barrie-Orillia": "巴里-奥里利亚",
  "Yelahanka": "耶拉汉卡",
  "La Tuque": "拉图克",
  "Leaf Rapids": "利夫拉皮兹",
  "Alert": "阿勒特",
  "Yevlakh": "叶夫拉赫",
  "Langley": "兰利",
  "Mayo": "梅奥",
  "Matane": "马塔讷",
  "Manitouwadge": "马尼图瓦奇",
  "Mary's Harbour": "玛丽港",
  "Moose Jaw": "穆斯乔",
  "Mys Kamennyi": "卡缅内角",
  "Charlevoix": "夏利华",
  "Makkovik": "马科维克",
  "Yurimaguas": "尤里马瓜斯",
  "Chibougamau": "希布加莫",
  "Maniwaki": "马尼瓦基",
  "Natashquan": "纳塔什昆",
  "Yenbo Airport": "延布机场",
  "Wemindji": "韦明吉",
  "Gatineau": "加蒂诺",
  "Norway House": "挪威豪斯",
  "Hudson's Hope": "哈德逊霍普",
  "Points North La": "北方点着陆场",
  "Matagami": "马塔加米",
  "Nejanilini Lake": "内贾尼利尼湖",
  "North Spirit La": "北灵湖",
  "Nemiscau": "内米斯考",
  "Snap Lake": "斯纳普湖",
  "Ekati": "埃卡蒂",
  "Cold Lake": "冷湖",
  "Ogoki Post": "奥戈基邮政",
  "Oxford House": "牛津豪斯",
  "High Level": "高地",
  "Owen Sound": "欧文桑德",
  "Yotvata": "约特瓦塔",
  "Parry Sound": "帕里桑德",
  "Portage": "波蒂奇",
  "Inukjuak": "因纽朱阿克",
  "Aupaluk": "奥帕卢克",
  "Pikangikum": "皮康吉库姆",
  "Port-Menier": "梅尼耶港",
  "Peawanuck": "皮瓦努克",
  "Peterborough": "彼得伯勒",
  "Port Hawkesbury": "霍克斯伯里港",
  "Powell River": "鲍威尔河",
  "Puvirnituq": "普维尼图克",
  "Fort Chipewyan": "奇普怀恩堡",
  "Burns Lake": "伯恩斯莱克",
  "Muskoka": "马斯科卡",
  "Quaqtaq": "夸克塔克",
  "The Pas": "帕斯",
  "Windsor": "温莎",
  "Nakina": "纳基纳",
  "Comox": "科莫克斯",
  "St Thomas": "圣托马斯",
  "Thunder Bay": "桑德贝",
  "North Battlefor": "北巴特尔福德",
  "Gameti": "加梅蒂",
  "Resolute Bay": "决议湾",
  "Cartwright": "卡特赖特",
  "Rigolet": "里戈莱特",
  "Riviere-du-Loup": "里维耶尔-迪卢",
  "Red Lake": "红湖",
  "Rocky Mountain": "落基山庄",
  "Carp": "卡普",
  "Trois-Rivieres": "三河市",
  "Red Sucker Lake": "红萨克尔湖",
  "Revelstoke": "雷夫尔斯托克",
  "Squamish": "斯阔米什",
  "Stony Rapids": "斯托尼拉皮兹",
  "Lutselk'e": "卢采尔克",
  "Smiths Falls": "史密斯福尔斯",
  "Sanikiluaq": "萨尼基卢阿克",
  "St Leonard": "圣伦纳德",
  "Salmon Arm": "萨蒙阿姆",
  "Postville": "波斯特维尔",
  "St. Theresa Poi": "圣特雷莎波因特",
  "Sachs Harbour": "萨克斯港",
  "Pembroke": "彭布罗克",
  "Thicket Portage": "锡克特波蒂奇",
  "Cape Dorset": "多塞特角",
  "Alma": "阿尔马",
  "Thompson": "汤普森",
  "Big Trout Lake": "大鳟鱼湖",
  "Riviere Rouge": "红河",
  "Tasiujaq": "塔修亚克",
  "Timmins": "蒂明斯",
  "Yutian": "于田",
  "Tuktoyaktuk": "图克托亚图克",
  "Umiujaq": "乌米乌亚克",
  "Yuendumu Airpor": "尤恩杜穆机场",
  "Yushu": "玉树",
  "Repulse Bay": "里帕尔斯湾",
  "La Ronge": "拉龙日",
  "Vernon": "弗农",
  "Vermilion": "弗米利恩",
  "Qikiqtarjuaq": "基基克塔朱阿克",
  "Val-d'Or": "瓦勒多",
  "Kuujjuaq": "库朱瓦克",
  "Norman Wells": "诺曼韦尔斯",
  "Buffalo Narrows": "布法罗纳罗斯",
  "Wiarton": "怀尔顿",
  "Petawawa": "佩塔瓦瓦",
  "Kangiqsujuaq": "坎吉克苏朱阿克",
  "Deline": "迪林",
  "Williams Lake": "威廉斯莱克",
  "Williams Harbou": "威廉斯港",
  "Webequie": "韦贝基",
  "Wrigley": "瑞格利",
  "Cranbrook": "克兰布鲁克",
  "Fort St.John": "圣约翰堡",
  "Pangnirtung": "潘尼尔东",
  "Beaver Creek": "比弗克里克",
  "Earlton": "厄尔顿",
  "Terrace": "特勒斯",
  "Abbotsford": "阿伯茨福德",
  "Wawa": "瓦瓦",
  "North Bay": "北湾",
  "Taloyoak": "塔洛约阿克",
  "Lynn Lake": "林莱克",
  "Cowley": "考利",
  "Swift Current": "斯威夫特卡伦特",
  "St. John's": "圣约翰斯",
  "Kapuskasing": "卡普斯卡辛",
  "Armstrong": "阿姆斯特朗",
  "Mont-Joli": "蒙若利",
  "Gore Bay": "戈尔湾",
  "Slave Lake": "奴湖",
  "Coral Harbour": "科勒尔港",
  "Whitecourt": "怀特科特",
  "Teslin": "特斯林",
  "Mackenzie": "麦肯齐",
  "Trail": "特雷尔",
  "York Landing": "约克兰丁",
  "Zamboanga City": "三宝颜市",
  "Zaria": "扎里亚",
  "Boundary Bay": "边界湾",
  "Zabreh": "扎布热赫",
  "Bathurst": "巴瑟斯特",
  "Bromont": "布罗蒙",
  "Bowen Airport": "鲍恩机场",
  "Chabahar": "恰巴哈尔",
  "Sayaboury": "沙耶武里",
  "Neheim-Husten": "内海姆-许斯滕",
  "Bamberg": "班贝格",
  "Zacatecas": "萨卡特卡斯",
  "Celle Airport": "策勒机场",
  "Temuco": "特木科",
  "Secunda": "塞昆达",
  "Kelsey": "凯尔西",
  "Bella Bella": "贝拉贝拉",
  "Eastmain River": "东主河",
  "Zero Airport": "齐罗机场",
  "Fond-Du-Lac": "丰迪拉克",
  "Pukatawagan": "普卡塔瓦根",
  "Fort Mcpherson": "麦克弗森堡",
  "Tulita": "图利塔",
  "Gods River": "戈兹河",
  "South Galway Ai": "南戈尔韦机场",
  "Ngoma": "恩戈马",
  "Little Grand Ra": "小格兰德拉皮兹",
  "Grenchen Airpor": "格伦兴机场",
  "Shamshernagar": "尚舍尔纳格尔",
  "High Prairie": "高草原",
  "Oppin": "奥平",
  "Zhukovsky": "茹科夫斯基",
  "Trento": "特伦托",
  "Ixtapa": "伊斯塔帕",
  "Zhigansk": "日甘斯克",
  "Jenpeg": "詹佩格",
  "Locarno Airport": "洛迦诺机场",
  "Swan River": "斯旺河",
  "Kasaba Bay": "卡萨巴湾",
  "Kashechewan": "卡舍切万",
  "Kegaska": "凯加斯卡",
  "Sette Cama": "塞特卡马",
  "Zyryanka": "济良卡",
  "Kasompe": "卡松佩",
  "Linares": "利纳雷斯",
  "La Tabatiere": "拉塔巴蒂耶尔",
  "Zalingei": "扎林盖",
  "Zamora Airport": "萨莫拉机场",
  "Masset": "马塞特",
  "Zinder": "津德尔",
  "Hanau Army Air": "哈瑙陆军机场",
  "Poplar River": "波普勒河",
  "Koblenz": "科布伦茨",
  "Kiembi Samaki": "基恩比萨马基",
  "Marl": "马尔",
  "Klausheide": "克劳斯海德",
  "Sachigo Lake": "萨奇戈湖",
  "Pucon": "普孔",
  "Zephyrhills": "泽弗希尔斯",
  "Pinehouse Lake": "派恩豪斯湖",
  "Rheine Bentlage": "赖讷-本特拉格",
  "Speyer": "施派尔",
  "Donaueschingen": "多瑙埃兴根",
  "Zweibrucken": "茨魏布吕肯",
  "Zrenjanin": "兹雷尼亚宁",
  "Serui-Japen Isl": "塞鲁伊-亚彭岛",
  "Round Lake": "圆湖",
  "Sarmi-Papua Isl": "萨尔米-巴布亚岛",
  "St Pierre": "圣皮埃尔",
  "Stendal": "施滕达尔",
  "South Indian La": "南印第安湖",
  "St. Paul": "圣保罗",
  "Stewart": "斯图尔特",
  "Tete-a-la-Balei": "泰特阿拉巴莱纳",
  "Zakynthos Islan": "扎金索斯岛",
  "Shamattawa": "沙马塔瓦",
  "Zaqatala": "扎卡塔拉",
  "Ignace": "伊格纳斯",
  "Ancud": "安库德",
  "Zilfi": "济勒菲",
  "Churchill Falls": "丘吉尔瀑布",
  "Savannakhet Air": "沙湾拿吉机场",
  "Lac Brochet": "拉布罗谢湖",
  "Suwalki": "苏瓦乌基",
  "Wollaston Lake": "沃拉斯顿湖",
  "Jan Mayen Jan M": "扬马延岛",
  "Zangilan": "赞格兰",
  "Tymovskoye": "特莫夫斯科耶",
  "Mzuzu": "姆祖祖",
  "Zanesville": "赞斯维尔"
};