/**
 * CPDLC电文数据
 * 管制员-飞行员数据链通信(CPDLC)电文集
 *
 * 数据结构说明:
 * - uplink: 上行电文(管制员->飞行员)
 * - downlink: 下行电文(飞行员->管制员)
 *
 * 每条电文包含:
 * - id: 电文编号 (或 * )
 * - category: 分类
 * - purpose: 电文目的/用途(中文描述)
 * - format_en: 电文规定格式(英文)
 * - format_zh: 电文规定格式(中文)
 * - urgent: 紧急级别 (D-遇险, U-紧急, N-正常, L-低)
 * - alert: 告警级别 (H-高, M-中, L-低, N-无)
 * - response: 回答要求 (W/U-照办/不能, Y-是, R-收到, A/N-是/否, N-不需要)
 */

var cpdlcMessages = {
  // 上行电文(管制员->飞行员)
  uplink: [
    // 表 A5-1 回答/认收
    { id: '0', category: '回答/认收', purpose: '表示 ATC 不能同意请求。', format_en: 'UNABLE', format_zh: '不能', urgent: 'N', alert: 'M', response: 'N' },
    { id: '1', category: '回答/认收', purpose: '表示 ATC 收到电文,将予以答复。', format_en: 'STANDBY', format_zh: '请等候', urgent: 'N', alert: 'L', response: 'N' },
    { id: '2', category: '回答/认收', purpose: '表示 ATC 收到请求,但推迟到以后答复。', format_en: 'REQUEST DEFERRED', format_zh: '请求暂缓', urgent: 'N', alert: 'L', response: 'N' },
    { id: '3', category: '回答/认收', purpose: '表示 ATC 收到并明白电文。', format_en: 'ROGER', format_zh: '明白', urgent: 'N', alert: 'L', response: 'N' },
    { id: '4', category: '回答/认收', purpose: '是、对。', format_en: 'AFFIRM', format_zh: '是、对', urgent: 'N', alert: 'L', response: 'N' },
    { id: '5', category: '回答/认收', purpose: '不是、不对。', format_en: 'NEGATIVE', format_zh: '不是、不对', urgent: 'N', alert: 'L', response: 'N' },
    { id: '235', category: '回答/认收', purpose: '通知已收到非法干扰的电文。', format_en: 'ROGER 7500', format_zh: '收到7500', urgent: 'U', alert: 'H', response: 'N' },
    { id: '211', category: '回答/认收', purpose: '表示 ATC 收到请求并已转发下一管制当局。', format_en: 'REQUEST FORWARDED', format_zh: '请求已转出', urgent: 'N', alert: 'L', response: 'N' },
    { id: '218', category: '回答/认收', purpose: '通知飞行员,地面已收到请求。', format_en: 'REQUEST ALREADY RECEIVED', format_zh: '请求已收悉', urgent: 'L', alert: 'N', response: 'N' },
    // 表 A5-2 垂直许可
    { id: '6', category: '垂直许可', purpose: '通知应等候高度层改变的指令。', format_en: 'EXPECT (level)', format_zh: '预期(高度层)', urgent: 'L', alert: 'L', response: 'R' },
    { id: '7', category: '垂直许可', purpose: '通知航空器应等候在指定时间开始爬升的指令。', format_en: 'EXPECT CLIMB AT (time)', format_zh: '预期在(时间)爬升', urgent: 'L', alert: 'L', response: 'R' },
    { id: '8', category: '垂直许可', purpose: '通知航空器应等候在指定位置开始爬升的指令。', format_en: 'EXPECT CLIMB AT (position)', format_zh: '预期在(位置)爬升', urgent: 'L', alert: 'L', response: 'R' },
    { id: '9', category: '垂直许可', purpose: '通知航空器应等候在指定时间开始下降的指令。', format_en: 'EXPECT DESCENT AT (time)', format_zh: '预期在(时间)下降', urgent: 'L', alert: 'L', response: 'R' },
    { id: '10', category: '垂直许可', purpose: '通知航空器应等候在指定位置开始下降的指令。', format_en: 'EXPECT DESCENT AT (position)', format_zh: '预期在(位置)下降', urgent: 'L', alert: 'L', response: 'R' },
    { id: '11', category: '垂直许可', purpose: '通知航空器应等候在指定时间开始巡航爬升的指令。', format_en: 'EXPECT CRUISE CLIMB AT (time)', format_zh: '预期在(时间)巡航爬升', urgent: 'L', alert: 'L', response: 'R' },
    { id: '12', category: '垂直许可', purpose: '通知航空器应等候在指定位置开始巡航爬升的指令。', format_en: 'EXPECT CRUISE CLIMB AT (position)', format_zh: '预期在(位置)巡航爬升', urgent: 'L', alert: 'L', response: 'R' },
    { id: '19', category: '垂直许可', purpose: '指示保持指定高度层。', format_en: 'MAINTAIN (level)', format_zh: '保持(高度层)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '20', category: '垂直许可', purpose: '指示开始向指定高度层爬升,并在到达后即保持该高度层。', format_en: 'CLIMB TO (level)', format_zh: '爬升到(高度层)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '21', category: '垂直许可', purpose: '指示在指定时间开始向指定高度层爬升,并在到达后即保持该高度层。', format_en: 'AT (time) CLIMB TO (level)', format_zh: '在(时间)爬升到(高度层)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '22', category: '垂直许可', purpose: '指示在指定位置开始向指定高度层爬升,并在到达后即保持该高度层。', format_en: 'AT (position) CLIMB TO (level)', format_zh: '在(位置)爬升到(高度层)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '23', category: '垂直许可', purpose: '指示开始向指定高度层下降,并在到达后即保持该高度层。', format_en: 'DESCEND TO (level)', format_zh: '下降到(高度层)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '24', category: '垂直许可', purpose: '指示在指定时间开始向指定高度层下降,并在到达后即保持该高度层。', format_en: 'AT (time) DESCEND TO (level)', format_zh: '在(时间)下降至(高度层)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '25', category: '垂直许可', purpose: '指示在指定位置开始向指定高度层下降,并在到达后即保持该高度层。', format_en: 'AT (position) DESCEND TO (level)', format_zh: '在(位置)下降至(高度层)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '26', category: '垂直许可', purpose: '指示开始爬升,其爬升率应保证在指定时间或之前到达指定高度层。当电报内容未连接有其他垂直许可时,指定高度须是保持的指配高度。', format_en: 'CLIMB TO REACH (level) BY (time)', format_zh: '在(时间)之前爬升到(高度层)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '27', category: '垂直许可', purpose: '指示开始爬升,其爬升率应保证在到达指定位置之时或之前到达指定高度层。当电报内容未连接有其他垂直许可时,指定高度须是保持的指配高度。', format_en: 'CLIMB TO REACH (level) BY (position)', format_zh: '在(位置)之前爬升到(高度层)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '28', category: '垂直许可', purpose: '指示开始下降,其下降率应保证在指定时间或之前到达指定高度层。当电报内容未连接有其他垂直许可时,指定高度须是保持的指配高度。', format_en: 'DESCEND TO REACH (level) BY (time)', format_zh: '在(时间)之前下降至(高度层)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '29', category: '垂直许可', purpose: '指示开始下降,其下降率应保证在到达指定位置之时或之前到达指定高度层。当电报内容未连接有其他垂直许可时,指定高度须是保持的指配高度。', format_en: 'DESCEND TO REACH (level) BY (position)', format_zh: '在(位置)之前下降至(高度层)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '192', category: '垂直许可', purpose: '指示继续改变高度层,但升降率应保证在指定时间或之前到达指定高度层。', format_en: 'REACH (level) BY (time)', format_zh: '在(时间)之前到达(高度层)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '209', category: '垂直许可', purpose: '指示继续改变高度层,但升降率应保证到达指定位置之时或之前到达指定高度层。', format_en: 'REACH (level) BY (position)', format_zh: '在(位置)之前到达(高度层)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '30', category: '垂直许可', purpose: '指示在指定的划定垂直范围内保持高度层。', format_en: 'MAINTAIN BLOCK (level) TO (level)', format_zh: '保持高度段(高度层)至(高度层)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '31', category: '垂直许可', purpose: '指示开始爬升到划定垂直范围内的高度层。', format_en: 'CLIMB TO AND MAINTAIN BLOCK (level) TO (level)', format_zh: '爬升到高度段(高度层)至(高度层)并保持', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '32', category: '垂直许可', purpose: '指示开始下降到划定垂直范围内的高度层。', format_en: 'DESCEND TO AND MAINTAIN BLOCK (level) TO (level)', format_zh: '下降到高度段(高度层)至(高度层)并保持', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '34', category: '垂直许可', purpose: '指示开始巡航爬升,并继续上升至指定高度层,到达后须保持在指定高度层。', format_en: 'CRUISE CLIMB TO (level)', format_zh: '巡航爬升到(高度层)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '35', category: '垂直许可', purpose: '与有关高度层指令连同使用的指令,表示当高于指定高度层时开始巡航爬升。', format_en: 'WHEN ABOVE (level) COMMENCE CRUISE CLIMB', format_zh: '在(高度层)以上开始巡航爬升', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '219', category: '垂直许可', purpose: '指示当到达指定高度时停止爬升,到达后须保持这一高度。指定的高度低于先前指定的高度。', format_en: 'STOP CLIMB AT (level)', format_zh: '在(高度层)停止爬升', urgent: 'U', alert: 'M', response: 'W/U' },
    { id: '220', category: '垂直许可', purpose: '指示当到达指定的高度时停止下降,到达后须保持这一高度。指定的高度高于先前指定的高度。', format_en: 'STOP DESCENT AT (level)', format_zh: '在(高度层)停止下降', urgent: 'U', alert: 'M', response: 'W/U' },
    { id: '36', category: '垂直许可', purpose: '指示应以航空器最佳爬升率上升至指定高度层。', format_en: 'EXPEDITE CLIMB TO (level)', format_zh: '加速爬升到(高度层)', urgent: 'U', alert: 'M', response: 'W/U' },
    { id: '37', category: '垂直许可', purpose: '指示应以航空器最佳下降率下降至指定高度层。', format_en: 'EXPEDITE DESCENT TO (level)', format_zh: '加速下降至(高度层)', urgent: 'U', alert: 'M', response: 'W/U' },
    { id: '38', category: '垂直许可', purpose: '紧急指示立即爬升到指定高度层,到达指定高度后须保持这一高度。', format_en: 'IMMEDIATELY CLIMB TO (level)', format_zh: '立即爬升至(高度层)', urgent: 'D', alert: 'H', response: 'W/U' },
    { id: '39', category: '垂直许可', purpose: '紧急指示立即下降至指定高度层,到达指定高度后须保持这一高度。', format_en: 'IMMEDIATELY DESCEND TO (level)', format_zh: '立即下降至(高度层)', urgent: 'D', alert: 'H', response: 'W/U' },
    { id: '171', category: '垂直许可', purpose: '指示以不小于指定的速率爬升。', format_en: 'CLIMB AT (vertical rate) MINIMUM', format_zh: '最小以(垂直速率)爬升', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '172', category: '垂直许可', purpose: '指示以不大于指定的速率爬升。', format_en: 'CLIMB AT (vertical rate) MAXIMUM', format_zh: '最大以(垂直速率)爬升', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '173', category: '垂直许可', purpose: '指示以不小于指定的速率下降。', format_en: 'DESCEND AT (vertical rate) MINIMUM', format_zh: '最小以(垂直速率)下降', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '174', category: '垂直许可', purpose: '指示以不大于指定的速率下降。', format_en: 'DESCEND AT (vertical rate) MAXIMUM', format_zh: '最大以(垂直速率)下降', urgent: 'N', alert: 'M', response: 'W/U' },
    // 表 A5-3 穿越限制
    { id: '46', category: '穿越限制', purpose: '指示在指定的高度层穿越指定位置。该指令可能要求航空器改变其上升或下降剖面。', format_en: 'CROSS (position) AT (level)', format_zh: '在(高度层)穿越(位置)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '47', category: '穿越限制', purpose: '指示在指定高度层或以上穿越指定位置。', format_en: 'CROSS (position) AT OR ABOVE (level)', format_zh: '在(高度层)或以上穿越(位置)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '48', category: '穿越限制', purpose: '指示在指定高度层或以下穿越指定位置。', format_en: 'CROSS (position) AT OR BELOW (level)', format_zh: '在(高度层)或以下穿越(位置)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '49', category: '穿越限制', purpose: '指示在指定的高度层穿越指定位置,并在到达后即保持该高度层。', format_en: 'CROSS (position) AT AND MAINTAIN (level)', format_zh: '在(高度层)穿越(位置)并保持', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '50', category: '穿越限制', purpose: '指示在指定的高度层之间的高度层穿越指定位置。', format_en: 'CROSS (position) BETWEEN (level) AND (level)', format_zh: '在(高度层)和(高度层)之间穿越(位置)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '51', category: '穿越限制', purpose: '指示在指定的时间穿越指定位置。', format_en: 'CROSS (position) AT (time)', format_zh: '在(时间)穿越(位置)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '52', category: '穿越限制', purpose: '指示在指定的时间或之前穿越指定位置。', format_en: 'CROSS (position) AT OR BEFORE (time)', format_zh: '在(时间)或之前穿越(位置)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '53', category: '穿越限制', purpose: '指示在指定的时间或之后穿越指定位置。', format_en: 'CROSS (position) AT OR AFTER (time)', format_zh: '在(时间)或之后穿越(位置)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '54', category: '穿越限制', purpose: '指示在指定的时刻之间穿越指定位置。', format_en: 'CROSS (position) BETWEEN (time) AND (time)', format_zh: '在(时间)和(时间)之间穿越(位置)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '55', category: '穿越限制', purpose: '指示以指定速度穿越指定位置,保持该速度至以后通知。', format_en: 'CROSS (position) AT (speed)', format_zh: '以(速度)穿越(位置)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '56', category: '穿越限制', purpose: '指示以指定速度或更小速度穿越指定位置,并保持该速度至以后通知。', format_en: 'CROSS (position) AT OR LESS THAN (speed)', format_zh: '以(速度)或更小速度穿越(位置)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '57', category: '穿越限制', purpose: '指示以指定速度或更大速度穿越指定位置,保持该速度至以后通知。', format_en: 'CROSS (position) AT OR GREATER THAN (speed)', format_zh: '以(速度)或更大速度穿越(位置)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '58', category: '穿越限制', purpose: '指示于指定的时间,在指定的高度层穿越指定位置。', format_en: 'CROSS (position) AT (time) AT (level)', format_zh: '于(时间)在(高度层)穿越(位置)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '59', category: '穿越限制', purpose: '指示于指定的时间或之前,在指定的高度层穿越指定位置。', format_en: 'CROSS (position) AT OR BEFORE (time) AT (level)', format_zh: '于(时间)或之前在(高度层)穿越(位置)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '60', category: '穿越限制', purpose: '指示于指定的时间或之后,在指定的高度层穿越指定位置。', format_en: 'CROSS (position) AT OR AFTER (time) AT (level)', format_zh: '于(时间)或之后在(高度层)穿越(位置)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '61', category: '穿越限制', purpose: '指示以指定的高度层和速度穿越指定位置,并保持该高度层和速度。', format_en: 'CROSS (position) AT AND MAINTAIN (level) AT (speed)', format_zh: '在(高度层)以(速度)穿越(位置)并保持', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '62', category: '穿越限制', purpose: '指示于指定的时间,在指定的高度层穿越指定位置,并保持该高度层。', format_en: 'AT (time) CROSS (position) AT AND MAINTAIN (level)', format_zh: '于(时间)在(高度层)穿越(位置)并保持', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '63', category: '穿越限制', purpose: '指示于指定的时间,以指定的高度层和速度穿越指定位置,并保持该高度层和速度。', format_en: 'AT (time) CROSS (position) AT AND MAINTAIN (level) AT (speed)', format_zh: '于(时间)在(高度层)以(速度)穿越(位置)并保持', urgent: 'N', alert: 'M', response: 'W/U' },
    // 表 A5-4 横向偏离
    { id: '64', category: '横向偏离', purpose: '指示按指定方向,指定偏航距离,平行于批准航路飞行。', format_en: 'OFFSET (specified distance) (direction) OF ROUTE', format_zh: '偏离航路的(方向)(指定距离)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '65', category: '横向偏离', purpose: '指示从指定位置开始,按指定方向,指定偏航距离,平行于批准航路飞行。', format_en: 'AT (position) OFFSET (specified distance) (direction) OF ROUTE', format_zh: '在(位置)偏离航路的(方向)(指定距离)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '66', category: '横向偏离', purpose: '指示于指定时间开始,按指定方向,指定偏航距离,平行于批准航路飞行。', format_en: 'AT (time) OFFSET (specified distance) (direction) OF ROUTE', format_zh: '于(时间)偏离航路的(方向)(指定距离)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '67', category: '横向偏离', purpose: '指示重新加入批准航路。', format_en: 'PROCEED BACK ON ROUTE', format_zh: '返回航路', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '68', category: '横向偏离', purpose: '指示在到达指定位置之时或之前重新加入批准航路。', format_en: 'REJOIN ROUTE BY (position)', format_zh: '在(位置)之前返回航路', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '69', category: '横向偏离', purpose: '指示于指定时间或之前重新加入批准航路。', format_en: 'REJOIN ROUTE BY (time)', format_zh: '在(时间)之前返回航路', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '70', category: '横向偏离', purpose: '通知可能发出许可,使航空器能在到达指定位置之时或之前重新加入批准航路。', format_en: 'EXPECT BACK ON ROUTE BY (position)', format_zh: '预期在(位置)之前返回航路', urgent: 'L', alert: 'L', response: 'R' },
    { id: '71', category: '横向偏离', purpose: '通知可能发出许可,使航空器能在指定时间或之前重新加入批准航路。', format_en: 'EXPECT BACK ON ROUTE BY (time)', format_zh: '预期在(时间)之前返回航路', urgent: 'L', alert: 'L', response: 'R' },
    { id: '72', category: '横向偏离', purpose: '指示在允许的一段飞行或航向之后,恢复自己的航行。可以同如何或在何处重新加入批准航路的指令相连用。', format_en: 'RESUME OWN NAVIGATION', format_zh: '恢复自己的航行', urgent: 'N', alert: 'M', response: 'W/U' },
    // 表 A5-5 航路改变
    { id: '73', category: '航路改变', purpose: '从起飞至许可界限之前应遵行的指令。', format_en: '(departure clearance)', format_zh: '(起飞许可)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '74', category: '航路改变', purpose: '指示从现在位置直接飞向指定位置。', format_en: 'PROCEED DIRECT TO (position)', format_zh: '直飞(位置)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '75', category: '航路改变', purpose: '指示在可能时直接飞向指定位置。', format_en: 'WHEN ABLE PROCEED DIRECT TO (position)', format_zh: '如可能直飞(位置)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '76', category: '航路改变', purpose: '指示于指定时间直接飞向指定位置。', format_en: 'AT (time) PROCEED DIRECT TO (position)', format_zh: '于(时间)直飞(位置)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '77', category: '航路改变', purpose: '指示从指定位置直接飞向下一指定位置。', format_en: 'AT (position) PROCEED DIRECT TO (position)', format_zh: '在(位置)直飞(位置)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '78', category: '航路改变', purpose: '指示在到达指定高度层后,直接飞向指定位置。', format_en: 'AT (level) PROCEED DIRECT TO (position)', format_zh: '在(高度层)直飞(位置)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '79', category: '航路改变', purpose: '指示经由指定航路飞往指定位置。', format_en: 'CLEARED TO (position) VIA (route clearance)', format_zh: '允许经由(批准航路)飞往(位置)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '80', category: '航路改变', purpose: '指示沿指定航路飞行。', format_en: 'CLEARED (route clearance)', format_zh: '允许飞(批准航路)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '81', category: '航路改变', purpose: '指示按照指定的程序飞行。', format_en: 'CLEARED (procedure name)', format_zh: '允许飞(程序名称)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '236', category: '航路改变', purpose: '指示飞离管制空域。', format_en: 'LEAVE CONTROLLED AIRSPACE', format_zh: '飞离管制空域', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '82', category: '航路改变', purpose: '批准偏航至许可航路的指定方向,指定距离。', format_en: 'CLEARED TO DEVIATE UPTO (specified distance) (direction) OFROUTE', format_zh: '允许偏航至航路的(方向)至(指定距离)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '83', category: '航路改变', purpose: '指示从指定位置飞经指定航路。', format_en: 'AT (position) CLEARED (route clearance)', format_zh: '允许在(位置)飞(批准航路)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '84', category: '航路改变', purpose: '指示从指定位置飞指定的程序。', format_en: 'AT (position) CLEARED (procedure name)', format_zh: '在(位置)允许飞(程序名称)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '85', category: '航路改变', purpose: '通知可能签发在指定航路上飞行的许可。', format_en: 'EXPECT (route clearance)', format_zh: '预期(航路许可)', urgent: 'L', alert: 'L', response: 'R' },
    { id: '86', category: '航路改变', purpose: '通知可能签发从指定位置在指定航路飞行的许可。', format_en: 'AT (position) EXPECT (route clearance)', format_zh: '预期在(位置)飞(航路许可)', urgent: 'L', alert: 'L', response: 'R' },
    { id: '87', category: '航路改变', purpose: '通知可能签发直飞指定位置的许可。', format_en: 'EXPECT DIRECT TO (position)', format_zh: '预期直飞(位置)', urgent: 'L', alert: 'L', response: 'R' },
    { id: '88', category: '航路改变', purpose: '通知可能签发从第一指定位置直飞下一指定位置的许可。', format_en: 'AT (position) EXPECT DIRECT TO (position)', format_zh: '预期在(位置)直飞(位置)', urgent: 'L', alert: 'L', response: 'R' },
    { id: '89', category: '航路改变', purpose: '通知可能签发于指定时间开始直飞指定位置的许可。', format_en: 'AT (time) EXPECT DIRECT TO (position)', format_zh: '预期于(时间)直飞(位置)', urgent: 'L', alert: 'L', response: 'R' },
    { id: '90', category: '航路改变', purpose: '通知可能签发在到达指定高度层后开始直飞指定位置的许可。', format_en: 'AT (level) EXPECT DIRECT TO (position)', format_zh: '预期在(高度层)直飞(位置)', urgent: 'L', alert: 'L', response: 'R' },
    { id: '91', category: '航路改变', purpose: '指示在指定位置,以指定的高度层加入具有指定特性的等待航线。', format_en: 'HOLD AT (position) MAINTAIN (level) INBOUND TRACK (degrees) (direction) TURNS (leg type)', format_zh: '在(位置)等待保持(高度层)入航航迹(度)(方向)转弯(边的类型)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '92', category: '航路改变', purpose: '指示在指定的位置,以指定的高度层加入具有公布特性的等待空域。', format_en: 'HOLD AT (position) AS PUBLISHED MAINTAIN (level)', format_zh: '在规定(位置)等待保持(高度层)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '93', category: '航路改变', purpose: '通知可能在指定时间签发向前飞行的许可。', format_en: 'EXPECT FURTHER CLEARANCE AT (time)', format_zh: '在(时间)等待下一步许可', urgent: 'L', alert: 'L', response: 'R' },
    { id: '94', category: '航路改变', purpose: '指示按指定方向左转或右转至指定航向。', format_en: 'TURN (direction) HEADING (degrees)', format_zh: '转弯(方向)航向(度)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '95', category: '航路改变', purpose: '指示按指定方向左转或右转至指定航迹。', format_en: 'TURN (direction) GROUND TRACK (degrees)', format_zh: '转弯(方向)航迹(度)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '215', category: '航路改变', purpose: '指示作指定度数的左转弯或右转弯。', format_en: 'TURN (direction) (degrees) DEGREES', format_zh: '转弯(方向)(度)度', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '190', category: '航路改变', purpose: '指示按指定航向飞行。', format_en: 'FLY HEADING (degrees)', format_zh: '飞行航向(度)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '96', category: '航路改变', purpose: '指示继续按现在航向飞行。', format_en: 'CONTINUE PRESENT HEADING', format_zh: '继续飞现在航向', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '97', category: '航路改变', purpose: '指示从指定位置飞指定航向。', format_en: 'AT (position) FLY HEADING (degrees)', format_zh: '从(位置)飞航向(度)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '221', category: '航路改变', purpose: '指示在转至先前指配的航向前,在指定航向停止转弯。', format_en: 'STOP TURN HEADING (degrees)', format_zh: '在航向(度)停止转弯', urgent: 'U', alert: 'M', response: 'W/U' },
    { id: '98', category: '航路改变', purpose: '指示立即按规定左转或右转至指定航向。', format_en: 'IMMEDIATELY TURN (direction) HEADING (degrees)', format_zh: '立即(方向)转弯航向(度)', urgent: 'D', alert: 'H', response: 'W/U' },
    { id: '99', category: '航路改变', purpose: '通知可能为航空器签发飞指定程序的许可。', format_en: 'EXPECT (procedure name)', format_zh: '预期飞(程序名称)', urgent: 'L', alert: 'L', response: 'R' },
    // 表 A5-6 速度变化
    { id: '100', category: '速度变化', purpose: '通知可能签发于指定时间生效的速度指令。', format_en: 'AT (time) EXPECT (speed)', format_zh: '在(时间)预期(速度)', urgent: 'L', alert: 'L', response: 'R' },
    { id: '101', category: '速度变化', purpose: '通知可能签发在指定位置生效的速度指令。', format_en: 'AT (position) EXPECT (speed)', format_zh: '在(位置)预期(速度)', urgent: 'L', alert: 'L', response: 'R' },
    { id: '102', category: '速度变化', purpose: '通知可能签发在指定高度层生效的速度指令。', format_en: 'AT (level) EXPECT (speed)', format_zh: '在(高度层)预期(速度)', urgent: 'L', alert: 'L', response: 'R' },
    { id: '103', category: '速度变化', purpose: '通知可能签发于指定时间生效的速度范围指令。', format_en: 'AT (time) EXPECT (speed) TO (speed)', format_zh: '在(时间)预期(速度)至(速度)', urgent: 'L', alert: 'L', response: 'R' },
    { id: '104', category: '速度变化', purpose: '通知可能签发在指定位置生效的速度范围指令。', format_en: 'AT (position) EXPECT (speed) TO (speed)', format_zh: '在(位置)预期(速度)至(速度)', urgent: 'L', alert: 'L', response: 'R' },
    { id: '105', category: '速度变化', purpose: '通知可能签发在指定高度层生效的速度范围指令。', format_en: 'AT (level) EXPECT (speed) TO (speed)', format_zh: '在(高度层)预期(速度)至(速度)', urgent: 'L', alert: 'L', response: 'R' },
    { id: '106', category: '速度变化', purpose: '指示保持指定速度。', format_en: 'MAINTAIN (speed)', format_zh: '保持(速度)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '188', category: '速度变化', purpose: '指示通过指定位置之后保持指定速度。', format_en: 'AFTER PASSING (position) MAINTAIN (speed)', format_zh: '通过(位置)后保持(速度)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '107', category: '速度变化', purpose: '指示保持现在速度。', format_en: 'MAINTAIN PRESENT SPEED', format_zh: '保持现在速度', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '108', category: '速度变化', purpose: '指示保持指定速度或更大速度。', format_en: 'MAINTAIN (speed) OR GREATER', format_zh: '保持(速度)或更大速度', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '109', category: '速度变化', purpose: '指示保持指定速度或更小速度。', format_en: 'MAINTAIN (speed) OR LESS', format_zh: '保持(速度)或更小速度', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '110', category: '速度变化', purpose: '指示保持指定速度范围内的速度。', format_en: 'MAINTAIN (speed) TO (speed)', format_zh: '保持(速度)至(速度)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '111', category: '速度变化', purpose: '指示将现在速度加速至指定速度,并保持至进一步通知。', format_en: 'INCREASE SPEED TO (speed)', format_zh: '加速至(速度)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '112', category: '速度变化', purpose: '指示将现在速度加速至指定速度或更大速度,并保持该速度或更大速度至进一步通知。', format_en: 'INCREASE SPEED TO (speed) OR GREATER', format_zh: '加速至(速度)或更大速度', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '113', category: '速度变化', purpose: '指示将现在速度减慢至指定速度,并保持至进一步通知。', format_en: 'REDUCE SPEED TO (speed)', format_zh: '减速至(速度)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '114', category: '速度变化', purpose: '指示将现在速度减至指定速度或更小速度,并保持该速度或更小速度至进一步通知。', format_en: 'REDUCE SPEED TO (speed) OR LESS', format_zh: '减速至(速度)或更小速度', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '115', category: '速度变化', purpose: '指示不得超过指定速度。', format_en: 'DO NOT EXCEED (speed)', format_zh: '不得超过(速度)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '116', category: '速度变化', purpose: '指示航空器恢复正常速度。先前发布的速度限制被取消。', format_en: 'RESUME NORMAL SPEED', format_zh: '恢复正常速度', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '189', category: '速度变化', purpose: '指示将现在速度调整至指定速度。', format_en: 'ADJUST SPEED TO (speed)', format_zh: '调整速度至(速度)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '222', category: '速度变化', purpose: '通知航空器可以不受限制保持其希望的速度。', format_en: 'NO SPEED RESTRICTION', format_zh: '无速度限制', urgent: 'L', alert: 'L', response: 'R' },
    { id: '223', category: '速度变化', purpose: '指示减慢现行速度至最低安全进近速度。', format_en: 'REDUCE TO MINIMUM APPROACH SPEED', format_zh: '减至最低进近速度', urgent: 'N', alert: 'M', response: 'W/U' },
    // 表 A5-7 联络/监测/监视请求
    { id: '117', category: '联络/监测/监视请求', purpose: '指示在指定频率上联络有指定的 ATS 单位名称的 ATS 单位。', format_en: 'CONTACT (unit name) (frequency)', format_zh: '联络(单位名称)(频率)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '118', category: '联络/监测/监视请求', purpose: '指示在指定位置,在指定频率上联络有指定的 ATS 单位名称的 ATS 单位。', format_en: 'AT (position) CONTACT (unit name) (frequency)', format_zh: '在(位置)联络(单位名称)(频率)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '119', category: '联络/监测/监视请求', purpose: '指示于指定时间,在指定频率上联络有指定的 ATS 单位名称的 ATS 单位。', format_en: 'AT (time) CONTACT (unit name) (frequency)', format_zh: '于(时间)联络(单位名称)(频率)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '238', category: '联络/监测/监视请求', purpose: '通知经指定的二次频率', format_en: 'SECONDARY FREQUENCY (frequency)', format_zh: '二次频率(频率)', urgent: 'N', alert: 'L', response: 'R' },
    { id: '120', category: '联络/监测/监视请求', purpose: '指示在指定频率上监测有指定的 ATS 单位名称的 ATS 单位。', format_en: 'MONITOR (unit name) (frequency)', format_zh: '监测(单位名称)(频率)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '121', category: '联络/监测/监视请求', purpose: '指示在指定位置,在指定频率上监测有指定的 ATS 单位名称的 ATS 单位。', format_en: 'AT (position) MONITOR (unit name) (frequency)', format_zh: '在(位置)监测(单位名称)(频率)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '122', category: '联络/监测/监视请求', purpose: '指示于指定时间,在指定频率上监测有指定的 ATS 单位名称的 ATS 单位。', format_en: 'AT (time) MONITOR (unit name) (frequency)', format_zh: '于(时间)监测(单位名称)(频率)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '123', category: '联络/监测/监视请求', purpose: '指示选用指配的 SSR 编码。', format_en: 'SQUAWK (code)', format_zh: '打开应答机(编码)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '124', category: '联络/监测/监视请求', purpose: '指示停用 SSR 应答机。', format_en: 'STOP SQUAWK', format_zh: '关闭应答机', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '239', category: '联络/监测/监视请求', purpose: '指示终止拍发 ADS-B', format_en: 'STOP ADS-B TRANSMISSION', format_zh: '停止拍发 ADS-B', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '125', category: '联络/监测/监视请求', purpose: '指示 SSR 应答机应答内容应包括高度层信息。', format_en: 'SQUAWK MODE CHARLIE', format_zh: '使用应答模式C', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '240', category: '联络/监测/监视请求', purpose: '指示 ADS-B 发报应包括高度情报。', format_en: 'TRANSMIT ADS-B ALTITUDE', format_zh: '发送 ADS-B 高度', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '126', category: '联络/监测/监视请求', purpose: '指示 SSR 应答机应答内容不再需要包括高度层信息。', format_en: 'STOP SQUAWK MODE CHARLIE', format_zh: '停用应答模式C', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '241', category: '联络/监测/监视请求', purpose: '指示 ADS-B 发报不再包括高度情报。', format_en: 'STOP ADS-B ALTITUDE TRANSMISSION', format_zh: '关闭 ADS-B 高度发送', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '179', category: '联络/监测/监视请求', purpose: '指示使用 SSR 应答机识别功能。', format_en: 'SQUAWK IDENT', format_zh: '打开应答识别', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '242', category: '联络/监测/监视请求', purpose: '指示启用 ADS-B 发射机“识别”功能', format_en: 'TRANSMIT ADS-B IDENT', format_zh: '发送 ADS-B 识别', urgent: 'N', alert: 'M', response: 'W/U' },
    // 表 A5-8 报告/证实请求
    { id: '243', category: '报告/证实请求', purpose: '指示航空器离开恶劣气象条件并回到批准的飞行航路的许可能够接受时报告。', format_en: 'REPORT CLEAR OF WEATHER', format_zh: '报告天气晴朗', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '127', category: '报告/证实请求', purpose: '指示航空器在回到批准航路时报告。', format_en: 'REPORT BACK ON ROUTE', format_zh: '报告回到航路', urgent: 'N', alert: 'L', response: 'W/U' },
    { id: '128', category: '报告/证实请求', purpose: '指示航空器在退出保持或在爬升或下降时穿越的指定高度层时报告。', format_en: 'REPORT LEAVING (level)', format_zh: '报告离开(高度层)', urgent: 'N', alert: 'L', response: 'W/U' },
    { id: '129', category: '报告/证实请求', purpose: '指示航空器在指定高度层保持平飞时报告。', format_en: 'REPORT MAINTAINING (level)', format_zh: '报告保持(高度层)', urgent: 'N', alert: 'L', response: 'W/U' },
    { id: '200', category: '报告/证实请求', purpose: '指示报告保持指定高度层,与高度层许可连用。', format_en: 'REPORT REACHING', format_zh: '报告保持', urgent: 'N', alert: 'L', response: 'W/U' },
    { id: '180', category: '报告/证实请求', purpose: '指示航空器在指定垂直范围内时报告。', format_en: 'REPORT REACHING BLOCK (level) TO (level)', format_zh: '报告到达高度段(高度层)至(高度层)', urgent: 'N', alert: 'L', response: 'W/U' },
    { id: '130', category: '报告/证实请求', purpose: '指示航空器通过指定位置后报告。', format_en: 'REPORT PASSING (position)', format_zh: '报告通过(位置)', urgent: 'N', alert: 'L', response: 'W/U' },
    { id: '181', category: '报告/证实请求', purpose: '指示报告距/自指定位置的现在距离。', format_en: 'REPORT DISTANCE (to/from) (position)', format_zh: '报告(距/自)(位置)的距离', urgent: 'N', alert: 'M', response: 'Y' },
    { id: '184', category: '报告/证实请求', purpose: '指示于指定时间报告距/自指定位置的距离。', format_en: 'AT (time) REPORT DISTANCE (to/from) (position)', format_zh: '于(时间)报告(距/自)(位置)的距离', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '228', category: '报告/证实请求', purpose: '指示报告预计到达指定位置的时间。', format_en: 'REPORT ETA (position)', format_zh: '报告 ETA (位置)', urgent: 'L', alert: 'L', response: 'Y' },
    { id: '131', category: '报告/证实请求', purpose: '指示报告剩余油量和机上人数。', format_en: 'REPORT REMAINING FUEL AND PERSONS ON BOARD', format_zh: '报告剩余油量和机上人数', urgent: 'U', alert: 'M', response: 'Y' },
    { id: '132', category: '报告/证实请求', purpose: '指示报告现在位置。', format_en: 'REPORT POSITION', format_zh: '报告位置', urgent: 'N', alert: 'M', response: 'Y' },
    { id: '133', category: '报告/证实请求', purpose: '指示报告现在高度。', format_en: 'REPORT PRESENT LEVEL', format_zh: '报告现在高度层', urgent: 'N', alert: 'M', response: 'Y' },
    { id: '134', category: '报告/证实请求', purpose: '指示报告要求的速度。', format_en: 'REPORT (speed type) (speed type) (speed type) SPEED', format_zh: '报告(速度类型)(速度类型)(速度类型)速度', urgent: 'N', alert: 'M', response: 'Y' },
    { id: '135', category: '报告/证实请求', purpose: '指示证实现用指配高度层。', format_en: 'CONFIRM ASSIGNED LEVEL', format_zh: '证实现用指配高度层', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '136', category: '报告/证实请求', purpose: '指示证实现用指定速度。', format_en: 'CONFIRM ASSIGNED SPEED', format_zh: '证实现用指定速度', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '137', category: '报告/证实请求', purpose: '指示证实现飞指定航路。', format_en: 'CONFIRM ASSIGNED ROUTE', format_zh: '证实指定航路', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '138', category: '报告/证实请求', purpose: '指示证实先前报告的飞越上一航路点的时间。', format_en: 'CONFIRM TIME OVER REPORTED WAYPOINT', format_zh: '证实飞越已报航路点的时间', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '139', category: '报告/证实请求', purpose: '指示证实先前报告的航路点名称。', format_en: 'CONFIRM REPORTED WAYPOINT', format_zh: '证实报告的航路点', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '140', category: '报告/证实请求', purpose: '指示证实下一航路点的名称。', format_en: 'CONFIRM NEXT WAYPOINT', format_zh: '证实下一航路点', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '141', category: '报告/证实请求', purpose: '指示证实先前报告的预计到达下一航路点的时间。', format_en: 'CONFIRM NEXT WAYPOINT ETA', format_zh: '证实下一航路点的 ETA', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '142', category: '报告/证实请求', purpose: '指示证实再下一个航路点的名称。', format_en: 'CONFIRM ENSUING WAYPOINT', format_zh: '证实再下一个航路点', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '143', category: '报告/证实请求', purpose: '不明白请求,应予以澄清并重新申请。', format_en: 'CONFIRM REQUEST', format_zh: '证实请求', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '144', category: '报告/证实请求', purpose: '指示报告选用的 SSR 编码。', format_en: 'CONFIRM SQUAWK', format_zh: '证实应答机编码', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '145', category: '报告/证实请求', purpose: '指示报告现飞航向。', format_en: 'REPORT HEADING', format_zh: '报告航向', urgent: 'N', alert: 'M', response: 'Y' },
    { id: '146', category: '报告/证实请求', purpose: '指示报告现在地面航迹。', format_en: 'REPORT GROUND TRACK', format_zh: '报告航迹', urgent: 'N', alert: 'M', response: 'Y' },
    { id: '182', category: '报告/证实请求', purpose: '指示报告收到的最后一个 ATIS 的识别代码。', format_en: 'CONFIRM ATIS CODE', format_zh: '证实 ATIS 代码', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '147', category: '报告/证实请求', purpose: '指示作位置报告。', format_en: 'REQUEST POSITION REPORT', format_zh: '请发位置报告', urgent: 'N', alert: 'M', response: 'Y' },
    { id: '216', category: '报告/证实请求', purpose: '指示提出飞行计划。', format_en: 'REQUEST FLIGHT PLAN', format_zh: '请发飞行计划', urgent: 'N', alert: 'M', response: 'Y' },
    { id: '217', category: '报告/证实请求', purpose: '指示报告航空器已降落。', format_en: 'REPORT ARRIVAL', format_zh: '报告到达', urgent: 'N', alert: 'M', response: 'Y' },
    { id: '229', category: '报告/证实请求', purpose: '指示报告愿往降落的备降场。', format_en: 'REPORT ALTERNATE AERODROME', format_zh: '报告备降场', urgent: 'L', alert: 'L', response: 'Y' },
    { id: '231', category: '报告/证实请求', purpose: '指示说明飞行员愿飞的高度层。', format_en: 'STATE PREFERRED LEVEL', format_zh: '说明愿飞的高度层', urgent: 'L', alert: 'L', response: 'Y' },
    { id: '232', category: '报告/证实请求', purpose: '指示说明飞行员希望开始向预计降落机场下降的时间和/或位置。', format_en: 'STATE TOP OF DESCENT', format_zh: '说明下降起始点', urgent: 'L', alert: 'L', response: 'Y' },
    // 表 A5-9 询问请求
    { id: '148', category: '询问请求', purpose: '请告能够接受指定高度层的最早时间或位置。', format_en: 'WHEN CAN YOU ACCEPT (level)', format_zh: '你何时能够接受(高度层)', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '149', category: '询问请求', purpose: '指示报告能否在指定位置接受指定高度层。', format_en: 'CAN YOU ACCEPT (level) AT (position)', format_zh: '你能否在(位置)接受(高度层)', urgent: 'N', alert: 'L', response: 'A/N' },
    { id: '150', category: '询问请求', purpose: '指示报告能否在指定时间接受指定高度层。', format_en: 'CAN YOU ACCEPT (level) AT (time)', format_zh: '你能否于(时间)接受(高度层)', urgent: 'N', alert: 'L', response: 'A/N' },
    { id: '151', category: '询问请求', purpose: '指示报告可以接受指定速度的最早时间或位置。', format_en: 'WHEN CAN YOU ACCEPT (speed)', format_zh: '你何时能接受(速度)', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '152', category: '询问请求', purpose: '指示报告可以接受指定偏航航迹的最早时间或位置。', format_en: 'WHEN CAN YOU ACCEPT (specified distance) (direction) OFFSET', format_zh: '你何时能接受偏航(方向)(指定距离)', urgent: 'N', alert: 'L', response: 'Y' },
    // 表 A5-10 空中交通咨询
    { id: '153', category: '空中交通咨询', purpose: 'ATS 咨询信息: 高度表应按指定值拨正。', format_en: 'ALTIMETER (altimeter)', format_zh: '高度表拨正(高度表拨正值)', urgent: 'N', alert: 'L', response: 'R' },
    { id: '213', category: '空中交通咨询', purpose: 'ATS 咨询信息: 指定高度表拨正值与指定设施相关。', format_en: '(facility designation) ALTIMETER (altimeter)', format_zh: '(设施代号)高度表拨正(高度表拨正值)', urgent: 'N', alert: 'L', response: 'R' },
    { id: '154', category: '空中交通咨询', purpose: 'ATS 咨询信息: 雷达服务现已终止。', format_en: 'RADAR SERVICE TERMINATED', format_zh: '雷达服务已终止', urgent: 'N', alert: 'L', response: 'R' },
    { id: '244', category: '空中交通咨询', purpose: 'ATS 咨询信息: 雷达和/或 ADS-B 服务现已终止。', format_en: 'IDENTIFICATION TERMINATED', format_zh: '识别终止', urgent: 'N', alert: 'L', response: 'R' },
    { id: '191', category: '空中交通咨询', purpose: 'ATS 咨询信息: 航空器正进入不提供 ATS 服务的空域,所有 ATS 服务均已终止。', format_en: 'ALL ATS TERMINATED', format_zh: '所有ATS服务均已终止', urgent: 'N', alert: 'M', response: 'R' },
    { id: '155', category: '空中交通咨询', purpose: 'ATS 咨询信息: 已在指定位置建立雷达联系。', format_en: 'RADAR CONTACT (position)', format_zh: '雷达联系(位置)', urgent: 'N', alert: 'M', response: 'R' },
    { id: '156', category: '空中交通咨询', purpose: 'ATS 咨询信息: 现已失去雷达联系。', format_en: 'RADAR CONTACT LOST', format_zh: '雷达联系中断', urgent: 'N', alert: 'M', response: 'R' },
    { id: '210', category: '空中交通咨询', purpose: 'ATS咨询信息:在雷达和/或ADS-B上识别出航空器在指定位置。', format_en: 'IDENTIFIED (position)', format_zh: '已识别(位置)', urgent: 'N', alert: 'M', response: 'R' },
    { id: '193', category: '空中交通咨询', purpose: '通知现失去雷达和/或 ADS-B 识别。', format_en: 'IDENTIFICATION LOST', format_zh: '失去识别', urgent: 'N', alert: 'M', response: 'R' },
    { id: '157', category: '空中交通咨询', purpose: '通知发现在指定频率上有连续发射,检查话筒按钮。', format_en: 'CHECK STUCK MICROPHONE (frequency)', format_zh: '检查插入话筒(频率)', urgent: 'U', alert: 'M', response: 'N' },
    { id: '158', category: '空中交通咨询', purpose: 'ATS 咨询信息: 以指定代码为标识的 ATIS 情报为现行情报。', format_en: 'ATIS (atis code)', format_zh: 'ATIS (atis 代码)', urgent: 'N', alert: 'L', response: 'R' },
    { id: '212', category: '空中交通咨询', purpose: 'ATS 咨询信息: 指定机场的指定 ATIS 情报为现行情报。', format_en: '(facility designation) ATIS (atis code) CURRENT', format_zh: '(机场代号)ATIS(atis 代码)为现行情报', urgent: 'N', alert: 'L', response: 'R' },
    { id: '214', category: '空中交通咨询', purpose: 'ATS 咨询信息: 表示指定跑道的 RVR 值。', format_en: 'RVR RUNWAY (runway) (rvr)', format_zh: 'RVR 跑道(跑道)(rvr)', urgent: 'N', alert: 'M', response: 'R' },
    { id: '224', category: '空中交通咨询', purpose: 'ATS 咨询信息: 预计不会出现延误。', format_en: 'NO DELAY EXPECTED', format_zh: '预计不会出现延误', urgent: 'N', alert: 'L', response: 'R' },
    { id: '225', category: '空中交通咨询', purpose: 'ATS 咨询信息: 预期延误尚未确定。', format_en: 'DELAY NOT DETERMINED', format_zh: '延误未定', urgent: 'N', alert: 'L', response: 'R' },
    { id: '226', category: '空中交通咨询', purpose: 'ATS 咨询信息: 航空器预计许可于指定时间开始其进近。', format_en: 'EXPECTED APPROACH TIME (time)', format_zh: '预计进近时间(时间)', urgent: 'N', alert: 'L', response: 'R' },
    // 表 A5-11 系统管理电文
    { id: '159', category: '系统管理电文', purpose: '系统电文通知地面检测发现错误。', format_en: 'ERROR (error information)', format_zh: '错误(错误信息)', urgent: 'U', alert: 'M', response: 'N' },
    { id: '160', category: '系统管理电文', purpose: '通知航空电子设备,指定单位为下一数据负责单位。如果未指定数据负责单位表示任何以前指定的下一数据负责单位不再有效。', format_en: 'NEXT DATA AUTHORITY (facility)', format_zh: '下一数据负责单位(负责单位)', urgent: 'L', alert: 'N', response: 'N' },
    { id: '161', category: '系统管理电文', purpose: '通知航空电子设备,与当前数据负责单位的数据链通信正在终止。', format_en: 'END SERVICE', format_zh: '终止服务', urgent: 'L', alert: 'N', response: 'N' },
    { id: '162', category: '系统管理电文', purpose: '通知地面系统不支持该电文。', format_en: 'MESSAGE NOT SUPPORTED BY THIS ATS UNIT', format_zh: '本ATS单位不支持这份电报', urgent: 'L', alert: 'L', response: 'N' },
    { id: '234', category: '系统管理电文', purpose: '通知地面系统无该航空器飞行计划。', format_en: 'FLIGHT PLAN NOT HELD', format_zh: '没有飞行计划', urgent: 'L', alert: 'L', response: 'N' },
    { id: '163', category: '系统管理电文', purpose: '通知飞行员 ATSU 标识。', format_en: '(facility designation)', format_zh: '(负责单位代号)', urgent: 'L', alert: 'N', response: 'N' },
    { id: '227', category: '系统管理电文', purpose: '向机上系统证实,地面系统收到逻辑认收电文,并认为此电文可接受以传送给负责人。', format_en: 'LOGICAL ACKNOWLEDGEMENT', format_zh: '逻辑认收', urgent: 'N', alert: 'M', response: 'N' },
    { id: '233', category: '系统管理电文', purpose: '通知飞行员,本地面系统不接受发送的逻辑认收电文。', format_en: 'USE OF LOGICAL ACKNOWLEDGEMENT PROHIBITED', format_zh: '禁用逻辑承认', urgent: 'N', alert: 'M', response: 'N' },
    // 表 A5-12 间距电文
    { id: '*', category: '间距电文', purpose: '参照航空器后方有高度层更换程序航空器时,空中交通服务确认驾驶员使用高度层更换程序。此电文总是连接一个垂直许可。', format_en: 'ITP BEHIND (aircraft identification of reference aircraft)', format_zh: '(参照航空器的航空器识别代码)后方有高度层更换程序', urgent: 'N', alert: 'L', response: 'R' },
    { id: '*', category: '间距电文', purpose: '参照航空器前方有高度层更换程序航空器时,空中交通服务确认驾驶员使用高度层更换程序。此电文总是连接一个垂直许可。', format_en: 'ITP AHEAD OF (aircraft identification of reference aircraft)', format_zh: '(参照航空器的航空器识别代码)前方有高度层更换程序', urgent: 'N', alert: 'L', response: 'R' },
    { id: '*', category: '间距电文', purpose: '当两架参照航空器后方有高度层更换程序航空器时,空中交通服务确认驾驶员使用高度层更换程序。此电文总是连接一个垂直许可。', format_en: 'ITP BEHIND (aircraft identification of reference aircraft) AND BEHIND (aircraft identification of reference aircraft)', format_zh: '(参照航空器的航空器识别代码)后方和(参照航空器的航空器识别代码)后方有高度层更换程序', urgent: 'N', alert: 'L', response: 'R' },
    { id: '*', category: '间距电文', purpose: '当两架参照航空器前方有高度层更换程序航空器时,空中交通服务确认驾驶员使用高度层更换程序。此电文总是连接一个垂直许可。', format_en: 'ITP AHEAD OF (aircraft identification of reference aircraft) AND AHEAD OF (aircraft identification of reference aircraft)', format_zh: '(参照航空器的航空器识别代码)前方和(参照航空器的航空器识别代码)前方有高度层更换程序', urgent: 'N', alert: 'L', response: 'R' },
    { id: '*', category: '间距电文', purpose: '当一架高度层更换程序航空器位于一架参照航空器之后,但在另一架参照航空器之前,空中交通服务确认驾驶员使用高度层更换程序。此电文总是连接一个垂直许可。', format_en: 'ITP BEHIND (aircraft identification of reference aircraft) AND AHEAD OF (aircraft identification of reference aircraft)', format_zh: '(参照航空器的航空器识别代码)后方和(参照航空器的航空器识别)前方有高度层更换程序', urgent: 'N', alert: 'L', response: 'R' },
    // 表 A5-13 其他电文
    { id: '164', category: '其他电文', purpose: '有关指示可在以后任何时间执行。', format_en: 'WHEN READY', format_zh: '当准备好时', urgent: 'L', alert: 'N', response: 'N' },
    { id: '230', category: '其他电文', purpose: '有关指示应立即执行。', format_en: 'IMMEDIATELY', format_zh: '立即', urgent: 'D', alert: 'H', response: 'N' },
    { id: '165', category: '其他电文', purpose: '用于连接两份电文,说明许可或指令的正当实施顺序。', format_en: 'THEN', format_zh: '然后', urgent: 'L', alert: 'N', response: 'N' },
    { id: '166', category: '其他电文', purpose: '由于交通原因发出有关指令。', format_en: 'DUE TO (traffic type) TRAFFIC', format_zh: '由于(飞行种类)飞行', urgent: 'L', alert: 'N', response: 'N' },
    { id: '167', category: '其他电文', purpose: '由于空域限制发出有关指令。', format_en: 'DUE TO AIRSPACE RESTRICTION', format_zh: '由于空域限制', urgent: 'L', alert: 'N', response: 'N' },
    { id: '168', category: '其他电文', purpose: '所指明的电文无需处理。', format_en: 'DISREGARD', format_zh: '无需处理', urgent: 'U', alert: 'M', response: 'R' },
    { id: '176', category: '其他电文', purpose: '指示飞行员负责保持与其他航空器的间隔,同时负责保持目视气象条件。', format_en: 'MAINTAIN OWN SEPARATION AND VMC', format_zh: '自行保持间隔和目视气象条件', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '177', category: '其他电文', purpose: '用于与许可或指令连用,表示飞行员打算执行时可以执行。', format_en: 'AT PILOTS DISCRETION', format_zh: '由飞行员决定', urgent: 'L', alert: 'L', response: 'N' },
    { id: '169', category: '其他电文', purpose: '(非固定格式电文)', format_en: '(free text)', format_zh: '(非固定格式电文)', urgent: 'N', alert: 'L', response: 'R' },
    { id: '170', category: '其他电文', purpose: '(非固定格式电文)', format_en: '(free text)', format_zh: '(非固定格式电文)', urgent: 'D', alert: 'H', response: 'R' },
    { id: '183', category: '其他电文', purpose: '(非固定格式电文)', format_en: '(free text)', format_zh: '(非固定格式电文)', urgent: 'M', alert: 'N', response: 'M' },
    { id: '187', category: '其他电文', purpose: '(非固定格式电文)', format_en: '(free text)', format_zh: '(非固定格式电文)', urgent: 'L', alert: 'N', response: 'N' },
    { id: '194', category: '其他电文', purpose: '(非固定格式电文)', format_en: '(free text)', format_zh: '(非固定格式电文)', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '195', category: '其他电文', purpose: '(非固定格式电文)', format_en: '(free text)', format_zh: '(非固定格式电文)', urgent: 'L', alert: 'L', response: 'R' },
    { id: '196', category: '其他电文', purpose: '(非固定格式电文)', format_en: '(free text)', format_zh: '(非固定格式电文)', urgent: 'N', alert: 'M', response: 'W/U' },
    { id: '197', category: '其他电文', purpose: '(非固定格式电文)', format_en: '(free text)', format_zh: '(非固定格式电文)', urgent: 'U', alert: 'M', response: 'W/U' },
    { id: '198', category: '其他电文', purpose: '(非固定格式电文)', format_en: '(free text)', format_zh: '(非固定格式电文)', urgent: 'D', alert: 'H', response: 'W/U' },
    { id: '199', category: '其他电文', purpose: '(非固定格式电文)', format_en: '(free text)', format_zh: '(非固定格式电文)', urgent: 'N', alert: 'L', response: 'N' },
    { id: '203', category: '其他电文', purpose: '(非固定格式电文)', format_en: '(free text)', format_zh: '(非固定格式电文)', urgent: 'N', alert: 'M', response: 'R' },
    { id: '204', category: '其他电文', purpose: '(非固定格式电文)', format_en: '(free text)', format_zh: '(非固定格式电文)', urgent: 'N', alert: 'M', response: 'Y' },
    { id: '205', category: '其他电文', purpose: '(非固定格式电文)', format_en: '(free text)', format_zh: '(非固定格式电文)', urgent: 'N', alert: 'M', response: 'A/N' },
    { id: '206', category: '其他电文', purpose: '(非固定格式电文)', format_en: '(free text)', format_zh: '(非固定格式电文)', urgent: 'L', alert: 'N', response: 'Y' },
    { id: '207', category: '其他电文', purpose: '(非固定格式电文)', format_en: '(free text)', format_zh: '(非固定格式电文)', urgent: 'L', alert: 'L', response: 'Y' },
    { id: '208', category: '其他电文', purpose: '(非固定格式电文)', format_en: '(free text)', format_zh: '(非固定格式电文)', urgent: 'L', alert: 'L', response: 'N' },
  ],

  // 下行电文(飞行员->管制员)
  downlink: [
    // 表 A5-14 回答
    { id: '0', category: '回答', purpose: '明白指令,照办。', format_en: 'WILCO', format_zh: '照办', urgent: 'N', alert: 'M', response: 'N' },
    { id: '1', category: '回答', purpose: '不能照办。', format_en: 'UNABLE', format_zh: '不能', urgent: 'N', alert: 'M', response: 'N' },
    { id: '2', category: '回答', purpose: '等待答复。', format_en: 'STANDBY', format_zh: '等候', urgent: 'N', alert: 'M', response: 'N' },
    { id: '3', category: '回答', purpose: '收到电文,明白意思。', format_en: 'ROGER', format_zh: '明白', urgent: 'N', alert: 'M', response: 'N' },
    { id: '4', category: '回答', purpose: '是、对', format_en: 'AFFIRM', format_zh: '是、对', urgent: 'N', alert: 'M', response: 'N' },
    { id: '5', category: '回答', purpose: '不是、不对', format_en: 'NEGATIVE', format_zh: '不是、不对', urgent: 'N', alert: 'M', response: 'N' },
    // 表 A5-15 垂直请求
    { id: '6', category: '垂直请求', purpose: '请求在指定高度层飞行。', format_en: 'REQUEST (level)', format_zh: '请求(高度层)', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '7', category: '垂直请求', purpose: '请求在指定垂直范围内的高度层飞行。', format_en: 'REQUEST BLOCK (level) TO (level)', format_zh: '请求高度段(高度层)至(高度层)', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '8', category: '垂直请求', purpose: '请求巡航爬升至指定高度层。', format_en: 'REQUEST CRUISE CLIMB TO (level)', format_zh: '请求巡航爬升至(高度层)', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '9', category: '垂直请求', purpose: '请求爬升至指定高度层。', format_en: 'REQUEST CLIMB TO (level)', format_zh: '请求爬升至(高度层)', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '10', category: '垂直请求', purpose: '请求下降至指定高度层。', format_en: 'REQUEST DESCENT TO (level)', format_zh: '请求下降至(高度层)', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '11', category: '垂直请求', purpose: '请求批准在指定位置爬升至指定高度层。', format_en: 'AT (position) REQUEST CLIMB TO (level)', format_zh: '请求在(位置)爬升至(高度层)', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '12', category: '垂直请求', purpose: '请求批准在指定位置下降至指定高度层。', format_en: 'AT (position) REQUEST DESCENT TO (level)', format_zh: '请求在(位置)下降至(高度层)', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '13', category: '垂直请求', purpose: '请求批准于指定时间爬升至指定高度层。', format_en: 'AT (time) REQUEST CLIMB TO (level)', format_zh: '请求于(时间)爬升至(高度层)', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '14', category: '垂直请求', purpose: '请求批准于指定时间下降至指定高度层。', format_en: 'AT (time) REQUEST DESCENT TO (level)', format_zh: '请求于(时间)下降至(高度层)', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '69', category: '垂直请求', purpose: '请求批准按目视避让下降。', format_en: 'REQUEST VMC DESCENT', format_zh: '请求 VMC 下降', urgent: 'N', alert: 'L', response: 'Y' },
    // 表 A5-16 横向偏离请求
    { id: '15', category: '横向偏离请求', purpose: '请求批准按指定方向的指定距离,以平行航迹偏离批准航路。', format_en: 'REQUEST OFFSET (specified distance) (direction) OF ROUTE', format_zh: '请求偏离航路的(方向)(指定距离)', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '16', category: '横向偏离请求', purpose: '请求批准从指定位置,按指定方向的指定距离,以平行航迹偏离批准航路。', format_en: 'AT (position) REQUEST OFFSET (specified distance) (direction) OF ROUTE', format_zh: '请求在(位置)偏离航路的(方向)(指定距离)', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '17', category: '横向偏离请求', purpose: '请求批准于指定时间,按指定方向的指定距离,以平行航迹偏离批准航路。', format_en: 'AT (time) REQUEST OFFSET (specified distance) (direction) OF ROUTE', format_zh: '请求于(时间)偏离航路的(方向)(指定距离)', urgent: 'N', alert: 'L', response: 'Y' },
    // 表 A5-17 速度请求
    { id: '18', category: '速度请求', purpose: '请求以指定速度飞行。', format_en: 'REQUEST (speed)', format_zh: '请求(速度)', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '19', category: '速度请求', purpose: '请求在指定速度范围内飞行。', format_en: 'REQUEST (speed) TO (speed)', format_zh: '请求(速度)至(速度)', urgent: 'N', alert: 'L', response: 'Y' },
    // 表 A5-18 话音联络请求
    { id: '20', category: '话音联络请求', purpose: '请求话音联络。', format_en: 'REQUEST VOICE CONTACT', format_zh: '请求话音联络', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '21', category: '话音联络请求', purpose: '请求在指定频率用话音联络。', format_en: 'REQUEST VOICE CONTACT (frequency)', format_zh: '请求话音联络(频率)', urgent: 'N', alert: 'L', response: 'Y' },
    // 表 A5-19 航路改变请求
    { id: '22', category: '航路改变请求', purpose: '请求从现在位置直飞指定位置。', format_en: 'REQUEST DIRECT TO (position)', format_zh: '请求直飞(位置)', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '23', category: '航路改变请求', purpose: '请求指定程序的许可。', format_en: 'REQUEST (procedure name)', format_zh: '请求(程序名称)', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '24', category: '航路改变请求', purpose: '请求航路许可。', format_en: 'REQUEST CLEARANCE (route clearance)', format_zh: '请求批准(航路许可)', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '25', category: '航路改变请求', purpose: '请求一种许可。', format_en: 'REQUEST (clearance type) CLEARANCE', format_zh: '请求(许可类型)许可', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '26', category: '航路改变请求', purpose: '请求因天气改航经指定航路至指定位置。', format_en: 'REQUEST WEATHER DEVIATION TO (position) VIA (route clearance)', format_zh: '请求因天气改飞(位置)经(批准航路)', urgent: 'N', alert: 'M', response: 'Y' },
    { id: '27', category: '航路改变请求', purpose: '请求因天气偏航至航迹的指定方向,指定距离。', format_en: 'REQUEST WEATHER DEVIATION UP TO (specified distance) (direction) OF ROUTE', format_zh: '请求因天气偏航至航路的(方向)(指定距离)', urgent: 'N', alert: 'M', response: 'Y' },
    { id: '70', category: '航路改变请求', purpose: '请求许可用指定航向飞行。', format_en: 'REQUEST HEADING (degrees)', format_zh: '请求航向(度数)', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '71', category: '航路改变请求', purpose: '请求许可用指定地面航迹飞行。', format_en: 'REQUEST GROUND TRACK (degrees)', format_zh: '请求航迹(度数)', urgent: 'N', alert: 'L', response: 'Y' },
    // 表 A5-20 报告
    { id: '28', category: '报告', purpose: '报告正离开指定高度层。', format_en: 'LEAVING (level)', format_zh: '正离开(高度层)', urgent: 'N', alert: 'L', response: 'N' },
    { id: '29', category: '报告', purpose: '报告正向指定高度层爬升。', format_en: 'CLIMBING TO (level)', format_zh: '正爬升至(高度层)', urgent: 'N', alert: 'L', response: 'N' },
    { id: '30', category: '报告', purpose: '报告正向指定高度层下降。', format_en: 'DESCENDING TO (level)', format_zh: '正下降至(高度层)', urgent: 'N', alert: 'L', response: 'N' },
    { id: '31', category: '报告', purpose: '报告通过指定位置。', format_en: 'PASSING (position)', format_zh: '通过(位置)', urgent: 'N', alert: 'L', response: 'N' },
    { id: '78', category: '报告', purpose: '报告在指定时间,航空器位置如电文所述。', format_en: 'AT (time) (distance) (to/from) (position)', format_zh: '于(时间)(距离)(距/自)(位置)', urgent: 'N', alert: 'L', response: 'N' },
    { id: '32', category: '报告', purpose: '报告现在高度层。', format_en: 'PRESENT LEVEL (level)', format_zh: '现在高度层(高度层)', urgent: 'N', alert: 'L', response: 'N' },
    { id: '33', category: '报告', purpose: '报告现在位置。', format_en: 'PRESENT POSITION (position)', format_zh: '现在位置(位置)', urgent: 'N', alert: 'L', response: 'N' },
    { id: '34', category: '报告', purpose: '报告现在速度。', format_en: 'PRESENT SPEED (speed)', format_zh: '现在速度(速度)', urgent: 'N', alert: 'L', response: 'N' },
    { id: '113', category: '报告', purpose: '报告请求的速度。', format_en: '(speed type) (speed type) (speed type) SPEED (speed)', format_zh: '(速度类型)(速度类型)(速度类型)速度(速度)', urgent: 'N', alert: 'L', response: 'N' },
    { id: '35', category: '报告', purpose: '报告现在航向度数。', format_en: 'PRESENT HEADING (degrees)', format_zh: '现在航向(度)', urgent: 'N', alert: 'L', response: 'N' },
    { id: '36', category: '报告', purpose: '报告现在地面航迹度数。', format_en: 'PRESENT GROUND TRACK (degrees)', format_zh: '现在航迹(度)', urgent: 'N', alert: 'L', response: 'N' },
    { id: '37', category: '报告', purpose: '报告航空器现保持指定高度层。', format_en: 'MAINTAINING (level)', format_zh: '保持(高度层)', urgent: 'N', alert: 'L', response: 'N' },
    { id: '76', category: '报告', purpose: '报告航空器已到达指定垂直范围内的高度层。', format_en: 'REACHING BLOCK (level) TO (level)', format_zh: '到达高度段(高度层)至(高度层)', urgent: 'N', alert: 'L', response: 'N' },
    { id: '38', category: '报告', purpose: '回诵指配高度层。', format_en: 'ASSIGNED LEVEL (level)', format_zh: '指配高度层(高度层)', urgent: 'N', alert: 'M', response: 'N' },
    { id: '77', category: '报告', purpose: '回诵指配垂直范围。', format_en: 'ASSIGNED BLOCK (level) TO (level)', format_zh: '指配高度段(高度层)至(高度层)', urgent: 'N', alert: 'M', response: 'N' },
    { id: '39', category: '报告', purpose: '回诵指配速度。', format_en: 'ASSIGNED SPEED (speed)', format_zh: '指配速度(速度)', urgent: 'N', alert: 'M', response: 'N' },
    { id: '40', category: '报告', purpose: '回诵指配航路。', format_en: 'ASSIGNED ROUTE (route clearance)', format_zh: '指配航路(航路许可)', urgent: 'N', alert: 'M', response: 'N' },
    { id: '41', category: '报告', purpose: '航空器已回到批准航路上。', format_en: 'BACK ON ROUTE', format_zh: '回到航路上', urgent: 'N', alert: 'M', response: 'N' },
    { id: '114', category: '报告', purpose: '通知航空器天气晴朗并能够接受回到批准的飞行航路的许可。', format_en: 'CLEAR OF WEATHER', format_zh: '天气晴朗', urgent: 'N', alert: 'M', response: 'N' },
    { id: '42', category: '报告', purpose: '指定位置为下一航路点。', format_en: 'NEXT WAYPOINT (position)', format_zh: '下一航路点(位置)', urgent: 'N', alert: 'L', response: 'N' },
    { id: '43', category: '报告', purpose: '指定时间为下一航路点的 ETA。', format_en: 'NEXT WAYPOINT ETA (time)', format_zh: '下一航路点的 ETA (时间)', urgent: 'N', alert: 'L', response: 'N' },
    { id: '44', category: '报告', purpose: '指定位置为再下一个航路点。', format_en: 'ENSUING WAYPOINT (position)', format_zh: '再下一个航路点(位置)', urgent: 'N', alert: 'L', response: 'N' },
    { id: '45', category: '报告', purpose: '澄清先前报告的飞越航路点。', format_en: 'REPORTED WAYPOINT (position)', format_zh: '已报航路点(位置)', urgent: 'N', alert: 'L', response: 'N' },
    { id: '46', category: '报告', purpose: '澄清先前报告的飞越航路点的时间。', format_en: 'REPORTED WAYPOINT (time)', format_zh: '已报航路点(时间)', urgent: 'N', alert: 'L', response: 'N' },
    { id: '47', category: '报告', purpose: '已选择指定的 SSR 编码。', format_en: 'SQUAWKING (code)', format_zh: '打开应答机(编码)', urgent: 'N', alert: 'L', response: 'N' },
    { id: '48', category: '报告', purpose: '位置报告。', format_en: 'POSITION REPORT (position report)', format_zh: '位置报告(位置报告)', urgent: 'N', alert: 'M', response: 'N' },
    { id: '79', category: '报告', purpose: '指定代码为最新收到的 ATIS 的代码。', format_en: 'ATIS (atis code)', format_zh: 'ATIS (atis 代码)', urgent: 'N', alert: 'L', response: 'N' },
    { id: '89', category: '报告', purpose: '在指定频率上正在监听指定 ATS 单位。', format_en: 'MONITORING (unit name) (frequency)', format_zh: '监听(单位名称)(频率)', urgent: 'U', alert: 'M', response: 'N' },
    { id: '102', category: '报告', purpose: '用于报告航空器已经降落。', format_en: 'LANDING REPORT', format_zh: '降落报告', urgent: 'N', alert: 'N', response: 'N' },
    { id: '104', category: '报告', purpose: '报告预计到达指定地点的时间。', format_en: 'ETA (position) (time)', format_zh: 'ETA (地点)(时间)', urgent: 'L', alert: 'L', response: 'N' },
    { id: '105', category: '报告', purpose: '报告备降机场。', format_en: 'ALTERNATE AERODROME (airport)', format_zh: '备降机场(机场)', urgent: 'L', alert: 'L', response: 'N' },
    { id: '106', category: '报告', purpose: '报告选用高度层', format_en: 'PREFERRED LEVEL (level)', format_zh: '选用高度层(高度层)', urgent: 'L', alert: 'L', response: 'N' },
    { id: '109', category: '报告', purpose: '报告计划开始下降进近的时间。', format_en: 'TOP OF DESCENT (time)', format_zh: '下降起始点(时间)', urgent: 'L', alert: 'L', response: 'N' },
    { id: '110', category: '报告', purpose: '报告计划开始下降进近的位置', format_en: 'TOP OF DESCENT (position)', format_zh: '下降起始点(位置)', urgent: 'L', alert: 'L', response: 'N' },
    { id: '111', category: '报告', purpose: '报告计划开始下降进近的选用的位置和时间。', format_en: 'TOP OF DESCENT (time) (position)', format_zh: '下降起始点(时间)(位置)', urgent: 'L', alert: 'L', response: 'N' },
    // 表 A5-21 询问请求
    { id: '49', category: '询问请求', purpose: '请示可以取得指定速度许可的最早时间。', format_en: 'WHEN CAN WE EXPECT (speed)', format_zh: '我们何时可以期望(速度)', urgent: 'L', alert: 'L', response: 'Y' },
    { id: '50', category: '询问请求', purpose: '请示可以取得指定速度范围许可的最早时间。', format_en: 'WHEN CAN WE EXPECT (speed) TO (speed)', format_zh: '我们何时可以期望(速度)至(速度)', urgent: 'L', alert: 'L', response: 'Y' },
    { id: '51', category: '询问请求', purpose: '请示可以取得回到计划航路许可的最早时间。', format_en: 'WHEN CAN WE EXPECT BACK ON ROUTE', format_zh: '我们何时可以期望回到航路上', urgent: 'L', alert: 'L', response: 'Y' },
    { id: '52', category: '询问请求', purpose: '请示可以取得下降许可的最早时间。', format_en: 'WHEN CAN WE EXPECT LOWER LEVEL', format_zh: '我们何时可以期望在更低高度层飞行', urgent: 'L', alert: 'L', response: 'Y' },
    { id: '53', category: '询问请求', purpose: '请示可以取得爬升许可的最早时间。', format_en: 'WHEN CAN WE EXPECT HIGHER LEVEL', format_zh: '我们何时可以期望在更高高度层飞行', urgent: 'L', alert: 'L', response: 'Y' },
    { id: '54', category: '询问请求', purpose: '请示可以取得巡航爬升至指定高度层许可的最早时间。', format_en: 'WHEN CAN WE EXPECT CRUISE CLIMB TO (level)', format_zh: '我们何时可以期望巡航爬升至(高度层)', urgent: 'L', alert: 'L', response: 'Y' },
    { id: '87', category: '询问请求', purpose: '请示可以取得爬升至指定高度层许可的最早时间。', format_en: 'WHEN CAN WE EXPECT CLIMB TO (level)', format_zh: '我们何时可以期望爬升至(高度层)', urgent: 'L', alert: 'L', response: 'Y' },
    { id: '88', category: '询问请求', purpose: '请示可以取得下降至指定高度层许可的最早时间。', format_en: 'WHEN CAN WE EXPECT DESCENT TO (level)', format_zh: '我们何时可以期望下降至(高度层)', urgent: 'L', alert: 'L', response: 'Y' },
    // 表 A5-22 紧急电文
    { id: '55', category: '紧急电文', purpose: '紧急电文前缀。', format_en: 'PAN PAN PAN', format_zh: '', urgent: 'U', alert: 'H', response: 'Y' },
    { id: '56', category: '紧急电文', purpose: '遇险电文前缀。', format_en: 'MAYDAY MAYDAY MAYDAY', format_zh: '', urgent: 'D', alert: 'H', response: 'Y' },
    { id: '112', category: '紧急电文', purpose: '专门表示航空器遭遇非法干扰。', format_en: 'SQUAWKING 7500', format_zh: '应答编码 7500', urgent: 'U', alert: 'H', response: 'N' },
    { id: '57', category: '紧急电文', purpose: '通知剩余油量和机上人数。', format_en: '(remaining fuel) OF FUEL REMAINING AND (persons on board) PERSONS ON BOARD', format_zh: '剩余的油量(剩余油量)和机上人数(机上人数)', urgent: 'U', alert: 'H', response: 'Y' },
    { id: '58', category: '紧急电文', purpose: '报告飞行员希望取消紧急状况。', format_en: 'CANCEL EMERGENCY', format_zh: '取消紧急状况', urgent: 'U', alert: 'M', response: 'Y' },
    { id: '59', category: '紧急电文', purpose: '报告因紧急需要,航空器经由指定航路改航至指定地点。', format_en: 'DIVERTING TO (position) VIA (route clearance)', format_zh: '改航至(地点)经由(批准航路)', urgent: 'U', alert: 'H', response: 'Y' },
    { id: '60', category: '紧急电文', purpose: '报告因紧急需要,航空器在批准航路指定方向偏离至指定距离,保持平行航迹。', format_en: 'OFFSETTING (specified distance) (direction) OF ROUTE', format_zh: '偏离航路的(方向)(指定距离)', urgent: 'U', alert: 'H', response: 'Y' },
    { id: '61', category: '紧急电文', purpose: '报告因紧急需要,航空器正下降到指定高度层。', format_en: 'DESCENDING TO (level)', format_zh: '下降到(高度层)', urgent: 'U', alert: 'H', response: 'Y' },
    { id: '80', category: '紧急电文', purpose: '通知因紧急需要,航空器在批准航路指定方向偏航至指定距离。', format_en: 'DEVIATING UP TO (specified distance) (direction) OF ROUTE', format_zh: '偏航至航路的(方向)(指定距离)', urgent: 'U', alert: 'H', response: 'Y' },
    // 表 A5-23 系统管理电文
    { id: '62', category: '系统管理电文', purpose: '系统电文—航空电子设备检测发现错误。', format_en: 'ERROR (error information)', format_zh: '错误(错误信息)', urgent: 'U', alert: 'L', response: 'N' },
    { id: '63', category: '系统管理电文', purpose: '系统电文—拒收非当前数据负责单位的地面站发来的 CPDLC 电文。', format_en: 'NOT CURRENT DATA AUTHORITY', format_zh: '非当前数据负责单位', urgent: 'L', alert: 'L', response: 'N' },
    { id: '99', category: '系统管理电文', purpose: '系统电文—通知地面站,现在它是当前数据负责单位。', format_en: 'CURRENT DATA AUTHORITY', format_zh: '当前数据负责单位', urgent: 'L', alert: 'L', response: 'N' },
    { id: '64', category: '系统管理电文', purpose: '通知地面站指定的 ATSU 是当前数据负责单位。', format_en: '(facility designation)', format_zh: '(负责单位代号)', urgent: 'L', alert: 'L', response: 'N' },
    { id: '107', category: '系统管理电文', purpose: '系统电文—通知地面系统,在当前数据负责单位未指定地面系统为NDA时,试图联系一架航空器。', format_en: 'NOT AUTHORIZED NEXT DATA AUTHORITY', format_zh: '无批准的下一数据负责单位', urgent: 'L', alert: 'L', response: 'N' },
    { id: '73', category: '系统管理电文', purpose: '系统电文—表明软件版号。', format_en: '(version number)', format_zh: '(版号)', urgent: 'L', alert: 'L', response: 'N' },
    { id: '100', category: '系统管理电文', purpose: '向地面系统证实,航空器系统收到逻辑认收电文,并认为可接受及向负责人展示。', format_en: 'LOGICAL ACKNOWLEDGEMENT', format_zh: '逻辑认收', urgent: 'N', alert: 'M', response: 'N' },
    // 表 A5-24 间距信息
    { id: '*', category: '间距信息', purpose: '咨询表示驾驶员有高度层更换程序设备,并提供距参照航空器的距离,包括航空器识别。此电文总是连接一个垂直请求。', format_en: 'ITP (distance) BEHIND (aircraft identification of reference aircraft)', format_zh: '(参照航空器的航空器识别代码)后方有高度层更换程序(距离)', urgent: 'N', alert: 'L', response: 'N' },
    { id: '*', category: '间距信息', purpose: '咨询表示驾驶员有高度层更换程序设备,并提供距参照航空器的距离,包括航空器识别。此电文总是连接一个垂直请求。', format_en: 'ITP (distance) AHEAD OF (aircraft identification of reference aircraft)', format_zh: '(参照航空器的航空器识别代码)前方有高度层更换程序(距离)', urgent: 'N', alert: 'L', response: 'N' },
    { id: '*', category: '间距信息', purpose: '咨询表示驾驶员有高度层更换程序设备,并提供距两架参照航空器的距离,包括航空器识别。此电文总是连接一个垂直请求。', format_en: 'ITP (distance) BEHIND (aircraft identification of reference aircraft) AND (distance) BEHIND (aircraft identification of reference aircraft)', format_zh: '(参照航空器的航空器识别代码)后方(距离)和(参照航空器的航空器识别代码)后方有高度层更换程序(距离)', urgent: 'N', alert: 'L', response: 'N' },
    { id: '*', category: '间距信息', purpose: '咨询表示驾驶员有高度层更换程序设备,并提供距两架参照航空器的距离,包括航空器识别。此电文总是连接一个垂直请求。', format_en: 'ITP (distance) AHEAD OF (aircraft identification of reference aircraft) AND (distance) AHEAD OF (aircraft identification of reference aircraft)', format_zh: '(参照航空器的航空器识别代码)前方(距离)和(参照航空器的航空器识别代码)前方有高度层更换程序(距离)', urgent: 'N', alert: 'L', response: 'N' },
    { id: '*', category: '间距信息', purpose: '咨询表示驾驶员有高度层更换程序设备,并提供距一架参照航空器的距离和距另一架参照航空器的距离,包括航空器识别。此电文总是连接一个垂直请求。', format_en: 'ITP (distance) BEHIND (aircraft identification of reference aircraft) AND (distance) AHEAD OF (aircraft identification of reference aircraft)', format_zh: '(参照航空器的航空器识别代码)后方(距离)和(参照航空器的航空器识别代码)前方有高度层更换程序(距离)', urgent: 'N', alert: 'L', response: 'N' },
    // 表 A5-25 其他电文
    { id: '65', category: '其他电文', purpose: '用于解释飞行员电文的理由。', format_en: 'DUE TO WEATHER', format_zh: '因为天气', urgent: 'L', alert: 'L', response: 'N' },
    { id: '66', category: '其他电文', purpose: '用于解释飞行员电文的理由。', format_en: 'DUE TO AIRCRAFT PERFORMANCE', format_zh: '因为航空器性能', urgent: 'L', alert: 'L', response: 'N' },
    { id: '74', category: '其他电文', purpose: '说明飞行员希望自行保持间隔,并保持 VMC。', format_en: 'REQUEST TO MAINTAIN OWN SEPARATION AND VMC', format_zh: '请求自行保持间隔和 VMC', urgent: 'L', alert: 'L', response: 'Y' },
    { id: '75', category: '其他电文', purpose: '和其他电文连用,表示飞行员希望在做好准备时,执行提出的请求。', format_en: 'AT PILOTS DISCRETION', format_zh: '由飞行员决定', urgent: 'L', alert: 'L', response: 'N' },
    { id: '101', category: '其他电文', purpose: '允许飞行员表示希望终止当前数据负责单位的 CPDLC 服务。', format_en: 'REQUEST END OF SERVICE', format_zh: '请求终止服务', urgent: 'L', alert: 'L', response: 'Y' },
    { id: '103', category: '其他电文', purpose: '允许飞行员表明已取消 IFR 飞行计划。', format_en: 'CANCELLING IFR', format_zh: '取消 IFR', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '108', category: '其他电文', purpose: '通知除冰工作结束。', format_en: 'DE-ICING COMPLETE', format_zh: '除冰结束', urgent: 'L', alert: 'L', response: 'N' },
    { id: '67', category: '其他电文', purpose: '(非规定格式电文)', format_en: '(free text)', format_zh: '(非规定格式电文)', urgent: 'N', alert: 'L', response: 'N' },
    { id: '68', category: '其他电文', purpose: '(非规定格式电文)', format_en: '(free text)', format_zh: '(非规定格式电文)', urgent: 'D', alert: 'H', response: 'Y' },
    { id: '90', category: '其他电文', purpose: '(非规定格式电文)', format_en: '(free text)', format_zh: '(非规定格式电文)', urgent: 'N', alert: 'M', response: 'N' },
    { id: '91', category: '其他电文', purpose: '(非规定格式电文)', format_en: '(free text)', format_zh: '(非规定格式电文)', urgent: 'N', alert: 'L', response: 'Y' },
    { id: '92', category: '其他电文', purpose: '(非规定格式电文)', format_en: '(free text)', format_zh: '(非规定格式电文)', urgent: 'L', alert: 'L', response: 'Y' },
    { id: '93', category: '其他电文', purpose: '(非规定格式电文)', format_en: '(free text)', format_zh: '(非规定格式电文)', urgent: 'U', alert: 'H', response: 'N' },
    { id: '94', category: '其他电文', purpose: '(非规定格式电文)', format_en: '(free text)', format_zh: '(非规定格式电文)', urgent: 'D', alert: 'H', response: 'N' },
    { id: '95', category: '其他电文', purpose: '(非规定格式电文)', format_en: '(free text)', format_zh: '(非规定格式电文)', urgent: 'U', alert: 'M', response: 'N' },
    { id: '96', category: '其他电文', purpose: '(非规定格式电文)', format_en: '(free text)', format_zh: '(非规定格式电文)', urgent: 'U', alert: 'L', response: 'N' },
    { id: '97', category: '其他电文', purpose: '(非规定格式电文)', format_en: '(free text)', format_zh: '(非规定格式电文)', urgent: 'L', alert: 'L', response: 'N' },
    { id: '98', category: '其他电文', purpose: '(非规定格式电文)', format_en: '(free text)', format_zh: '(非规定格式电文)', urgent: 'N', alert: 'N', response: 'N' },
    // 表 A5-26 询问回答
    { id: '81', category: '询问回答', purpose: '我们可以在指定时间接受指定高度层。', format_en: 'WE CAN ACCEPT (level) AT (time)', format_zh: '我们可以在(时间)接受(高度层)', urgent: 'L', alert: 'L', response: 'N' },
    { id: '115', category: '询问回答', purpose: '我们可以在指定位置接受指定高度。', format_en: 'WE CAN ACCEPT (level) AT (position)', format_zh: '我们能在(位置)接受(高度)', urgent: 'L', alert: 'L', response: 'N' },
    { id: '82', category: '询问回答', purpose: '我们不能接受指定高度层。', format_en: 'WE CANNOT ACCEPT (level)', format_zh: '我们不能接受(高度层)', urgent: 'L', alert: 'L', response: 'N' },
    { id: '83', category: '询问回答', purpose: '我们能在指定时间接受指定速度。', format_en: 'WE CAN ACCEPT (speed) AT (time)', format_zh: '我们能在(时间)接受(速度)', urgent: 'L', alert: 'L', response: 'N' },
    { id: '116', category: '询问回答', purpose: '我们能在指定位置接受指定速度。', format_en: 'WE CAN ACCEPT (speed) AT (position)', format_zh: '我们能在(位置)接受(速度)', urgent: 'L', alert: 'L', response: 'N' },
    { id: '84', category: '询问回答', purpose: '我们不能接受指定速度。', format_en: 'WE CANNOT ACCEPT (speed)', format_zh: '我们不能接受(速度)', urgent: 'L', alert: 'L', response: 'N' },
    { id: '85', category: '询问回答', purpose: '我们能在指定时间接受偏于指定方向、指定距离的平行航迹。', format_en: 'WE CAN ACCEPT (specified distance) (direction) AT (time)', format_zh: '我们能于(时间)接受(方向)(指定距离)', urgent: 'L', alert: 'L', response: 'N' },
    { id: '117', category: '询问回答', purpose: '我们能在指定位置接受偏于指定方向、指定距离的平行航迹。', format_en: 'WE CAN ACCEPT (specified distance) (direction) AT (position)', format_zh: '我们能在(位置)接受(指定距离)(方向)', urgent: 'L', alert: 'L', response: 'N' },
    { id: '86', category: '询问回答', purpose: '我们不能接受偏于指定方向、指定距离的平行航迹。', format_en: 'WE CANNOT ACCEPT (specified distance) (direction)', format_zh: '我们不能接受(方向)(指定距离)', urgent: 'L', alert: 'L', response: 'N' },
  ],

  // 分类列表(用于筛选)
  categories: {
    uplink: [
      '回答/认收',
      '垂直许可',
      '穿越限制',
      '横向偏离',
      '航路改变',
      '速度变化',
      '联络/监测/监视请求',
      '报告/证实请求',
      '询问请求',
      '空中交通咨询',
      '系统管理电文',
      '间距电文',
      '其他电文'
    ],
    downlink: [
      '回答',
      '垂直请求',
      '横向偏离请求',
      '速度请求',
      '话音联络请求',
      '航路改变请求',
      '报告',
      '询问请求',
      '紧急电文',
      '系统管理电文',
      '间距信息',
      '其他电文',
      '询问回答'
    ]
  }
};

module.exports = cpdlcMessages;