// 应急特情词汇数据
var emergencyGlossaryData = {
  "glossary": [
    {
      "name": "1. 爆炸物威胁 (Explosive Threat)",
      "terms": [
        { "chinese": "爆炸物威胁", "english": "explosive threat" },
        { "chinese": "匿名电话", "english": "anonymous call" },
        { "chinese": "输送带", "english": "conveyor" },
        { "chinese": "紧急撤离", "english": "emergency evacuation" },
        { "chinese": "地面特种车辆", "english": "servicing truck" },
        { "chinese": "逃生滑梯(紧急滑梯)", "english": "escape chute (emergency slides)" },
        { "chinese": "地面电源车", "english": "ground power unit" },
        { "chinese": "拆弹人员", "english": "bomb disposal squad" },
        { "chinese": "救火车", "english": "fire engine" },
        { "chinese": "爆炸", "english": "explode" },
        { "chinese": "救护车", "english": "ambulance" },
        { "chinese": "火焰、燃烧", "english": "flame" },
        { "chinese": "事故处理车", "english": "crash tender" },
        { "chinese": "爆炸物", "english": "explosion" },
        { "chinese": "保安运货车", "english": "security van" },
        { "chinese": "手榴弹", "english": "hand grenade" },
        { "chinese": "除冰车", "english": "ice-melter" },
        { "chinese": "威胁", "english": "threaten" },
        { "chinese": "加油车", "english": "refueller" },
        { "chinese": "恐怖分子", "english": "terrorist" },
        { "chinese": "人质", "english": "hostage" },
        { "chinese": "妥协", "english": "compromise" },
        { "chinese": "迫降", "english": "forced landing" },
        { "chinese": "爆胎", "english": "burst" }
      ]
    },
    {
      "name": "2. 操纵系统故障 (Control System Failure)",
      "terms": [
        { "chinese": "操纵系统故障", "english": "control system failure" },
        { "chinese": "飞行操纵系统", "english": "flight control system" },
        { "chinese": "缝翼", "english": "slat" },
        { "chinese": "操纵系统故障", "english": "control system inoperative" },
        { "chinese": "襟翼", "english": "flap" },
        { "chinese": "反喷装置", "english": "thrust reverser" },
        { "chinese": "扰流板", "english": "spoiler" },
        { "chinese": "操纵手柄", "english": "handles" },
        { "chinese": "无襟翼落地", "english": "a flapless landing" },
        { "chinese": "开关", "english": "switch" },
        { "chinese": "收襟翼", "english": "retract the flaps" },
        { "chinese": "按钮或旋钮", "english": "knobs" },
        { "chinese": "刹车不可靠", "english": "brakes are unreliable" },
        { "chinese": "方向舵", "english": "rudder" },
        { "chinese": "转弯方向盘(前轮)", "english": "steering wheel (front wheel)" },
        { "chinese": "升降舵", "english": "elevator" },
        { "chinese": "襟翼角度", "english": "flap angle" },
        { "chinese": "杆", "english": "lever/stick/column" },
        { "chinese": "俯仰配平", "english": "pitch trim" },
        { "chinese": "平稳", "english": "smooth" },
        { "chinese": "压力传感器", "english": "pressure sensor" },
        { "chinese": "操纵面", "english": "control surface" },
        { "chinese": "配平显示器", "english": "trim indicator" },
        { "chinese": "副翼", "english": "aileron" },
        { "chinese": "脱落", "english": "shed" }
      ]
    },
    {
      "name": "3. 电力系统故障 (Electrical System Failure)",
      "terms": [
        { "chinese": "电力系统故障", "english": "electrical failure" },
        { "chinese": "供电失效", "english": "power supply failure" },
        { "chinese": "短路", "english": "short circuit" },
        { "chinese": "直流发电机", "english": "DC generator" },
        { "chinese": "整流器", "english": "rectifier" },
        { "chinese": "交流发电机", "english": "AC generator" },
        { "chinese": "固态变压器", "english": "solid state transformer" },
        { "chinese": "辅助电源装置", "english": "APU (Auxiliary Power Unit)" },
        { "chinese": "主电门", "english": "main switch" },
        { "chinese": "电线", "english": "wire" },
        { "chinese": "供电", "english": "feeding" },
        { "chinese": "跳开关", "english": "circuit breaker" },
        { "chinese": "电力卸载", "english": "electrical unloading" },
        { "chinese": "接触不良", "english": "loose connection" },
        { "chinese": "整体驱动发电机", "english": "IDG (Integrated Drive Generator)" },
        { "chinese": "电源", "english": "power supply" },
        { "chinese": "变压整流组件", "english": "TRU (Transformer Rectifier Unit)" },
        { "chinese": "瞬时断电", "english": "momentary power failure" },
        { "chinese": "发电机控制组件", "english": "GCU (Generator Control Unit)" },
        { "chinese": "电压表", "english": "voltmeter" },
        { "chinese": "汇流条电源控制组件", "english": "BPCU (Bus Power Control Unit)" },
        { "chinese": "保险丝", "english": "fuse" },
        { "chinese": "连线、引线", "english": "lead" },
        { "chinese": "汇流条", "english": "bus bar" },
        { "chinese": "断开", "english": "disconnect" }
      ]
    },
    {
      "name": "4. 发动机故障 (Engine Failure)",
      "terms": [
        { "chinese": "发动机故障", "english": "engine failure" },
        { "chinese": "吸入飞鸟", "english": "bird ingestion" },
        { "chinese": "发动机喘振", "english": "engine surge" },
        { "chinese": "警告灯闪烁", "english": "warning lights flashing" },
        { "chinese": "超温", "english": "overheat" },
        { "chinese": "增压泵", "english": "boost pump" },
        { "chinese": "发动机起火", "english": "engine on fire" },
        { "chinese": "消防救援", "english": "fire service assistance" },
        { "chinese": "吊舱", "english": "pod" },
        { "chinese": "进气道", "english": "air inlet or intake" },
        { "chinese": "风扇", "english": "fan" },
        { "chinese": "风扇叶片", "english": "fan blade" },
        { "chinese": "压缩机", "english": "compressor" },
        { "chinese": "压缩机叶片", "english": "compressor blade" },
        { "chinese": "喷嘴", "english": "nozzle" },
        { "chinese": "加/减油门", "english": "throttle up/down" },
        { "chinese": "发动机配置", "english": "engine setting" },
        { "chinese": "分裂、爆炸", "english": "disintegrate" },
        { "chinese": "很大的响声", "english": "loud thump" },
        { "chinese": "振动", "english": "vibration" },
        { "chinese": "发动机发出低沉的响声", "english": "low rumble" }
      ]
    },
    {
      "name": "5. 除/防冰系统故障 (De-icing/Anti-icing System Failure)",
      "terms": [
        { "chinese": "除/防冰系统故障", "english": "De-icing/Anti-icing system inoperative" },
        { "chinese": "结冰层(指下限)", "english": "the freezing level" },
        { "chinese": "结冰", "english": "icing" },
        { "chinese": "冻雨", "english": "freezing rain" },
        { "chinese": "防冻液", "english": "anti-icing fluid" },
        { "chinese": "冲水厕所", "english": "flushing toilet" },
        { "chinese": "结冰指示器", "english": "icing indicator" },
        { "chinese": "防冰导管;防冰装置导管", "english": "anti-icing duct" },
        { "chinese": "防冰空气调节器", "english": "anti-icing air regulator" },
        { "chinese": "防冰装置活门", "english": "anti-icing valve" },
        { "chinese": "全静压管除冰装置/空速管防冰器", "english": "pitot de-icer" }
      ]
    },
    {
      "name": "6. 风挡问题 (Windshield Issues)",
      "terms": [
        { "chinese": "风挡", "english": "windshield" },
        { "chinese": "外层风挡破碎", "english": "outer windshield crazed" },
        { "chinese": "内层风挡", "english": "inner windshield" },
        { "chinese": "雨刮器", "english": "wiper" },
        { "chinese": "鸟击", "english": "bird strike" },
        { "chinese": "击碎", "english": "smash" },
        { "chinese": "裂纹", "english": "crack" },
        { "chinese": "粉碎性的破裂", "english": "shatter" },
        { "chinese": "不明外来物", "english": "unknown foreign object" },
        { "chinese": "重击声", "english": "thump" },
        { "chinese": "释压", "english": "depressurization" }
      ]
    },
    {
      "name": "7. 空中失火 (In-flight Fire)",
      "terms": [
        { "chinese": "驾驶舱", "english": "cockpit" },
        { "chinese": "客舱", "english": "passenger cabin" },
        { "chinese": "卫生间", "english": "lavatory" },
        { "chinese": "行李舱", "english": "baggage compartment" },
        { "chinese": "火警", "english": "fire warning" },
        { "chinese": "货舱", "english": "cargo compartment" },
        { "chinese": "灭火器", "english": "fire extinguisher" },
        { "chinese": "明火", "english": "open flame" },
        { "chinese": "逃生滑梯", "english": "emergency slides / escape chutes" },
        { "chinese": "灭火设施", "english": "firefighting equipment" },
        { "chinese": "窒息", "english": "asphyxiation / suffocation" }
      ]
    },
    {
      "name": "8. 劫机 (Hijacking)",
      "terms": [
        { "chinese": "劫机", "english": "hijacking" },
        { "chinese": "劫机者", "english": "hijacker" },
        { "chinese": "威胁", "english": "intimidate / threaten" },
        { "chinese": "过站旅客", "english": "transit passenger" },
        { "chinese": "强迫", "english": "compel / force" },
        { "chinese": "现场指挥员", "english": "ramp controller" },
        { "chinese": "恐怖分子", "english": "terrorist" },
        { "chinese": "人质", "english": "hostage" },
        { "chinese": "定期航班", "english": "scheduled flight" },
        { "chinese": "非定期航班", "english": "non-scheduled flight" },
        { "chinese": "国内航班", "english": "domestic flight" },
        { "chinese": "国际航班", "english": "international flight" },
        { "chinese": "加班飞行", "english": "extra section flight" },
        { "chinese": "包机飞行", "english": "charter flight" },
        { "chinese": "客运飞行", "english": "passenger flight" },
        { "chinese": "货运飞行", "english": "cargo flight" },
        { "chinese": "专机", "english": "special flight" },
        { "chinese": "应急信号", "english": "emergency signal" },
        { "chinese": "乘客安抚", "english": "passenger reassurance" },
        { "chinese": "协商劫机者", "english": "negotiate with hijacker" },
        { "chinese": "防卫措施", "english": "defensive measures" },
        { "chinese": "航空警察", "english": "air marshal" },
        { "chinese": "紧急代码", "english": "emergency code" },
        { "chinese": "应急响应团队", "english": "emergency response team" },
        { "chinese": "控制权转移", "english": "transfer of control" },
        { "chinese": "航空局通知", "english": "aviation authority notification" }
      ]
    },
    {
      "name": "9. 雷达失效 (Radar Failure)",
      "terms": [
        { "chinese": "一次监视雷达", "english": "primary surveillance radar (PSR)" },
        { "chinese": "航空器接近", "english": "aircraft proximity" },
        { "chinese": "精密进近雷达", "english": "precision approach radar (PAR)" },
        { "chinese": "雷达干扰", "english": "radar clutter" },
        { "chinese": "二次监视雷达", "english": "secondary surveillance radar (SSR)" },
        { "chinese": "雷达看到", "english": "radar contact" },
        { "chinese": "场面监视雷达", "english": "airport surveillance radar (ASR)" },
        { "chinese": "雷达识别", "english": "identified" },
        { "chinese": "雷达位置指示", "english": "radar position indication (RPI)" },
        { "chinese": "(强制)报告点", "english": "(compulsory) reporting point" },
        { "chinese": "雷达位置符号", "english": "radar position symbol (RPS)" },
        { "chinese": "重要点", "english": "significant point" },
        { "chinese": "一次监视雷达回波", "english": "PSR blip" },
        { "chinese": "航路点(for RNAV)", "english": "way point" },
        { "chinese": "二次监视雷达应答", "english": "SSR response" },
        { "chinese": "雷达间隔/非雷达间隔", "english": "radar separation/non-radar separation" }
      ]
    },
    {
      "name": "10. 起落架问题 (Landing Gear Issues)",
      "terms": [
        { "chinese": "起落架问题", "english": "landing gear issue" },
        { "chinese": "卡阻", "english": "jam" },
        { "chinese": "起落架锁定", "english": "gear locked" },
        { "chinese": "低空通场", "english": "low pass" },
        { "chinese": "轮舱门", "english": "wheel door" },
        { "chinese": "爆破", "english": "burst" },
        { "chinese": "放了气的轮胎", "english": "flat (deflated) tyre" },
        { "chinese": "放下/收起", "english": "extend/retract" },
        { "chinese": "刺孔", "english": "puncture" },
        { "chinese": "连续起落,触地拉升", "english": "touch and go" },
        { "chinese": "人工放下起落架", "english": "crank the gear down" },
        { "chinese": "放油", "english": "fuel dumping" },
        { "chinese": "将轮子震动放下", "english": "jar the wheel down" },
        { "chinese": "改航", "english": "divert" },
        { "chinese": "折断", "english": "collapsed" },
        { "chinese": "喷洒", "english": "spray" },
        { "chinese": "机腹着陆", "english": "belly landing" },
        { "chinese": "收起落架着陆", "english": "gear up landing" },
        { "chinese": "泡沫毯", "english": "foam carpet" },
        { "chinese": "检查起落架", "english": "gear check" }
      ]
    },
    {
      "name": "11. 燃油问题 (Fuel Issues)",
      "terms": [
        { "chinese": "燃油问题", "english": "fuel issue" },
        { "chinese": "低油压警告", "english": "low fuel pressure warning" },
        { "chinese": "燃油泄漏", "english": "fuel leak" },
        { "chinese": "重力加油泵", "english": "gravity filler" },
        { "chinese": "喷油嘴", "english": "blow pipe" },
        { "chinese": "单向阀门", "english": "one-way valve" },
        { "chinese": "通气孔", "english": "vent" },
        { "chinese": "热过滤器", "english": "heated filter" },
        { "chinese": "烧尽燃油(在等待着陆时)", "english": "burn off fuel" },
        { "chinese": "移动加油车", "english": "mobile tanker" },
        { "chinese": "接通应急燃油系统", "english": "select emergency fuel" },
        { "chinese": "机场固定加油栓", "english": "fixed airport fuel hydrant" },
        { "chinese": "燃油管路", "english": "fuel lines" },
        { "chinese": "燃油消耗率", "english": "the rate of fuel consumption" },
        { "chinese": "接头", "english": "joints" },
        { "chinese": "放掉燃油", "english": "decant (dump) fuel" },
        { "chinese": "燃油续航能力", "english": "fuel endurance" },
        { "chinese": "油箱", "english": "fuel tanks" },
        { "chinese": "油泵", "english": "fuel pump" },
        { "chinese": "放油阀", "english": "dump valves" },
        { "chinese": "流量表", "english": "fuel flow indicators" }
      ]
    },
    {
      "name": "12. 防疫 (Epidemic Prevention)",
      "terms": [
        { "chinese": "呼吸机", "english": "respirator" },
        { "chinese": "传染病", "english": "epidemic" },
        { "chinese": "症状", "english": "symptom" },
        { "chinese": "肺炎疫情", "english": "pneumonia situation" },
        { "chinese": "胸闷", "english": "chest tightness" },
        { "chinese": "新型冠状病毒", "english": "novel coronavirus" },
        { "chinese": "咳嗽", "english": "cough" },
        { "chinese": "确诊病例", "english": "confirmed case" },
        { "chinese": "眩晕", "english": "dizziness" },
        { "chinese": "疑似病例", "english": "suspected case" },
        { "chinese": "恶心", "english": "nausea" },
        { "chinese": "密切接触者", "english": "close contacts" },
        { "chinese": "发冷", "english": "ague" },
        { "chinese": "重症", "english": "critical conditions" },
        { "chinese": "腹泻", "english": "diarrhea" },
        { "chinese": "轻症", "english": "mild case" },
        { "chinese": "检验检疫部", "english": "inspection and quarantine department" },
        { "chinese": "体温异常", "english": "abnormal body temperature" },
        { "chinese": "体温筛查", "english": "temperature screening" },
        { "chinese": "疾控中心", "english": "center for disease control and prevention" },
        { "chinese": "疫苗", "english": "vaccine" },
        { "chinese": "医学观察", "english": "medical observation" },
        { "chinese": "一级应急响应", "english": "first-level emergency response" },
        { "chinese": "医疗援助", "english": "medical assistance" },
        { "chinese": "解除隔离", "english": "be discharged" },
        { "chinese": "诊断", "english": "diagnose" },
        { "chinese": "消毒", "english": "disinfect" },
        { "chinese": "医学检查", "english": "medical inspection" }
      ]
    },
    {
      "name": "13. 鸟击 (Bird Strike)",
      "terms": [
        { "chinese": "鸟击", "english": "bird strike" },
        { "chinese": "航班延误", "english": "flight delay" },
        { "chinese": "航班取消", "english": "flight cancellation" },
        { "chinese": "应急着陆", "english": "emergency landing" },
        { "chinese": "飞机外观检查", "english": "visual inspection of aircraft" },
        { "chinese": "引擎检查", "english": "engine inspection" },
        { "chinese": "引擎性能测试", "english": "engine performance test" },
        { "chinese": "损伤评估", "english": "damage assessment" },
        { "chinese": "维修工作", "english": "maintenance work" },
        { "chinese": "替换受损部件", "english": "replacement of damaged parts" },
        { "chinese": "航班重新排班", "english": "flight rescheduling" },
        { "chinese": "防鸟措施", "english": "bird deterrent measures" },
        { "chinese": "飞行员报告", "english": "pilot report" },
        { "chinese": "航空局通知", "english": "aviation authority notification" },
        { "chinese": "客舱乘务员报告", "english": "cabin crew report" }
      ]
    },
    {
      "name": "14. 烟雾 (Smoke)",
      "terms": [
        { "chinese": "烟雾", "english": "smoke" },
        { "chinese": "应急氧气面罩", "english": "emergency oxygen masks" },
        { "chinese": "烟雾探测器", "english": "smoke detectors" },
        { "chinese": "通风系统故障", "english": "ventilation system failure" },
        { "chinese": "空气循环", "english": "air circulation" },
        { "chinese": "火警测试", "english": "fire alarm test" },
        { "chinese": "客舱烟雾", "english": "cabin smoke" },
        { "chinese": "电气火灾", "english": "electrical fire" },
        { "chinese": "灭火器", "english": "fire extinguisher" },
        { "chinese": "烟雾清除", "english": "smoke clearance" },
        { "chinese": "乘客疏散", "english": "passenger evacuation" },
        { "chinese": "客舱检查", "english": "cabin inspection" },
        { "chinese": "维修和检查", "english": "maintenance and inspection" },
        { "chinese": "应急响应计划", "english": "emergency response plan" }
      ]
    },
    {
      "name": "15. 中断起飞 (Aborted Takeoff)",
      "terms": [
        { "chinese": "中断起飞", "english": "aborted takeoff" },
        { "chinese": "制动系统", "english": "braking system" },
        { "chinese": "紧急制动", "english": "emergency braking" },
        { "chinese": "起飞滑跑", "english": "takeoff roll" },
        { "chinese": "起飞中断决策速度", "english": "decision speed (V1)" },
        { "chinese": "起飞安全速度", "english": "takeoff safety speed (V2)" },
        { "chinese": "失速速度", "english": "stall speed" },
        { "chinese": "返回登机口", "english": "return to gate" },
        { "chinese": "起飞程序重置", "english": "takeoff procedure reset" },
        { "chinese": "跑道检查", "english": "runway inspection" },
        { "chinese": "起飞延误", "english": "takeoff delay" },
        { "chinese": "机场运行控制", "english": "airport operations control" },
        { "chinese": "机械故障", "english": "mechanical failure" },
        { "chinese": "气象条件", "english": "weather conditions" },
        { "chinese": "飞行员判断", "english": "pilot judgment" },
        { "chinese": "安全检查", "english": "safety check" },
        { "chinese": "重新起飞", "english": "takeoff resume" }
      ]
    },
    {
      "name": "16. 应急撤离 (Emergency Evacuation)",
      "terms": [
        { "chinese": "应急撤离", "english": "emergency evacuation" },
        { "chinese": "滑梯", "english": "slide" },
        { "chinese": "安全出口", "english": "emergency exit" },
        { "chinese": "客舱乘务长指令", "english": "cabin crew instructions" },
        { "chinese": "避免恐慌", "english": "avoid panic" },
        { "chinese": "集合点", "english": "assembly point" },
        { "chinese": "逃生口", "english": "escape hatch" },
        { "chinese": "乘客疏散", "english": "passenger evacuation" },
        { "chinese": "应急照明", "english": "emergency lighting" },
        { "chinese": "逃生路径标记", "english": "escape path marking" },
        { "chinese": "安全带解锁", "english": "seat belt release" },
        { "chinese": "防冲击姿势", "english": "brace position" },
        { "chinese": "撤离指令", "english": "evacuation command" },
        { "chinese": "逃生窗", "english": "escape window" },
        { "chinese": "紧急通信设备", "english": "emergency communication devices" },
        { "chinese": "客舱安全检查", "english": "cabin safety check" },
        { "chinese": "防烟面罩", "english": "smoke hood" }
      ]
    }
  ]
};

module.exports = {
  emergencyGlossary: emergencyGlossaryData
};