// 日常运行常用词汇数据
var routineGlossaryData = {
  "glossary": [
    {
      "name": "1. 旅客服务 (Passenger Services)",
      "terms": [
        { "chinese": "值机", "english": "check-in" },
        { "chinese": "值机柜台", "english": "check-in counter" },
        { "chinese": "自助值机", "english": "self-service check-in / kiosk" },
        { "chinese": "网上值机", "english": "online check-in / web check-in" },
        { "chinese": "登机牌", "english": "boarding pass" },
        { "chinese": "电子登机牌", "english": "electronic boarding pass / mobile boarding pass" },
        { "chinese": "登机口", "english": "gate / boarding gate" },
        { "chinese": "登机时间", "english": "boarding time" },
        { "chinese": "开始登机", "english": "boarding has started / now boarding" },
        { "chinese": "停止登机", "english": "gate closed / boarding closed" },
        { "chinese": "登机顺序", "english": "boarding sequence / priority boarding" },
        { "chinese": "预留座位", "english": "seat reservation" },
        { "chinese": "托运行李", "english": "checked baggage / check-in luggage" },
        { "chinese": "手提行李", "english": "carry-on baggage / hand luggage / cabin baggage" },
        { "chinese": "行李限额", "english": "baggage allowance" },
        { "chinese": "行李超重", "english": "excess baggage / overweight baggage" },
        { "chinese": "行李超重费", "english": "excess baggage charge" },
        { "chinese": "行李丢失", "english": "lost baggage / missing baggage" },
        { "chinese": "行李延误", "english": "delayed baggage" },
        { "chinese": "行李损坏", "english": "damaged baggage" },
        { "chinese": "行李标签", "english": "baggage tag / luggage tag" },
        { "chinese": "行李提取", "english": "baggage claim / baggage reclaim" },
        { "chinese": "行李查询", "english": "baggage inquiry / baggage tracing" },
        { "chinese": "行李转盘", "english": "baggage carousel / luggage carousel" },
        { "chinese": "失物招领", "english": "lost and found" },
        { "chinese": "安检", "english": "security check / security screening" },
        { "chinese": "安检通道", "english": "security checkpoint" },
        { "chinese": "出发大厅", "english": "departure hall / departure lounge" },
        { "chinese": "到达大厅", "english": "arrival hall / arrivals" },
        { "chinese": "候机楼", "english": "terminal / passenger terminal" },
        { "chinese": "候机室", "english": "departure lounge / waiting area" },
        { "chinese": "贵宾休息室", "english": "VIP lounge / premium lounge" },
        { "chinese": "中转旅客", "english": "transfer passenger / connecting passenger" },
        { "chinese": "过境旅客", "english": "transit passenger" },
        { "chinese": "联程航班", "english": "connecting flight" },
        { "chinese": "航班延误", "english": "flight delay" },
        { "chinese": "航班取消", "english": "flight cancellation" },
        { "chinese": "航班备降", "english": "flight diversion" },
        { "chinese": "航班返航", "english": "return to origin / air turnback" },
        { "chinese": "登机口变更", "english": "gate change" },
        { "chinese": "最终登机广播", "english": "final call / final boarding call" },
        { "chinese": "客舱广播", "english": "cabin announcement / public address (PA)" },
        { "chinese": "改签", "english": "rebooking / change of reservation" },
        { "chinese": "退票", "english": "refund / ticket cancellation" },
        { "chinese": "不正常旅客", "english": "unruly passenger / disruptive passenger" },
        { "chinese": "醉酒旅客", "english": "intoxicated passenger" },
        { "chinese": "座位分配", "english": "seat assignment" },
        { "chinese": "靠窗座位", "english": "window seat" },
        { "chinese": "靠走廊座位", "english": "aisle seat" },
        { "chinese": "中间座位", "english": "middle seat" },
        { "chinese": "紧急出口座位", "english": "emergency exit row seat" },
        { "chinese": "升舱", "english": "upgrade" },
        { "chinese": "超售", "english": "overbooking" },
        { "chinese": "拒绝登机", "english": "denied boarding" },
        { "chinese": "误机", "english": "missed flight / no-show" },
        { "chinese": "特殊餐食申请", "english": "special meal request" },
        { "chinese": "旅客意见表", "english": "passenger feedback form" },
        { "chinese": "常旅客计划", "english": "frequent flyer program / mileage program" },
        { "chinese": "里程累积", "english": "mileage accrual / earn miles" },
        { "chinese": "里程兑换", "english": "mileage redemption / redeem miles" }
      ]
    },
    {
      "name": "2. 地面保障 (Ground Handling)",
      "terms": [
        { "chinese": "地面服务", "english": "ground services / ground handling" },
        { "chinese": "停机坪", "english": "apron / ramp" },
        { "chinese": "机位分配", "english": "stand allocation / gate assignment" },
        { "chinese": "地面电源车", "english": "Ground Power Unit (GPU)" },
        { "chinese": "空调车", "english": "Air Conditioning Unit (ACU)" },
        { "chinese": "气源车", "english": "Air Start Unit (ASU)" },
        { "chinese": "牵引车", "english": "pushback tug / tow tractor" },
        { "chinese": "顶推", "english": "pushback" },
        { "chinese": "客梯车", "english": "passenger steps / stairs / air stairs" },
        { "chinese": "传送带车", "english": "belt loader" },
        { "chinese": "加油车", "english": "refueller / fuel tanker / fuel truck" },
        { "chinese": "加油", "english": "refuelling / fueling" },
        { "chinese": "清水车", "english": "potable water truck" },
        { "chinese": "污水车", "english": "lavatory service vehicle / waste disposal truck" },
        { "chinese": "除冰/防冰车", "english": "de-icing / anti-icing vehicle" },
        { "chinese": "除冰液", "english": "de-icing fluid" },
        { "chinese": "防冰液", "english": "anti-icing fluid" },
        { "chinese": "餐饮车", "english": "catering truck / catering vehicle" },
        { "chinese": "配餐", "english": "catering / meal loading" },
        { "chinese": "客舱清洁", "english": "cabin cleaning" },
        { "chinese": "机外清洁", "english": "aircraft washing / exterior cleaning" },
        { "chinese": "轮挡", "english": "wheel chocks (chocks in / chocks off)" },
        { "chinese": "安全锥", "english": "safety cones / traffic cones" },
        { "chinese": "行李拖车", "english": "baggage cart / baggage trailer" },
        { "chinese": "行李装载", "english": "baggage loading" },
        { "chinese": "机务人员", "english": "ground mechanic / ground engineer / line maintenance" },
        { "chinese": "装卸监督", "english": "loading supervisor / ramp supervisor" },
        { "chinese": "机务耳机通讯", "english": "headset communication / interphone" },
        { "chinese": "绕机检查", "english": "walk-around check / exterior inspection" },
        { "chinese": "引导人员", "english": "marshaller / wing walker" },
        { "chinese": "地面服务协议", "english": "ground handling agreement" },
        { "chinese": "过站服务", "english": "turnaround services" }
      ]
    },
    {
      "name": "3. 飞行准备与离港 (Flight Preparation & Departure)",
      "terms": [
        { "chinese": "飞行前准备", "english": "pre-flight preparation" },
        { "chinese": "飞行计划", "english": "flight plan" },
        { "chinese": "飞行计划修改", "english": "flight plan amendment" },
        { "chinese": "油量计划", "english": "fuel planning" },
        { "chinese": "备降场", "english": "alternate airport / alternate aerodrome" },
        { "chinese": "放行许可", "english": "clearance / ATC clearance" },
        { "chinese": "离港许可", "english": "departure clearance" },
        { "chinese": "起飞许可", "english": "takeoff clearance" },
        { "chinese": "通播 (自动航站信息服务)", "english": "ATIS (Automatic Terminal Information Service)" },
        { "chinese": "推出和开车", "english": "pushback and startup / pushback and engine start" },
        { "chinese": "滑行", "english": "taxi / taxiing" },
        { "chinese": "滑行道", "english": "taxiway" },
        { "chinese": "快速脱离道", "english": "high-speed exit / rapid exit taxiway" },
        { "chinese": "跑道外等待", "english": "hold short of runway" },
        { "chinese": "上跑道并等待", "english": "line up and wait (LUAW)" },
        { "chinese": "跑道占用", "english": "runway incursion" },
        { "chinese": "重量和平衡", "english": "weight and balance" },
        { "chinese": "载重表", "english": "load sheet / loadsheet" },
        { "chinese": "预计撤轮挡时间", "english": "Estimated Off-Block Time (EOBT)" },
        { "chinese": "实际撤轮挡时间", "english": "Actual Off-Block Time (AOBT)" },
        { "chinese": "预计起飞时间", "english": "Estimated Time of Departure (ETD)" },
        { "chinese": "实际起飞时间", "english": "Actual Time of Departure (ATD)" },
        { "chinese": "离港时刻", "english": "slot time / departure slot / CTOT (Calculated Take-Off Time)" },
        { "chinese": "流量控制", "english": "flow control / ATFM (Air Traffic Flow Management)" },
        { "chinese": "有效载荷", "english": "payload" },
        { "chinese": "无燃油重量", "english": "Zero Fuel Weight (ZFW)" },
        { "chinese": "起飞全重", "english": "Takeoff Weight (TOW)" },
        { "chinese": "最大起飞重量", "english": "Maximum Takeoff Weight (MTOW)" },
        { "chinese": "业载", "english": "traffic load / commercial load" },
        { "chinese": "签派", "english": "flight dispatch / dispatcher" },
        { "chinese": "签派放行", "english": "dispatch release" },
        { "chinese": "性能计算", "english": "performance calculation" },
        { "chinese": "起飞性能", "english": "takeoff performance" },
        { "chinese": "V1速度", "english": "decision speed (V1)" },
        { "chinese": "VR速度", "english": "rotation speed (VR)" },
        { "chinese": "V2速度", "english": "takeoff safety speed (V2)" }
      ]
    },
    {
      "name": "4. 进港与过站 (Arrival & Transit)",
      "terms": [
        { "chinese": "进近", "english": "approach" },
        { "chinese": "进近许可", "english": "approach clearance" },
        { "chinese": "落地许可", "english": "landing clearance" },
        { "chinese": "复飞", "english": "go-around / missed approach" },
        { "chinese": "接地", "english": "touchdown" },
        { "chinese": "脱离跑道", "english": "vacate the runway / clear the runway" },
        { "chinese": "停机位", "english": "parking stand / bay / gate" },
        { "chinese": "廊桥", "english": "jet bridge / aerobridge / passenger boarding bridge" },
        { "chinese": "远机位", "english": "remote stand / remote bay" },
        { "chinese": "摆渡车", "english": "shuttle bus / apron bus" },
        { "chinese": "引导车", "english": "follow-me car / lead-in vehicle" },
        { "chinese": "引导员", "english": "marshaller / parking guide" },
        { "chinese": "实际到达时间", "english": "Actual Time of Arrival (ATA)" },
        { "chinese": "预计上轮挡时间", "english": "Estimated In-Block Time (EIBT)" },
        { "chinese": "实际上轮挡时间", "english": "Actual In-Block Time (AIBT)" },
        { "chinese": "下客", "english": "disembarkation / disembarking / deplaning" },
        { "chinese": "上客", "english": "boarding / embarkation" },
        { "chinese": "过站检查", "english": "transit check / through check" },
        { "chinese": "过站时间", "english": "turnaround time / ground time" },
        { "chinese": "快速过站", "english": "quick turnaround / rapid turnaround" },
        { "chinese": "航后检查", "english": "post-flight inspection / after-flight check" },
        { "chinese": "机组过夜", "english": "crew remain overnight (RON)" },
        { "chinese": "机组休息", "english": "crew rest / crew layover" },
        { "chinese": "到达准备", "english": "arrival preparation / descent preparation" },
        { "chinese": "着陆性能", "english": "landing performance" },
        { "chinese": "落地重量", "english": "landing weight" },
        { "chinese": "最大落地重量", "english": "Maximum Landing Weight (MLW)" }
      ]
    },
    {
      "name": "5. 特殊旅客 (Special Passengers)",
      "terms": [
        { "chinese": "无人陪伴儿童", "english": "Unaccompanied Minor (UMNR)" },
        { "chinese": "轮椅旅客(可上楼梯)", "english": "Wheelchair (Ramp) - WCHR" },
        { "chinese": "轮椅旅客(不能上楼梯)", "english": "Wheelchair (Steps) - WCHS" },
        { "chinese": "轮椅旅客(完全无法移动)", "english": "Wheelchair (Cabin seat) - WCHC" },
        { "chinese": "担架旅客", "english": "Stretcher Passenger (STCR)" },
        { "chinese": "盲人旅客", "english": "Blind Passenger (BLND)" },
        { "chinese": "聋哑旅客", "english": "Deaf Passenger (DEAF)" },
        { "chinese": "需要医疗证明的旅客", "english": "Medical Case (MEDA)" },
        { "chinese": "智力或发育障碍旅客", "english": "Disabled Passenger with Intellectual or Developmental Disability (DPNA)" },
        { "chinese": "携带服务犬的旅客", "english": "Passenger with a service animal" },
        { "chinese": "遣返人员(有人押送)", "english": "Deportee (accompanied) - DEPA" },
        { "chinese": "遣返人员(无人押送)", "english": "Deportee (unaccompanied) - DEPU" },
        { "chinese": "重要旅客", "english": "Very Important Person (VIP)" }
      ]
    },
    {
      "name": "6. 海关与边防 (Customs & Immigration)",
      "terms": [
        { "chinese": "遣返", "english": "deportation" },
        { "chinese": "不予入境旅客", "english": "inadmissible passenger (INAD)" },
        { "chinese": "护照", "english": "passport" },
        { "chinese": "签证", "english": "visa" },
        { "chinese": "机组签证", "english": "crew visa (e.g., C1/D visa)" },
        { "chinese": "海关申报", "english": "customs declaration" },
        { "chinese": "边防检查", "english": "immigration control" },
        { "chinese": "总申报单", "english": "General Declaration (Gen Dec)" },
        { "chinese": "旅客名单", "english": "Passenger Manifest" },
        { "chinese": "机组名单", "english": "Crew Manifest" },
        { "chinese": "预先旅客信息系统", "english": "Advance Passenger Information System (APIS)" },
        { "chinese": "检疫", "english": "quarantine" },
        { "chinese": "飞机消毒", "english": "aircraft disinsection" },
        { "chinese": "免税品", "english": "duty-free goods" }
      ]
    },
    {
      "name": "7. 机务与维修 (Aircraft Maintenance)",
      "terms": [
        { "chinese": "技术记录本", "english": "Technical Log Book (TLB)" },
        { "chinese": "客舱记录本", "english": "Cabin Log Book (CLB)" },
        { "chinese": "最低设备清单", "english": "Minimum Equipment List (MEL)" },
        { "chinese": "保留故障", "english": "deferred defect / carry forward item" },
        { "chinese": "禁止起飞项目", "english": "no-go item" },
        { "chinese": "适航", "english": "airworthy / serviceable" },
        { "chinese": "故障排除", "english": "troubleshooting" },
        { "chinese": "零部件更换", "english": "part replacement" },
        { "chinese": "轮胎压力", "english": "tire pressure" },
        { "chinese": "滑油添加", "english": "oil servicing / uplift" },
        { "chinese": "液压油", "english": "hydraulic fluid" },
        { "chinese": "放行签字", "english": "maintenance release signature" },
        { "chinese": "飞机停场", "english": "Aircraft on Ground (AOG)" }
      ]
    },
    {
      "name": "8. 客舱服务与管理 (Cabin Service & Management)",
      "terms": [
        { "chinese": "客舱乘务员", "english": "flight attendant / cabin crew" },
        { "chinese": "乘务长", "english": "purser / senior cabin crew member / cabin manager" },
        { "chinese": "客舱安全演示", "english": "safety demonstration / safety briefing" },
        { "chinese": "安全须知卡", "english": "safety instruction card / safety card" },
        { "chinese": "救生衣", "english": "life vest / life jacket" },
        { "chinese": "氧气面罩", "english": "oxygen mask" },
        { "chinese": "紧急出口", "english": "emergency exit" },
        { "chinese": "驾驶舱呼叫", "english": "flight deck call / cockpit call" },
        { "chinese": "客舱准备就绪", "english": "cabin ready for takeoff/landing / cabin secure" },
        { "chinese": "餐饮供应", "english": "catering supplies / meal service" },
        { "chinese": "餐车", "english": "meal cart / service cart / trolley" },
        { "chinese": "免税品销售", "english": "duty-free sales" },
        { "chinese": "客舱温度调节", "english": "cabin temperature adjustment" },
        { "chinese": "客舱增压", "english": "cabin pressurization" },
        { "chinese": "饮用水量", "english": "potable water quantity" },
        { "chinese": "旅客座位号", "english": "passenger seat number" },
        { "chinese": "系好安全带", "english": "fasten seatbelt / seatbelt fastened" },
        { "chinese": "颠簸时系好安全带", "english": "fasten seatbelt for turbulence" },
        { "chinese": "安全带指示灯", "english": "seatbelt sign" },
        { "chinese": "禁止吸烟", "english": "no smoking" },
        { "chinese": "驾驶舱准入许可", "english": "cockpit entry permission / flight deck access" },
        { "chinese": "客舱灯光", "english": "cabin lighting" },
        { "chinese": "阅读灯", "english": "reading light" },
        { "chinese": "机上娱乐系统", "english": "In-Flight Entertainment (IFE) system" },
        { "chinese": "呼叫按钮", "english": "call button / attendant call" },
        { "chinese": "洗手间", "english": "lavatory / restroom / washroom" },
        { "chinese": "洗手间占用", "english": "lavatory occupied" },
        { "chinese": "小桌板", "english": "tray table" },
        { "chinese": "座椅靠背", "english": "seat back / backrest" },
        { "chinese": "客舱行李架", "english": "overhead bin / overhead compartment" },
        { "chinese": "机上医疗事件", "english": "in-flight medical incident" },
        { "chinese": "急救箱", "english": "first aid kit" },
        { "chinese": "医疗包", "english": "medical kit" },
        { "chinese": "自动体外除颤器", "english": "Automated External Defibrillator (AED)" }
      ]
    },
    {
      "name": "9. 飞行运行与航路 (Flight Operations & Enroute)",
      "terms": [
        { "chinese": "空中交通管制", "english": "Air Traffic Control (ATC)" },
        { "chinese": "管制员", "english": "air traffic controller" },
        { "chinese": "区域管制", "english": "Area Control Centre (ACC) / en-route control" },
        { "chinese": "进近管制", "english": "Approach Control (APP)" },
        { "chinese": "塔台管制", "english": "Tower Control (TWR)" },
        { "chinese": "地面管制", "english": "Ground Control (GND)" },
        { "chinese": "放行许可席位", "english": "Clearance Delivery" },
        { "chinese": "飞行高度层", "english": "flight level (FL)" },
        { "chinese": "航向", "english": "heading" },
        { "chinese": "磁航向", "english": "magnetic heading" },
        { "chinese": "真航向", "english": "true heading" },
        { "chinese": "航迹", "english": "track" },
        { "chinese": "航路", "english": "airway / route" },
        { "chinese": "航路点", "english": "waypoint / fix" },
        { "chinese": "预计到达时间", "english": "Estimated Time of Arrival (ETA)" },
        { "chinese": "预计飞越时间", "english": "Estimated Time Over (ETO)" },
        { "chinese": "直飞", "english": "direct to / proceed direct" },
        { "chinese": "天气绕航", "english": "weather deviation / deviation for weather" },
        { "chinese": "改变高度", "english": "change of level / level change" },
        { "chinese": "上升", "english": "climb / climbing" },
        { "chinese": "下降", "english": "descend / descent / descending" },
        { "chinese": "巡航", "english": "cruise / cruising" },
        { "chinese": "平飞", "english": "level off / maintaining level" },
        { "chinese": "转向", "english": "turn / heading change" },
        { "chinese": "左转", "english": "turn left" },
        { "chinese": "右转", "english": "turn right" },
        { "chinese": "盘旋等待", "english": "holding / hold" },
        { "chinese": "等待程序", "english": "holding pattern" },
        { "chinese": "颠簸", "english": "turbulence" },
        { "chinese": "颠簸报告", "english": "turbulence report / PIREP (Pilot Report)" },
        { "chinese": "轻度颠簸", "english": "light turbulence" },
        { "chinese": "中度颠簸", "english": "moderate turbulence" },
        { "chinese": "严重颠簸", "english": "severe turbulence" },
        { "chinese": "风切变", "english": "wind shear / windshear" },
        { "chinese": "积冰", "english": "icing" },
        { "chinese": "收到", "english": "Roger / received" },
        { "chinese": "明白，照做", "english": "Wilco (Will Comply)" },
        { "chinese": "请重复", "english": "Say again / repeat" },
        { "chinese": "等待", "english": "Standby / stand by" },
        { "chinese": "确认", "english": "Affirm / affirmative" },
        { "chinese": "否定", "english": "Negative" },
        { "chinese": "无法执行", "english": "Unable" },
        { "chinese": "请求", "english": "Request" },
        { "chinese": "报告", "english": "Report" },
        { "chinese": "保持", "english": "Maintain" },
        { "chinese": "继续", "english": "Continue" }
      ]
    },
    {
      "name": "10. 行李与货物 (Baggage & Cargo)",
      "terms": [
        { "chinese": "航空货运", "english": "air cargo / air freight" },
        { "chinese": "航空货运单", "english": "Air Waybill (AWB)" },
        { "chinese": "货运代理", "english": "freight forwarder / cargo agent" },
        { "chinese": "集装设备", "english": "Unit Load Device (ULD)" },
        { "chinese": "集装箱", "english": "container" },
        { "chinese": "集装板", "english": "pallet" },
        { "chinese": "散货", "english": "bulk cargo / loose cargo" },
        { "chinese": "货舱", "english": "cargo hold / cargo compartment" },
        { "chinese": "前货舱", "english": "forward cargo hold" },
        { "chinese": "后货舱", "english": "aft cargo hold" },
        { "chinese": "散货舱", "english": "bulk cargo hold" },
        { "chinese": "优先行李", "english": "priority baggage / priority tag" },
        { "chinese": "超大行李", "english": "oversized baggage / bulky baggage" },
        { "chinese": "超重行李", "english": "overweight baggage" },
        { "chinese": "超尺寸行李", "english": "over-dimension baggage" },
        { "chinese": "运动器材", "english": "sports equipment" },
        { "chinese": "乐器", "english": "musical instrument" },
        { "chinese": "宠物运输", "english": "pet transportation" },
        { "chinese": "易碎品", "english": "fragile items" },
        { "chinese": "贵重物品", "english": "valuable items / valuables" },
        { "chinese": "鲜活易腐货物", "english": "perishable cargo / perishables" },
        { "chinese": "活体动物", "english": "live animals (AVI)" },
        { "chinese": "人体遗骸", "english": "human remains (HUM)" },
        { "chinese": "外交邮袋", "english": "diplomatic bag / diplomatic pouch" },
        { "chinese": "邮件", "english": "mail" },
        { "chinese": "危险品", "english": "dangerous goods (DG) / hazardous materials (HAZMAT)" },
        { "chinese": "限制物品", "english": "restricted articles" },
        { "chinese": "禁运物品", "english": "prohibited items / forbidden items" },
        { "chinese": "装载计划", "english": "load plan / loading plan" },
        { "chinese": "配载平衡", "english": "load distribution / load balance" },
        { "chinese": "最后一刻变更", "english": "last minute change (LMC)" },
        { "chinese": "货物舱单", "english": "cargo manifest" },
        { "chinese": "转运货物", "english": "transfer cargo / transit cargo" },
        { "chinese": "直达货物", "english": "through cargo" },
        { "chinese": "温控货物", "english": "temperature controlled cargo" },
        { "chinese": "冷藏货物", "english": "refrigerated cargo" },
        { "chinese": "货物装载监督", "english": "cargo loading supervisor" }
      ]
    }
  ]
};

module.exports = {
  routineGlossary: routineGlossaryData
};