graph TD
    A[地空双向通信失效] --> B(设定应答机编码7600);
    B --> C{选择飞行路径意图};

    C -- "一般程序: 飞往目的地" --> D{所在空域类型};
    D -- "监视管制服务空域" --> E[保持最后指定速度和高度<br>飞行7分钟];
    D -- "非监视管制服务空域" --> F[保持最后指定速度和高度<br>飞行20分钟];
    E --> G[按飞行计划调整速度和高度];
    F --> G;
    G --> H[按现行飞行计划航路<br>飞至目的地导航设备或定位点等待];
    H --> I[按最后确认的EAT或FPL的ETA<br>开始下降];
    I --> J[完成正常仪表进近];
    J --> K[在EAT/ETA后30分钟内着陆];

    C -- "其他意图(仅限监视空域)" --> L{具体意图};
    L -- "返回起飞机场" --> M[交替设置7600/7601<br>2次, 最终设为7600];
    M --> N[飞完SID后就近选择STAR返场];
    
    L -- "飞往起飞备降场" --> O[交替设置7600/7602<br>2次, 最终设为7600];
    O --> P[飞完SID后沿常规航路飞行];

    L -- "飞往目的地备降场" --> Q[目的地机场复飞后<br>按飞行计划飞往备降场];